<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: MainWindow Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:04:17 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('dc/df2/a00656.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-slots">Public Slots</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#friends">Friends</a> &#124;
<a href="../../de/ddd/a00653.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">MainWindow Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>The main window of the software.  
 <a href="../../dc/df2/a00656.php#details">More...</a></p>

<p><code>#include &lt;MainWindow.h&gt;</code></p>
<div class="dynheader">
Inheritance diagram for MainWindow:</div>
<div class="dyncontent">
<div class="center"><img src="../../d8/ddc/a00655.png" border="0" usemap="#MainWindow_inherit__map" alt="Inheritance graph"/></div>
<map name="MainWindow_inherit__map" id="MainWindow_inherit__map">
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for MainWindow:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/d2a/a00654.png" border="0" usemap="#MainWindow_coll__map" alt="Collaboration graph"/></div>
<map name="MainWindow_coll__map" id="MainWindow_coll__map">
<area shape="rect" id="node4" href="../../d5/d39/a00676.php" title="TeamMember" alt="" coords="43,109,146,136"/>
<area shape="rect" id="node5" title="STL class. " alt="" coords="215,109,331,136"/>
<area shape="rect" id="node7" href="../../df/d37/a00652.php" title="Globals" alt="" coords="311,288,377,315"/>
<area shape="rect" id="node9" title="STL class. " alt="" coords="400,109,480,136"/>
<area shape="rect" id="node10" title="STL class. " alt="" coords="377,5,503,47"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-slots"></a>
Public Slots</h2></td></tr>
<tr class="memitem:a0b85a19da77d0bed72a37d6be5844b59"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#a0b85a19da77d0bed72a37d6be5844b59">generalAllCheckstate</a> (int state)</td></tr>
<tr class="separator:a0b85a19da77d0bed72a37d6be5844b59"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac519892d0faafbd26acd7a7992f9285c"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#ac519892d0faafbd26acd7a7992f9285c">generalSaveDatas</a> ()</td></tr>
<tr class="separator:ac519892d0faafbd26acd7a7992f9285c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad3e2369acb314fbfea8a793858298b34"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#ad3e2369acb314fbfea8a793858298b34">generalCalculate</a> ()</td></tr>
<tr class="separator:ad3e2369acb314fbfea8a793858298b34"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a505c75251a666a8da570e569e864e346"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#a505c75251a666a8da570e569e864e346">reenableSave</a> ()</td></tr>
<tr class="separator:a505c75251a666a8da570e569e864e346"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7ec5a016e64ca83adf9bdf30513b190c"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#a7ec5a016e64ca83adf9bdf30513b190c">reenableGen</a> ()</td></tr>
<tr class="separator:a7ec5a016e64ca83adf9bdf30513b190c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a18dc86b52aff39ce15c68150d6381e7f"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#a18dc86b52aff39ce15c68150d6381e7f">computeIfNeeded</a> ()</td></tr>
<tr class="separator:a18dc86b52aff39ce15c68150d6381e7f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad5798c89ebbf4b15a1d76866903418c9"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#ad5798c89ebbf4b15a1d76866903418c9">g_setAll</a> (const <a class="el" href="../../df/d37/a00652.php">Globals</a> &amp;gl, const std::vector&lt; <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &gt; &amp;tm, const <a class="el" href="../../df/d46/a00664.php">Planning</a> &amp;pl)</td></tr>
<tr class="separator:ad5798c89ebbf4b15a1d76866903418c9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afbf23089969aeac3ae5ae2dc194460ef"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#afbf23089969aeac3ae5ae2dc194460ef">addMember</a> ()</td></tr>
<tr class="separator:afbf23089969aeac3ae5ae2dc194460ef"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4635fbbd25941294d7ddd280489092a8"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#a4635fbbd25941294d7ddd280489092a8">editMember</a> (QTableWidgetItem *item)</td></tr>
<tr class="separator:a4635fbbd25941294d7ddd280489092a8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a152f25e38ce6c4087fc2bfebd67ba2b7"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#a152f25e38ce6c4087fc2bfebd67ba2b7">deleteMember</a> ()</td></tr>
<tr class="separator:a152f25e38ce6c4087fc2bfebd67ba2b7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae7370d2140bb3823dfd8cc85ef4e6161"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#ae7370d2140bb3823dfd8cc85ef4e6161">updateSelectedMember</a> (int row, int)</td></tr>
<tr class="separator:ae7370d2140bb3823dfd8cc85ef4e6161"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a173388227e3b48ce310ff34be1f3535e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#a173388227e3b48ce310ff34be1f3535e">t_setAll</a> (const <a class="el" href="../../df/d37/a00652.php">Globals</a> &amp;gl, const std::vector&lt; <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &gt; &amp;tm, const <a class="el" href="../../df/d46/a00664.php">Planning</a> &amp;pl)</td></tr>
<tr class="separator:a173388227e3b48ce310ff34be1f3535e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a16ccde3508f4c90dde1b350fec24e48c"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#a16ccde3508f4c90dde1b350fec24e48c">p_setAll</a> (const <a class="el" href="../../df/d37/a00652.php">Globals</a> &amp;gl, const std::vector&lt; <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &gt; &amp;tm, const <a class="el" href="../../df/d46/a00664.php">Planning</a> &amp;pl)</td></tr>
<tr class="separator:a16ccde3508f4c90dde1b350fec24e48c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a221eba81c17c821ef10640da071f8ea9"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#a221eba81c17c821ef10640da071f8ea9">MainWindow</a> (<a class="el" href="../../dc/d62/a00640.php">Api</a> &amp;api, QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:a221eba81c17c821ef10640da071f8ea9"><td class="mdescLeft">&#160;</td><td class="mdescRight">The constructor of the class.  <a href="#a221eba81c17c821ef10640da071f8ea9">More...</a><br /></td></tr>
<tr class="separator:a221eba81c17c821ef10640da071f8ea9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9a780b70b080b3e745298191099bba4d"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#a9a780b70b080b3e745298191099bba4d">~MainWindow</a> ()</td></tr>
<tr class="separator:a9a780b70b080b3e745298191099bba4d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae21b4ca2c156eb550dcfec3df44cc71a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#ae21b4ca2c156eb550dcfec3df44cc71a">initWindow</a> ()</td></tr>
<tr class="separator:ae21b4ca2c156eb550dcfec3df44cc71a"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr class="memitem:afb4788b7a84063543823a0feb8d134b9"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../df/d37/a00652.php">Globals</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#afb4788b7a84063543823a0feb8d134b9">_p_globals</a></td></tr>
<tr class="separator:afb4788b7a84063543823a0feb8d134b9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6b1643e8e22c9319b8930f8c1780560c"><td class="memItemLeft" align="right" valign="top">std::vector&lt; <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#a6b1643e8e22c9319b8930f8c1780560c">_p_teamMembers</a></td></tr>
<tr class="separator:a6b1643e8e22c9319b8930f8c1780560c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="friends"></a>
Friends</h2></td></tr>
<tr class="memitem:a17791c185ba058b9c17f7e4f070cb09b"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/df2/a00656.php#a17791c185ba058b9c17f7e4f070cb09b">operator==</a> (const <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &amp;a, const int &amp;b)</td></tr>
<tr class="separator:a17791c185ba058b9c17f7e4f070cb09b"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>The main window of the software. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a221eba81c17c821ef10640da071f8ea9"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a221eba81c17c821ef10640da071f8ea9">&#9670;&nbsp;</a></span>MainWindow()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">MainWindow::MainWindow </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../dc/d62/a00640.php">Api</a> &amp;&#160;</td>
          <td class="paramname"><em>api</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>parent</em> = <code>nullptr</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>The constructor of the class. </p>

</div>
</div>
<a id="a9a780b70b080b3e745298191099bba4d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9a780b70b080b3e745298191099bba4d">&#9670;&nbsp;</a></span>~MainWindow()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual MainWindow::~MainWindow </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="afbf23089969aeac3ae5ae2dc194460ef"></a>
<h2 class="memtitle"><span class="permalink"><a href="#afbf23089969aeac3ae5ae2dc194460ef">&#9670;&nbsp;</a></span>addMember</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::addMember </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a18dc86b52aff39ce15c68150d6381e7f"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a18dc86b52aff39ce15c68150d6381e7f">&#9670;&nbsp;</a></span>computeIfNeeded</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::computeIfNeeded </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a152f25e38ce6c4087fc2bfebd67ba2b7"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a152f25e38ce6c4087fc2bfebd67ba2b7">&#9670;&nbsp;</a></span>deleteMember</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::deleteMember </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a4635fbbd25941294d7ddd280489092a8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a4635fbbd25941294d7ddd280489092a8">&#9670;&nbsp;</a></span>editMember</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::editMember </td>
          <td>(</td>
          <td class="paramtype">QTableWidgetItem *&#160;</td>
          <td class="paramname"><em>item</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ad5798c89ebbf4b15a1d76866903418c9"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ad5798c89ebbf4b15a1d76866903418c9">&#9670;&nbsp;</a></span>g_setAll</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::g_setAll </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="../../df/d37/a00652.php">Globals</a> &amp;&#160;</td>
          <td class="paramname"><em>gl</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::vector&lt; <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &gt; &amp;&#160;</td>
          <td class="paramname"><em>tm</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="../../df/d46/a00664.php">Planning</a> &amp;&#160;</td>
          <td class="paramname"><em>pl</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a0b85a19da77d0bed72a37d6be5844b59"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0b85a19da77d0bed72a37d6be5844b59">&#9670;&nbsp;</a></span>generalAllCheckstate</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::generalAllCheckstate </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>state</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ad3e2369acb314fbfea8a793858298b34"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ad3e2369acb314fbfea8a793858298b34">&#9670;&nbsp;</a></span>generalCalculate</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::generalCalculate </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ac519892d0faafbd26acd7a7992f9285c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac519892d0faafbd26acd7a7992f9285c">&#9670;&nbsp;</a></span>generalSaveDatas</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::generalSaveDatas </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ae21b4ca2c156eb550dcfec3df44cc71a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae21b4ca2c156eb550dcfec3df44cc71a">&#9670;&nbsp;</a></span>initWindow()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::initWindow </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a16ccde3508f4c90dde1b350fec24e48c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a16ccde3508f4c90dde1b350fec24e48c">&#9670;&nbsp;</a></span>p_setAll</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::p_setAll </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="../../df/d37/a00652.php">Globals</a> &amp;&#160;</td>
          <td class="paramname"><em>gl</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::vector&lt; <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &gt; &amp;&#160;</td>
          <td class="paramname"><em>tm</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="../../df/d46/a00664.php">Planning</a> &amp;&#160;</td>
          <td class="paramname"><em>pl</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a7ec5a016e64ca83adf9bdf30513b190c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7ec5a016e64ca83adf9bdf30513b190c">&#9670;&nbsp;</a></span>reenableGen</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::reenableGen </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a505c75251a666a8da570e569e864e346"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a505c75251a666a8da570e569e864e346">&#9670;&nbsp;</a></span>reenableSave</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::reenableSave </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a173388227e3b48ce310ff34be1f3535e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a173388227e3b48ce310ff34be1f3535e">&#9670;&nbsp;</a></span>t_setAll</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::t_setAll </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="../../df/d37/a00652.php">Globals</a> &amp;&#160;</td>
          <td class="paramname"><em>gl</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::vector&lt; <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &gt; &amp;&#160;</td>
          <td class="paramname"><em>tm</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="../../df/d46/a00664.php">Planning</a> &amp;&#160;</td>
          <td class="paramname"><em>pl</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ae7370d2140bb3823dfd8cc85ef4e6161"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae7370d2140bb3823dfd8cc85ef4e6161">&#9670;&nbsp;</a></span>updateSelectedMember</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void MainWindow::updateSelectedMember </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>row</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname">&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Friends And Related Function Documentation</h2>
<a id="a17791c185ba058b9c17f7e4f070cb09b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a17791c185ba058b9c17f7e4f070cb09b">&#9670;&nbsp;</a></span>operator==</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">bool operator== </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &amp;&#160;</td>
          <td class="paramname"><em>a</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const int &amp;&#160;</td>
          <td class="paramname"><em>b</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">friend</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a id="afb4788b7a84063543823a0feb8d134b9"></a>
<h2 class="memtitle"><span class="permalink"><a href="#afb4788b7a84063543823a0feb8d134b9">&#9670;&nbsp;</a></span>_p_globals</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../df/d37/a00652.php">Globals</a> MainWindow::_p_globals</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a6b1643e8e22c9319b8930f8c1780560c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a6b1643e8e22c9319b8930f8c1780560c">&#9670;&nbsp;</a></span>_p_teamMembers</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::vector&lt;<a class="el" href="../../d5/d39/a00676.php">TeamMember</a>&gt; MainWindow::_p_teamMembers</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d8/d41/a00038.php">MainWindow.h</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
