component_depth: 9
exclude:
- auth/
- PlanningService/
- register/
- TeamMemberService/
- TeamService/
- UserService/
- verification/
include:
- auth/src/
- PlanningService/src/
- register/src/
- TeamMemberService/src/
- TeamService/src/
- UserService/src/
- verification/src/
