#!/bin/bash

PROG_DIR=$PWD/`dirname $0`
SCREEN_NAME=graphql
PORTs="4000"

function enablePort() {
	if [ "`sudo iptables --list | grep $1`" = "" ]
	then
		sudo iptables -A INPUT -p tcp --dport $1 -j ACCEPT
	fi
}

function enablePorts() {
	for port in `echo -e $PORTs`
	do
		enablePort $port
	done
}

function run(){
	echo "Starting..."

	scr=`screen -list | grep "${SCREEN_NAME}" | tr -s '\t' | sed "s/\t/ /g" | tr -s ' ' | cut -d ' ' -f 2`

	if ! [ "$scr" = "" ]
	then
		screen -S $scr -X stuff "^C"
		screen -S $scr -X stuff "exit\n"
	fi

	screen -dmS ${SCREEN_NAME}
	screen -S ${SCREEN_NAME} -X stuff "node server.js\n"

	enablePorts

	exit 0
}

while [ -n "$1" ]; do
	case "$1" in
		-r)
			run
			;;
		*)
			echo "Option $1 not recognized"
			exit 1 ;;
	esac

	shift
done

git pull
./`basename $0` -r

exit 0
