#!/bin/bash

PROG_DIR=$PWD/`dirname $0`
SCREEN_NAME=graphql

git pull

scr=`screen -list | grep "${SCREEN_NAME}" | tr -s '\t' | sed "s/\t/ /g" | tr -s ' ' | cut -d ' ' -f 2`

if ! [ "$scr" = "" ]
then
	screen -S $scr -X stuff "^C"
	screen -S $scr -X stuff "exit\n"
fi

screen -dS ${SCREEN_NAME}
screen -S ${SCREEN_NAME} -X stuff "node server.js\n"

exit 0
