<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: RegisterWidget Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:25:59 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d1/d51/a00628.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-slots">Public Slots</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-attribs">Public Attributes</a> &#124;
<a href="#pri-methods">Private Member Functions</a> &#124;
<a href="#pri-attribs">Private Attributes</a> &#124;
<a href="../../d2/d34/a00625.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">RegisterWidget Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>The main window of the software.  
 <a href="../../d1/d51/a00628.php#details">More...</a></p>

<p><code>#include &lt;RegisterWidget.h&gt;</code></p>
<div class="dynheader">
Inheritance diagram for RegisterWidget:</div>
<div class="dyncontent">
<div class="center"><img src="../../d3/da3/a00627.png" border="0" usemap="#RegisterWidget_inherit__map" alt="Inheritance graph"/></div>
</div>
<div class="dynheader">
Collaboration diagram for RegisterWidget:</div>
<div class="dyncontent">
<div class="center"><img src="../../d6/dfa/a00626.png" border="0" usemap="#RegisterWidget_coll__map" alt="Collaboration graph"/></div>
<map name="RegisterWidget_coll__map" id="RegisterWidget_coll__map">
<area shape="rect" id="node4" title="STL class. " alt="" coords="93,160,173,237"/>
<area shape="rect" id="node5" title="STL class. " alt="" coords="69,5,196,97"/>
<area shape="rect" id="node6" title="STL class. " alt="" coords="197,160,319,237"/>
</map>
</div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-slots"></a>
Public Slots</h2></td></tr>
<tr class="memitem:adc0b4a0a0877a77fcf6e4b0f8292da6c"><td class="memItemLeft" align="right" valign="top"><a id="adc0b4a0a0877a77fcf6e4b0f8292da6c"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>generalAllCheckstate</b> (int state)</td></tr>
<tr class="separator:adc0b4a0a0877a77fcf6e4b0f8292da6c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a7807ba4d5048e2b3134dda99cd4c19f3"><td class="memItemLeft" align="right" valign="top"><a id="a7807ba4d5048e2b3134dda99cd4c19f3"></a>
&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d51/a00628.php#a7807ba4d5048e2b3134dda99cd4c19f3">RegisterWidget</a> (bool passless=false, QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:a7807ba4d5048e2b3134dda99cd4c19f3"><td class="mdescLeft">&#160;</td><td class="mdescRight">The constructor of the class. <br /></td></tr>
<tr class="separator:a7807ba4d5048e2b3134dda99cd4c19f3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab995ac919d7fbca08fcbfbba4172e0e7"><td class="memItemLeft" align="right" valign="top"><a id="ab995ac919d7fbca08fcbfbba4172e0e7"></a>
std::string&#160;</td><td class="memItemRight" valign="bottom"><b>getDaysOff</b> () const</td></tr>
<tr class="separator:ab995ac919d7fbca08fcbfbba4172e0e7"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-attribs"></a>
Public Attributes</h2></td></tr>
<tr class="memitem:a74237be10533acff46f14589b3568ade"><td class="memItemLeft" align="right" valign="top"><a id="a74237be10533acff46f14589b3568ade"></a>
QLineEdit *&#160;</td><td class="memItemRight" valign="bottom"><b>_username</b></td></tr>
<tr class="separator:a74237be10533acff46f14589b3568ade"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aff0471897ece6bb0c08ea2a4e5e035e6"><td class="memItemLeft" align="right" valign="top"><a id="aff0471897ece6bb0c08ea2a4e5e035e6"></a>
QLineEdit *&#160;</td><td class="memItemRight" valign="bottom"><b>_password</b></td></tr>
<tr class="separator:aff0471897ece6bb0c08ea2a4e5e035e6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5c1cf1097d44adec4ab1edc689609e08"><td class="memItemLeft" align="right" valign="top"><a id="a5c1cf1097d44adec4ab1edc689609e08"></a>
QLineEdit *&#160;</td><td class="memItemRight" valign="bottom"><b>_passwordConf</b></td></tr>
<tr class="separator:a5c1cf1097d44adec4ab1edc689609e08"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af743f98c0d1088e3955c11f7ecca8ad8"><td class="memItemLeft" align="right" valign="top"><a id="af743f98c0d1088e3955c11f7ecca8ad8"></a>
QCheckBox *&#160;</td><td class="memItemRight" valign="bottom"><b>_checkAll</b></td></tr>
<tr class="separator:af743f98c0d1088e3955c11f7ecca8ad8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae3439ba0a314e23e82a9a136a4163f84"><td class="memItemLeft" align="right" valign="top"><a id="ae3439ba0a314e23e82a9a136a4163f84"></a>
QLineEdit *&#160;</td><td class="memItemRight" valign="bottom"><b>_firstName</b></td></tr>
<tr class="separator:ae3439ba0a314e23e82a9a136a4163f84"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a42ef8b4599d867b0d7ad08c8362d696d"><td class="memItemLeft" align="right" valign="top"><a id="a42ef8b4599d867b0d7ad08c8362d696d"></a>
QLineEdit *&#160;</td><td class="memItemRight" valign="bottom"><b>_lastName</b></td></tr>
<tr class="separator:a42ef8b4599d867b0d7ad08c8362d696d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abfaaa76d8f2a3eb77fbe47c88135031e"><td class="memItemLeft" align="right" valign="top"><a id="abfaaa76d8f2a3eb77fbe47c88135031e"></a>
QDoubleSpinBox *&#160;</td><td class="memItemRight" valign="bottom"><b>_hoursPerWeek</b></td></tr>
<tr class="separator:abfaaa76d8f2a3eb77fbe47c88135031e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac586ce09560b4282faf3adbd26aeba3c"><td class="memItemLeft" align="right" valign="top"><a id="ac586ce09560b4282faf3adbd26aeba3c"></a>
std::map&lt; std::string, QCheckBox * &gt;&#160;</td><td class="memItemRight" valign="bottom"><b>_t_daysCheckboxes</b></td></tr>
<tr class="separator:ac586ce09560b4282faf3adbd26aeba3c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pri-methods"></a>
Private Member Functions</h2></td></tr>
<tr class="memitem:a3cc87e8e29bda172f4bd925d2230b38f"><td class="memItemLeft" align="right" valign="top"><a id="a3cc87e8e29bda172f4bd925d2230b38f"></a>
&#160;</td><td class="memItemRight" valign="bottom"><b>RegisterWidget</b> (const <a class="el" href="../../d1/d51/a00628.php">RegisterWidget</a> &amp;other)</td></tr>
<tr class="separator:a3cc87e8e29bda172f4bd925d2230b38f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aef939c7556b06baff68a82375cd105cd"><td class="memItemLeft" align="right" valign="top"><a id="aef939c7556b06baff68a82375cd105cd"></a>
<a class="el" href="../../d1/d51/a00628.php">RegisterWidget</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>operator=</b> (const <a class="el" href="../../d1/d51/a00628.php">RegisterWidget</a> &amp;other)</td></tr>
<tr class="separator:aef939c7556b06baff68a82375cd105cd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa77394f1e4a09c8fca1290258f79d086"><td class="memItemLeft" align="right" valign="top"><a id="aa77394f1e4a09c8fca1290258f79d086"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>init</b> (const <a class="el" href="../../d1/d51/a00628.php">RegisterWidget</a> *other=nullptr)</td></tr>
<tr class="separator:aa77394f1e4a09c8fca1290258f79d086"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pri-attribs"></a>
Private Attributes</h2></td></tr>
<tr class="memitem:ac718a184f68ddf595367b91f8ad8e9b5"><td class="memItemLeft" align="right" valign="top"><a id="ac718a184f68ddf595367b91f8ad8e9b5"></a>
QVBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><b>centerLayout</b></td></tr>
<tr class="separator:ac718a184f68ddf595367b91f8ad8e9b5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab5d6d76215556bcf8c6a4dc6f4c720e0"><td class="memItemLeft" align="right" valign="top"><a id="ab5d6d76215556bcf8c6a4dc6f4c720e0"></a>
bool&#160;</td><td class="memItemRight" valign="bottom"><b>_passless</b></td></tr>
<tr class="separator:ab5d6d76215556bcf8c6a4dc6f4c720e0"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>The main window of the software. </p>
</div><hr/>The documentation for this class was generated from the following file:<ul>
<li>RegisterWidget.h</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../d1/d51/a00628.php">RegisterWidget</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
