<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: ConnectWindow Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:25:59 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d4/d14/a00608.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-slots">Public Slots</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-methods">Protected Member Functions</a> &#124;
<a href="#pri-methods">Private Member Functions</a> &#124;
<a href="#pri-attribs">Private Attributes</a> &#124;
<a href="../../d0/d1c/a00605.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">ConnectWindow Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>The main window of the software.  
 <a href="../../d4/d14/a00608.php#details">More...</a></p>

<p><code>#include &lt;ConnectWindow.h&gt;</code></p>
<div class="dynheader">
Inheritance diagram for ConnectWindow:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/d07/a00607.png" border="0" usemap="#ConnectWindow_inherit__map" alt="Inheritance graph"/></div>
</div>
<div class="dynheader">
Collaboration diagram for ConnectWindow:</div>
<div class="dyncontent">
<div class="center"><img src="../../d8/d00/a00606.png" border="0" usemap="#ConnectWindow_coll__map" alt="Collaboration graph"/></div>
<map name="ConnectWindow_coll__map" id="ConnectWindow_coll__map">
<area shape="rect" id="node12" href="../../d4/d2a/a00632.php" title="The main window of the software. " alt="" coords="476,1747,609,2044"/>
<area shape="rect" id="node16" href="../../db/db5/a00616.php" title="The main window of the software. " alt="" coords="740,1395,919,2396"/>
<area shape="rect" id="node3" href="../../d6/d75/a00604.php" title="A class to talk with the remote apis. " alt="" coords="374,815,570,1303"/>
<area shape="rect" id="node6" title="STL class. " alt="" coords="727,300,807,377"/>
<area shape="rect" id="node18" href="../../db/ddc/a00636.php" title="{TeamMember\n|&#45; _nbHours\l&#45; _firstName\l&#45; _lastName\l|+ TeamMember()\l+ ~TeamMember()\l+ getId()\l+ getNbHours()\l+ getFirstName()\l+ getLastName()\l+ getDaysOff()\l+ daysOffToQString()\l+ setId()\l+ setNbHours()\l+ setFirstName()\l+ setLastName()\l+ setDaysOff()\l+ setDaysOffFromQString()\l}" alt="" coords="1098,455,1281,752"/>
<area shape="rect" id="node7" title="STL class. " alt="" coords="703,145,830,237"/>
<area shape="rect" id="node8" title="STL class. " alt="" coords="311,300,433,377"/>
<area shape="rect" id="node20" title="STL class. " alt="" coords="1002,153,1118,230"/>
<area shape="rect" id="node13" href="../../d1/d51/a00628.php" title="The main window of the software. " alt="" coords="594,917,761,1200"/>
<area shape="rect" id="node21" href="../../d3/dd6/a00624.php" title="{Planning\n||+ Planning()\l+ ~Planning()\l+ get()\l}" alt="" coords="1307,1005,1407,1112"/>
<area shape="rect" id="node22" href="../../d0/d8d/a00612.php" title="{Globals\n|+ startMin\l+ endMax\l+ nbHours\l|+ Globals()\l+ Globals()\l}" alt="" coords="985,998,1071,1119"/>
</map>
</div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-slots"></a>
Public Slots</h2></td></tr>
<tr class="memitem:a97ae82d5a82f16be9ef49190831cd627"><td class="memItemLeft" align="right" valign="top"><a id="a97ae82d5a82f16be9ef49190831cd627"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>connection</b> ()</td></tr>
<tr class="separator:a97ae82d5a82f16be9ef49190831cd627"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a30f9e20da21170b6fb4483631b8c2004"><td class="memItemLeft" align="right" valign="top"><a id="a30f9e20da21170b6fb4483631b8c2004"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>signingin</b> ()</td></tr>
<tr class="separator:a30f9e20da21170b6fb4483631b8c2004"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa7a256669919cd96e7762c92152779d5"><td class="memItemLeft" align="right" valign="top"><a id="aa7a256669919cd96e7762c92152779d5"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>goThrough</b> ()</td></tr>
<tr class="separator:aa7a256669919cd96e7762c92152779d5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9dfb8513eee377da498948fd808b08bf"><td class="memItemLeft" align="right" valign="top"><a id="a9dfb8513eee377da498948fd808b08bf"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>reenableLinks</b> ()</td></tr>
<tr class="separator:a9dfb8513eee377da498948fd808b08bf"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a922461f8248d2f68f992f391559e944b"><td class="memItemLeft" align="right" valign="top"><a id="a922461f8248d2f68f992f391559e944b"></a>
&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d14/a00608.php#a922461f8248d2f68f992f391559e944b">ConnectWindow</a> (<a class="el" href="../../db/db5/a00616.php">MainWindow</a> &amp;mainWind, <a class="el" href="../../d6/d75/a00604.php">Api</a> &amp;api, QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:a922461f8248d2f68f992f391559e944b"><td class="mdescLeft">&#160;</td><td class="mdescRight">The constructor of the class. <br /></td></tr>
<tr class="separator:a922461f8248d2f68f992f391559e944b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af84126e3453f6a29353686cdaf3c3d52"><td class="memItemLeft" align="right" valign="top"><a id="af84126e3453f6a29353686cdaf3c3d52"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>link</b> (<a class="el" href="../../d4/d2a/a00632.php">SigninWindow</a> *wind)</td></tr>
<tr class="separator:af84126e3453f6a29353686cdaf3c3d52"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a628c37f83de053fb7d68ee55dfbe24ec"><td class="memItemLeft" align="right" valign="top"><a id="a628c37f83de053fb7d68ee55dfbe24ec"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>testConnect</b> (const std::string &amp;user, const std::string &amp;pass)</td></tr>
<tr class="separator:a628c37f83de053fb7d68ee55dfbe24ec"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4241ce4be37f44d35e624bef31446ec9"><td class="memItemLeft" align="right" valign="top"><a id="a4241ce4be37f44d35e624bef31446ec9"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>testRegister</b> ()</td></tr>
<tr class="separator:a4241ce4be37f44d35e624bef31446ec9"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-methods"></a>
Protected Member Functions</h2></td></tr>
<tr class="memitem:a0f5ef34d29f827d44330accba2e81e86"><td class="memItemLeft" align="right" valign="top"><a id="a0f5ef34d29f827d44330accba2e81e86"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>showEvent</b> (QShowEvent *event)</td></tr>
<tr class="separator:a0f5ef34d29f827d44330accba2e81e86"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pri-methods"></a>
Private Member Functions</h2></td></tr>
<tr class="memitem:a2a74d621a2fca59846652819a809ebfd"><td class="memItemLeft" align="right" valign="top"><a id="a2a74d621a2fca59846652819a809ebfd"></a>
&#160;</td><td class="memItemRight" valign="bottom"><b>ConnectWindow</b> (const <a class="el" href="../../d4/d14/a00608.php">ConnectWindow</a> &amp;other)</td></tr>
<tr class="separator:a2a74d621a2fca59846652819a809ebfd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad06c1358cd2411ebfe88917cbf914ce2"><td class="memItemLeft" align="right" valign="top"><a id="ad06c1358cd2411ebfe88917cbf914ce2"></a>
<a class="el" href="../../d4/d14/a00608.php">ConnectWindow</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>operator=</b> (const <a class="el" href="../../d4/d14/a00608.php">ConnectWindow</a> &amp;other)</td></tr>
<tr class="separator:ad06c1358cd2411ebfe88917cbf914ce2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae386105daf5d19f1f354f50472f9d874"><td class="memItemLeft" align="right" valign="top"><a id="ae386105daf5d19f1f354f50472f9d874"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>init</b> (const <a class="el" href="../../d4/d14/a00608.php">ConnectWindow</a> *other=nullptr)</td></tr>
<tr class="separator:ae386105daf5d19f1f354f50472f9d874"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pri-attribs"></a>
Private Attributes</h2></td></tr>
<tr class="memitem:a4cf9a88b88bbd146fb3798631989598f"><td class="memItemLeft" align="right" valign="top"><a id="a4cf9a88b88bbd146fb3798631989598f"></a>
QVBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><b>centerLayout</b></td></tr>
<tr class="separator:a4cf9a88b88bbd146fb3798631989598f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7574b6845a9df5f9a6c3959b4c4476d0"><td class="memItemLeft" align="right" valign="top"><a id="a7574b6845a9df5f9a6c3959b4c4476d0"></a>
QWidget *&#160;</td><td class="memItemRight" valign="bottom"><b>center</b></td></tr>
<tr class="separator:a7574b6845a9df5f9a6c3959b4c4476d0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abef9f6df480082080ac2369d45030d38"><td class="memItemLeft" align="right" valign="top"><a id="abef9f6df480082080ac2369d45030d38"></a>
<a class="el" href="../../d4/d2a/a00632.php">SigninWindow</a> *&#160;</td><td class="memItemRight" valign="bottom"><b>_signinWindow</b></td></tr>
<tr class="separator:abef9f6df480082080ac2369d45030d38"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9923b957870f20f0ffa9c0d7bd28efdd"><td class="memItemLeft" align="right" valign="top"><a id="a9923b957870f20f0ffa9c0d7bd28efdd"></a>
QLineEdit *&#160;</td><td class="memItemRight" valign="bottom"><b>_username</b></td></tr>
<tr class="separator:a9923b957870f20f0ffa9c0d7bd28efdd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2f14c7f204e2f5523fa4d3442abbda38"><td class="memItemLeft" align="right" valign="top"><a id="a2f14c7f204e2f5523fa4d3442abbda38"></a>
QLineEdit *&#160;</td><td class="memItemRight" valign="bottom"><b>_password</b></td></tr>
<tr class="separator:a2f14c7f204e2f5523fa4d3442abbda38"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2f6c8d9554853540e47c03df2b25a310"><td class="memItemLeft" align="right" valign="top"><a id="a2f6c8d9554853540e47c03df2b25a310"></a>
QPushButton *&#160;</td><td class="memItemRight" valign="bottom"><b>_connect</b></td></tr>
<tr class="separator:a2f6c8d9554853540e47c03df2b25a310"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4f39a3777b052cd8d6c0782d78aca779"><td class="memItemLeft" align="right" valign="top"><a id="a4f39a3777b052cd8d6c0782d78aca779"></a>
QCommandLinkButton *&#160;</td><td class="memItemRight" valign="bottom"><b>_signin</b></td></tr>
<tr class="separator:a4f39a3777b052cd8d6c0782d78aca779"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aac64b05e447e14b86981432b854635b8"><td class="memItemLeft" align="right" valign="top"><a id="aac64b05e447e14b86981432b854635b8"></a>
<a class="el" href="../../db/db5/a00616.php">MainWindow</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>_mainWindow</b></td></tr>
<tr class="separator:aac64b05e447e14b86981432b854635b8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad68d5da50b971b1725cfa2f80b7cec9d"><td class="memItemLeft" align="right" valign="top"><a id="ad68d5da50b971b1725cfa2f80b7cec9d"></a>
<a class="el" href="../../d6/d75/a00604.php">Api</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>_api</b></td></tr>
<tr class="separator:ad68d5da50b971b1725cfa2f80b7cec9d"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>The main window of the software. </p>
</div><hr/>The documentation for this class was generated from the following file:<ul>
<li>ConnectWindow.h</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../d4/d14/a00608.php">ConnectWindow</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
