<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: BCrypt Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:04:17 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d9/d0f/a00644.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="../../db/d3a/a00641.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">BCrypt Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p><code>#include &lt;winbcrypt.h&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr class="memitem:a5b1ccbe2fdeebd86e2603c4108eda674"><td class="memItemLeft" align="right" valign="top">static std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/d0f/a00644.php#a5b1ccbe2fdeebd86e2603c4108eda674">generateHash</a> (const std::string &amp;password, int workload=12)</td></tr>
<tr class="separator:a5b1ccbe2fdeebd86e2603c4108eda674"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa3338e2983d8ef8875fbf090742457be"><td class="memItemLeft" align="right" valign="top">static bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/d0f/a00644.php#aa3338e2983d8ef8875fbf090742457be">validatePassword</a> (const std::string &amp;password, const std::string &amp;hash)</td></tr>
<tr class="separator:aa3338e2983d8ef8875fbf090742457be"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5b1ccbe2fdeebd86e2603c4108eda674"><td class="memItemLeft" align="right" valign="top">static std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/d0f/a00644.php#a5b1ccbe2fdeebd86e2603c4108eda674">generateHash</a> (const std::string &amp;password, int workload=12)</td></tr>
<tr class="separator:a5b1ccbe2fdeebd86e2603c4108eda674"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa3338e2983d8ef8875fbf090742457be"><td class="memItemLeft" align="right" valign="top">static bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/d0f/a00644.php#aa3338e2983d8ef8875fbf090742457be">validatePassword</a> (const std::string &amp;password, const std::string &amp;hash)</td></tr>
<tr class="separator:aa3338e2983d8ef8875fbf090742457be"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="a5b1ccbe2fdeebd86e2603c4108eda674"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a5b1ccbe2fdeebd86e2603c4108eda674">&#9670;&nbsp;</a></span>generateHash() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static std::string BCrypt::generateHash </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>password</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>workload</em> = <code>12</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/d0f/a00644_a5b1ccbe2fdeebd86e2603c4108eda674_cgraph.png" border="0" usemap="#d9/d0f/a00644_a5b1ccbe2fdeebd86e2603c4108eda674_cgraph" alt=""/></div>
<map name="d9/d0f/a00644_a5b1ccbe2fdeebd86e2603c4108eda674_cgraph" id="d9/d0f/a00644_a5b1ccbe2fdeebd86e2603c4108eda674_cgraph">
<area shape="rect" id="node2" href="../../d4/dee/a00008.php#a66e124b341e7ff6fdf0cf725bc535b3a" title="bcrypt_gensalt" alt="" coords="207,5,314,32"/>
<area shape="rect" id="node3" href="../../d4/dee/a00008.php#ad79e8a88481392abdde9e6c2f0b8be48" title="bcrypt_hashpw" alt="" coords="205,56,316,83"/>
</map>
</div>

</div>
</div>
<a id="a5b1ccbe2fdeebd86e2603c4108eda674"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a5b1ccbe2fdeebd86e2603c4108eda674">&#9670;&nbsp;</a></span>generateHash() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static std::string BCrypt::generateHash </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>password</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>workload</em> = <code>12</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/d0f/a00644_a5b1ccbe2fdeebd86e2603c4108eda674_cgraph.png" border="0" usemap="#d9/d0f/a00644_a5b1ccbe2fdeebd86e2603c4108eda674_cgraph" alt=""/></div>
<map name="d9/d0f/a00644_a5b1ccbe2fdeebd86e2603c4108eda674_cgraph" id="d9/d0f/a00644_a5b1ccbe2fdeebd86e2603c4108eda674_cgraph">
<area shape="rect" id="node2" href="../../d4/dee/a00008.php#a66e124b341e7ff6fdf0cf725bc535b3a" title="bcrypt_gensalt" alt="" coords="207,5,314,32"/>
<area shape="rect" id="node3" href="../../d4/dee/a00008.php#ad79e8a88481392abdde9e6c2f0b8be48" title="bcrypt_hashpw" alt="" coords="205,56,316,83"/>
</map>
</div>

</div>
</div>
<a id="aa3338e2983d8ef8875fbf090742457be"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa3338e2983d8ef8875fbf090742457be">&#9670;&nbsp;</a></span>validatePassword() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static bool BCrypt::validatePassword </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>password</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>hash</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/d0f/a00644_aa3338e2983d8ef8875fbf090742457be_cgraph.png" border="0" usemap="#d9/d0f/a00644_aa3338e2983d8ef8875fbf090742457be_cgraph" alt=""/></div>
<map name="d9/d0f/a00644_aa3338e2983d8ef8875fbf090742457be_cgraph" id="d9/d0f/a00644_aa3338e2983d8ef8875fbf090742457be_cgraph">
<area shape="rect" id="node2" href="../../d4/dee/a00008.php#aa91da2908f2fdd6f5d8a6e17645cc590" title="bcrypt_checkpw" alt="" coords="228,5,345,32"/>
</map>
</div>

</div>
</div>
<a id="aa3338e2983d8ef8875fbf090742457be"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa3338e2983d8ef8875fbf090742457be">&#9670;&nbsp;</a></span>validatePassword() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static bool BCrypt::validatePassword </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>password</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>hash</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/d0f/a00644_aa3338e2983d8ef8875fbf090742457be_cgraph.png" border="0" usemap="#d9/d0f/a00644_aa3338e2983d8ef8875fbf090742457be_cgraph" alt=""/></div>
<map name="d9/d0f/a00644_aa3338e2983d8ef8875fbf090742457be_cgraph" id="d9/d0f/a00644_aa3338e2983d8ef8875fbf090742457be_cgraph">
<area shape="rect" id="node2" href="../../d4/dee/a00008.php#aa91da2908f2fdd6f5d8a6e17645cc590" title="bcrypt_checkpw" alt="" coords="228,5,345,32"/>
</map>
</div>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li><a class="el" href="../../da/d45/a00011.php">BCrypt.hpp</a></li>
<li><a class="el" href="../../d6/d5b/a00026.php">winbcrypt.h</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../d9/d0f/a00644.php">BCrypt</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
