<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: MainWindow Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:25:59 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('db/db5/a00616.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-slots">Public Slots</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#pri-methods">Private Member Functions</a> &#124;
<a href="#pri-attribs">Private Attributes</a> &#124;
<a href="#friends">Friends</a> &#124;
<a href="../../d1/d6e/a00613.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">MainWindow Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>The main window of the software.  
 <a href="../../db/db5/a00616.php#details">More...</a></p>

<p><code>#include &lt;MainWindow.h&gt;</code></p>
<div class="dynheader">
Inheritance diagram for MainWindow:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/dd8/a00615.png" border="0" usemap="#MainWindow_inherit__map" alt="Inheritance graph"/></div>
</div>
<div class="dynheader">
Collaboration diagram for MainWindow:</div>
<div class="dyncontent">
<div class="center"><img src="../../d7/d80/a00614.png" border="0" usemap="#MainWindow_coll__map" alt="Collaboration graph"/></div>
<map name="MainWindow_coll__map" id="MainWindow_coll__map">
<area shape="rect" id="node4" title="STL class. " alt="" coords="727,300,807,377"/>
<area shape="rect" id="node9" href="../../d6/d75/a00604.php" title="A class to talk with the remote apis. " alt="" coords="550,815,746,1303"/>
<area shape="rect" id="node14" href="../../db/ddc/a00636.php" title="{TeamMember\n|&#45; _nbHours\l&#45; _firstName\l&#45; _lastName\l|+ TeamMember()\l+ ~TeamMember()\l+ getId()\l+ getNbHours()\l+ getFirstName()\l+ getLastName()\l+ getDaysOff()\l+ daysOffToQString()\l+ setId()\l+ setNbHours()\l+ setFirstName()\l+ setLastName()\l+ setDaysOff()\l+ setDaysOffFromQString()\l}" alt="" coords="1110,455,1293,752"/>
<area shape="rect" id="node5" title="STL class. " alt="" coords="704,145,830,237"/>
<area shape="rect" id="node6" title="STL class. " alt="" coords="346,300,468,377"/>
<area shape="rect" id="node16" title="STL class. " alt="" coords="1006,153,1122,230"/>
<area shape="rect" id="node17" href="../../d3/dd6/a00624.php" title="{Planning\n||+ Planning()\l+ ~Planning()\l+ get()\l}" alt="" coords="881,1005,981,1112"/>
<area shape="rect" id="node18" href="../../d0/d8d/a00612.php" title="{Globals\n|+ startMin\l+ endMax\l+ nbHours\l|+ Globals()\l+ Globals()\l}" alt="" coords="770,998,857,1119"/>
</map>
</div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-slots"></a>
Public Slots</h2></td></tr>
<tr class="memitem:a0b85a19da77d0bed72a37d6be5844b59"><td class="memItemLeft" align="right" valign="top"><a id="a0b85a19da77d0bed72a37d6be5844b59"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>generalAllCheckstate</b> (int state)</td></tr>
<tr class="separator:a0b85a19da77d0bed72a37d6be5844b59"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac519892d0faafbd26acd7a7992f9285c"><td class="memItemLeft" align="right" valign="top"><a id="ac519892d0faafbd26acd7a7992f9285c"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>generalSaveDatas</b> ()</td></tr>
<tr class="separator:ac519892d0faafbd26acd7a7992f9285c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad3e2369acb314fbfea8a793858298b34"><td class="memItemLeft" align="right" valign="top"><a id="ad3e2369acb314fbfea8a793858298b34"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>generalCalculate</b> ()</td></tr>
<tr class="separator:ad3e2369acb314fbfea8a793858298b34"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a505c75251a666a8da570e569e864e346"><td class="memItemLeft" align="right" valign="top"><a id="a505c75251a666a8da570e569e864e346"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>reenableSave</b> ()</td></tr>
<tr class="separator:a505c75251a666a8da570e569e864e346"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7ec5a016e64ca83adf9bdf30513b190c"><td class="memItemLeft" align="right" valign="top"><a id="a7ec5a016e64ca83adf9bdf30513b190c"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>reenableGen</b> ()</td></tr>
<tr class="separator:a7ec5a016e64ca83adf9bdf30513b190c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a18dc86b52aff39ce15c68150d6381e7f"><td class="memItemLeft" align="right" valign="top"><a id="a18dc86b52aff39ce15c68150d6381e7f"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>computeIfNeeded</b> ()</td></tr>
<tr class="separator:a18dc86b52aff39ce15c68150d6381e7f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad5798c89ebbf4b15a1d76866903418c9"><td class="memItemLeft" align="right" valign="top"><a id="ad5798c89ebbf4b15a1d76866903418c9"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>g_setAll</b> (const <a class="el" href="../../d0/d8d/a00612.php">Globals</a> &amp;gl, const std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt; &amp;tm, const <a class="el" href="../../d3/dd6/a00624.php">Planning</a> &amp;pl)</td></tr>
<tr class="separator:ad5798c89ebbf4b15a1d76866903418c9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afbf23089969aeac3ae5ae2dc194460ef"><td class="memItemLeft" align="right" valign="top"><a id="afbf23089969aeac3ae5ae2dc194460ef"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>addMember</b> ()</td></tr>
<tr class="separator:afbf23089969aeac3ae5ae2dc194460ef"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4635fbbd25941294d7ddd280489092a8"><td class="memItemLeft" align="right" valign="top"><a id="a4635fbbd25941294d7ddd280489092a8"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>editMember</b> (QTableWidgetItem *item)</td></tr>
<tr class="separator:a4635fbbd25941294d7ddd280489092a8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a152f25e38ce6c4087fc2bfebd67ba2b7"><td class="memItemLeft" align="right" valign="top"><a id="a152f25e38ce6c4087fc2bfebd67ba2b7"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>deleteMember</b> ()</td></tr>
<tr class="separator:a152f25e38ce6c4087fc2bfebd67ba2b7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae7370d2140bb3823dfd8cc85ef4e6161"><td class="memItemLeft" align="right" valign="top"><a id="ae7370d2140bb3823dfd8cc85ef4e6161"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>updateSelectedMember</b> (int row, int)</td></tr>
<tr class="separator:ae7370d2140bb3823dfd8cc85ef4e6161"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a173388227e3b48ce310ff34be1f3535e"><td class="memItemLeft" align="right" valign="top"><a id="a173388227e3b48ce310ff34be1f3535e"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>t_setAll</b> (const <a class="el" href="../../d0/d8d/a00612.php">Globals</a> &amp;gl, const std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt; &amp;tm, const <a class="el" href="../../d3/dd6/a00624.php">Planning</a> &amp;pl)</td></tr>
<tr class="separator:a173388227e3b48ce310ff34be1f3535e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a16ccde3508f4c90dde1b350fec24e48c"><td class="memItemLeft" align="right" valign="top"><a id="a16ccde3508f4c90dde1b350fec24e48c"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>p_setAll</b> (const <a class="el" href="../../d0/d8d/a00612.php">Globals</a> &amp;gl, const std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt; &amp;tm, const <a class="el" href="../../d3/dd6/a00624.php">Planning</a> &amp;pl)</td></tr>
<tr class="separator:a16ccde3508f4c90dde1b350fec24e48c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a221eba81c17c821ef10640da071f8ea9"><td class="memItemLeft" align="right" valign="top"><a id="a221eba81c17c821ef10640da071f8ea9"></a>
&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db5/a00616.php#a221eba81c17c821ef10640da071f8ea9">MainWindow</a> (<a class="el" href="../../d6/d75/a00604.php">Api</a> &amp;api, QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:a221eba81c17c821ef10640da071f8ea9"><td class="mdescLeft">&#160;</td><td class="mdescRight">The constructor of the class. <br /></td></tr>
<tr class="separator:a221eba81c17c821ef10640da071f8ea9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae21b4ca2c156eb550dcfec3df44cc71a"><td class="memItemLeft" align="right" valign="top"><a id="ae21b4ca2c156eb550dcfec3df44cc71a"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>initWindow</b> ()</td></tr>
<tr class="separator:ae21b4ca2c156eb550dcfec3df44cc71a"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr class="memitem:afb4788b7a84063543823a0feb8d134b9"><td class="memItemLeft" align="right" valign="top"><a id="afb4788b7a84063543823a0feb8d134b9"></a>
<a class="el" href="../../d0/d8d/a00612.php">Globals</a>&#160;</td><td class="memItemRight" valign="bottom"><b>_p_globals</b></td></tr>
<tr class="separator:afb4788b7a84063543823a0feb8d134b9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6b1643e8e22c9319b8930f8c1780560c"><td class="memItemLeft" align="right" valign="top"><a id="a6b1643e8e22c9319b8930f8c1780560c"></a>
std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><b>_p_teamMembers</b></td></tr>
<tr class="separator:a6b1643e8e22c9319b8930f8c1780560c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pri-methods"></a>
Private Member Functions</h2></td></tr>
<tr class="memitem:a2a62619724514c79d48cb659eb94ad86"><td class="memItemLeft" align="right" valign="top"><a id="a2a62619724514c79d48cb659eb94ad86"></a>
&#160;</td><td class="memItemRight" valign="bottom"><b>MainWindow</b> (const <a class="el" href="../../db/db5/a00616.php">MainWindow</a> &amp;other)</td></tr>
<tr class="separator:a2a62619724514c79d48cb659eb94ad86"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a359a5f9844edc4e3218c08caf9212e68"><td class="memItemLeft" align="right" valign="top"><a id="a359a5f9844edc4e3218c08caf9212e68"></a>
<a class="el" href="../../db/db5/a00616.php">MainWindow</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>operator=</b> (const <a class="el" href="../../db/db5/a00616.php">MainWindow</a> &amp;other)</td></tr>
<tr class="separator:a359a5f9844edc4e3218c08caf9212e68"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a770b01cc281ec5fd1c40010f2a84410c"><td class="memItemLeft" align="right" valign="top"><a id="a770b01cc281ec5fd1c40010f2a84410c"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>init</b> (const <a class="el" href="../../db/db5/a00616.php">MainWindow</a> *other=nullptr)</td></tr>
<tr class="separator:a770b01cc281ec5fd1c40010f2a84410c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4e20a4a065fbb0e4d3532a45a0a91425"><td class="memItemLeft" align="right" valign="top"><a id="a4e20a4a065fbb0e4d3532a45a0a91425"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>closeEvent</b> (QCloseEvent *event)</td></tr>
<tr class="separator:a4e20a4a065fbb0e4d3532a45a0a91425"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0c542f813e1aec3561052a17263151b7"><td class="memItemLeft" align="right" valign="top"><a id="a0c542f813e1aec3561052a17263151b7"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>initGeneralTab</b> (QTabWidget *tabWidget)</td></tr>
<tr class="separator:a0c542f813e1aec3561052a17263151b7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7ebfb35520b88564c89d06e7b09d5aa8"><td class="memItemLeft" align="right" valign="top"><a id="a7ebfb35520b88564c89d06e7b09d5aa8"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>initGeneralTab</b> (QTabWidget *tabWidget, <a class="el" href="../../d0/d8d/a00612.php">Globals</a> initGlob)</td></tr>
<tr class="separator:a7ebfb35520b88564c89d06e7b09d5aa8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:add3ab4baee335f2c815ea2e0cd723f97"><td class="memItemLeft" align="right" valign="top"><a id="add3ab4baee335f2c815ea2e0cd723f97"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>resetGeneralTab</b> (QTabWidget *tabWidget)</td></tr>
<tr class="separator:add3ab4baee335f2c815ea2e0cd723f97"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a72b72050758a5b46a8f63c3742720adf"><td class="memItemLeft" align="right" valign="top"><a id="a72b72050758a5b46a8f63c3742720adf"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>deleteGeneralTab</b> (QTabWidget *tabWidget)</td></tr>
<tr class="separator:a72b72050758a5b46a8f63c3742720adf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8d91535d4d2e9f21e3433975f2652826"><td class="memItemLeft" align="right" valign="top"><a id="a8d91535d4d2e9f21e3433975f2652826"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>setValues</b> (<a class="el" href="../../d0/d8d/a00612.php">Globals</a> initGlob)</td></tr>
<tr class="separator:a8d91535d4d2e9f21e3433975f2652826"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4fdf89b37d7ca677e5553c079d6b14e8"><td class="memItemLeft" align="right" valign="top"><a id="a4fdf89b37d7ca677e5553c079d6b14e8"></a>
<a class="el" href="../../d0/d8d/a00612.php">Globals</a>&#160;</td><td class="memItemRight" valign="bottom"><b>translate</b> ()</td></tr>
<tr class="separator:a4fdf89b37d7ca677e5553c079d6b14e8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab6d7cca983665e8bc18712242c681de6"><td class="memItemLeft" align="right" valign="top"><a id="ab6d7cca983665e8bc18712242c681de6"></a>
QTime&#160;</td><td class="memItemRight" valign="bottom"><b>getQTimeFromFloat</b> (float time)</td></tr>
<tr class="separator:ab6d7cca983665e8bc18712242c681de6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a33387f442117e712e7934c361562f331"><td class="memItemLeft" align="right" valign="top"><a id="a33387f442117e712e7934c361562f331"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>initTeamTab</b> (QTabWidget *tabWidget)</td></tr>
<tr class="separator:a33387f442117e712e7934c361562f331"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae03d3c736c0fee49a9df257cc195a034"><td class="memItemLeft" align="right" valign="top"><a id="ae03d3c736c0fee49a9df257cc195a034"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>resetTeamTab</b> (QTabWidget *tabWidget)</td></tr>
<tr class="separator:ae03d3c736c0fee49a9df257cc195a034"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab402952687635e013359718af1de2e41"><td class="memItemLeft" align="right" valign="top"><a id="ab402952687635e013359718af1de2e41"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>deleteTeamTab</b> (QTabWidget *tabWidget)</td></tr>
<tr class="separator:ab402952687635e013359718af1de2e41"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a58387da1d3b88242a0f734f9e0a9d158"><td class="memItemLeft" align="right" valign="top"><a id="a58387da1d3b88242a0f734f9e0a9d158"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>initTeamTable</b> ()</td></tr>
<tr class="separator:a58387da1d3b88242a0f734f9e0a9d158"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a036495c22ee9f082bd723e97eba7e435"><td class="memItemLeft" align="right" valign="top"><a id="a036495c22ee9f082bd723e97eba7e435"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>initPlanningTab</b> (QTabWidget *tabWidget)</td></tr>
<tr class="separator:a036495c22ee9f082bd723e97eba7e435"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a859ae14c71e4debb1c21d3497167af29"><td class="memItemLeft" align="right" valign="top"><a id="a859ae14c71e4debb1c21d3497167af29"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>resetPlanningTab</b> (QTabWidget *tabWidget)</td></tr>
<tr class="separator:a859ae14c71e4debb1c21d3497167af29"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a25dd30afcf50e3b6dc506dd9260e78f5"><td class="memItemLeft" align="right" valign="top"><a id="a25dd30afcf50e3b6dc506dd9260e78f5"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>deletePlanningTab</b> (QTabWidget *tabWidget)</td></tr>
<tr class="separator:a25dd30afcf50e3b6dc506dd9260e78f5"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pri-attribs"></a>
Private Attributes</h2></td></tr>
<tr class="memitem:aaafcdcfeded1bbf62f6b7bf05a70f819"><td class="memItemLeft" align="right" valign="top"><a id="aaafcdcfeded1bbf62f6b7bf05a70f819"></a>
QVBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><b>centerLayout</b></td></tr>
<tr class="separator:aaafcdcfeded1bbf62f6b7bf05a70f819"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aebbf677c3c672b4627bde023aae8cc5d"><td class="memItemLeft" align="right" valign="top"><a id="aebbf677c3c672b4627bde023aae8cc5d"></a>
QWidget *&#160;</td><td class="memItemRight" valign="bottom"><b>center</b></td></tr>
<tr class="separator:aebbf677c3c672b4627bde023aae8cc5d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2b7eef73dbbc7cece6889cef4092c925"><td class="memItemLeft" align="right" valign="top"><a id="a2b7eef73dbbc7cece6889cef4092c925"></a>
QTabWidget *&#160;</td><td class="memItemRight" valign="bottom"><b>_tab</b></td></tr>
<tr class="separator:a2b7eef73dbbc7cece6889cef4092c925"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a579b74a045f9af9152407428ea23f1d1"><td class="memItemLeft" align="right" valign="top"><a id="a579b74a045f9af9152407428ea23f1d1"></a>
QWidget *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_tab</b></td></tr>
<tr class="separator:a579b74a045f9af9152407428ea23f1d1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aca0d693d253295a2a99e7cfcab0d2cf3"><td class="memItemLeft" align="right" valign="top"><a id="aca0d693d253295a2a99e7cfcab0d2cf3"></a>
QVBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_lay</b></td></tr>
<tr class="separator:aca0d693d253295a2a99e7cfcab0d2cf3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae1107f643a19983423d9070001951382"><td class="memItemLeft" align="right" valign="top"><a id="ae1107f643a19983423d9070001951382"></a>
QVBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_daysChoice</b></td></tr>
<tr class="separator:ae1107f643a19983423d9070001951382"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa9e71552e9a1773d1a1d67de3324bc7a"><td class="memItemLeft" align="right" valign="top"><a id="aa9e71552e9a1773d1a1d67de3324bc7a"></a>
QHBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_checkAllLay</b></td></tr>
<tr class="separator:aa9e71552e9a1773d1a1d67de3324bc7a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:accb60d49f29adfa58fb1b8170c668533"><td class="memItemLeft" align="right" valign="top"><a id="accb60d49f29adfa58fb1b8170c668533"></a>
QCheckBox *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_allCheckbox</b></td></tr>
<tr class="separator:accb60d49f29adfa58fb1b8170c668533"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4c9d0034794e82e7906e1ef189238ab6"><td class="memItemLeft" align="right" valign="top"><a id="a4c9d0034794e82e7906e1ef189238ab6"></a>
QHBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_checkDays</b></td></tr>
<tr class="separator:a4c9d0034794e82e7906e1ef189238ab6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aff1344a2e553d4228d5a04d84ec37207"><td class="memItemLeft" align="right" valign="top"><a id="aff1344a2e553d4228d5a04d84ec37207"></a>
std::map&lt; std::string, QCheckBox * &gt;&#160;</td><td class="memItemRight" valign="bottom"><b>_g_daysCheckboxes</b></td></tr>
<tr class="separator:aff1344a2e553d4228d5a04d84ec37207"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab6e5fcaef945c922475f8247380eeec6"><td class="memItemLeft" align="right" valign="top"><a id="ab6e5fcaef945c922475f8247380eeec6"></a>
QHBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_minTimeLay</b></td></tr>
<tr class="separator:ab6e5fcaef945c922475f8247380eeec6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad732e3faa84f5c5e062ef230504f7708"><td class="memItemLeft" align="right" valign="top"><a id="ad732e3faa84f5c5e062ef230504f7708"></a>
QTimeEdit *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_minTimeEdit</b></td></tr>
<tr class="separator:ad732e3faa84f5c5e062ef230504f7708"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a478381515eabf0a1cfff6c9e0dafcdb1"><td class="memItemLeft" align="right" valign="top"><a id="a478381515eabf0a1cfff6c9e0dafcdb1"></a>
QLabel *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_minTimeLabel</b></td></tr>
<tr class="separator:a478381515eabf0a1cfff6c9e0dafcdb1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae9f579716520463962e97ceb7a4f10f1"><td class="memItemLeft" align="right" valign="top"><a id="ae9f579716520463962e97ceb7a4f10f1"></a>
QHBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_maxTimeLay</b></td></tr>
<tr class="separator:ae9f579716520463962e97ceb7a4f10f1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae2178605ddcf6a8a228d467f8fe16f48"><td class="memItemLeft" align="right" valign="top"><a id="ae2178605ddcf6a8a228d467f8fe16f48"></a>
QTimeEdit *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_maxTimeEdit</b></td></tr>
<tr class="separator:ae2178605ddcf6a8a228d467f8fe16f48"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a07dba83a34b95c13c18216ad3306cc67"><td class="memItemLeft" align="right" valign="top"><a id="a07dba83a34b95c13c18216ad3306cc67"></a>
QLabel *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_maxTimeLabel</b></td></tr>
<tr class="separator:a07dba83a34b95c13c18216ad3306cc67"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:affd29f71ee51875a0c5108d86c258016"><td class="memItemLeft" align="right" valign="top"><a id="affd29f71ee51875a0c5108d86c258016"></a>
QHBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_defaultHoursLay</b></td></tr>
<tr class="separator:affd29f71ee51875a0c5108d86c258016"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acc5975cbbe95f860f28807f04668c6b1"><td class="memItemLeft" align="right" valign="top"><a id="acc5975cbbe95f860f28807f04668c6b1"></a>
QDoubleSpinBox *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_defaultHoursEdit</b></td></tr>
<tr class="separator:acc5975cbbe95f860f28807f04668c6b1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a604496fd8b05a256fd42857f6e8582b9"><td class="memItemLeft" align="right" valign="top"><a id="a604496fd8b05a256fd42857f6e8582b9"></a>
QLabel *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_defaultHoursLabel</b></td></tr>
<tr class="separator:a604496fd8b05a256fd42857f6e8582b9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8bfe7f00b3c0ba50703baa32d06e82e6"><td class="memItemLeft" align="right" valign="top"><a id="a8bfe7f00b3c0ba50703baa32d06e82e6"></a>
QToolBar *&#160;</td><td class="memItemRight" valign="bottom"><b>_g_toolBar</b></td></tr>
<tr class="separator:a8bfe7f00b3c0ba50703baa32d06e82e6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac5a7f857261819efa73a7066aa5a7301"><td class="memItemLeft" align="right" valign="top"><a id="ac5a7f857261819efa73a7066aa5a7301"></a>
QAction *&#160;</td><td class="memItemRight" valign="bottom"><b>_saveAct</b></td></tr>
<tr class="separator:ac5a7f857261819efa73a7066aa5a7301"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad0d888116fe23b0d7a5c132234485146"><td class="memItemLeft" align="right" valign="top"><a id="ad0d888116fe23b0d7a5c132234485146"></a>
QAction *&#160;</td><td class="memItemRight" valign="bottom"><b>_genAct</b></td></tr>
<tr class="separator:ad0d888116fe23b0d7a5c132234485146"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac7e613964435c0784650a1440e714b7a"><td class="memItemLeft" align="right" valign="top"><a id="ac7e613964435c0784650a1440e714b7a"></a>
QAction *&#160;</td><td class="memItemRight" valign="bottom"><b>_syncAct</b></td></tr>
<tr class="separator:ac7e613964435c0784650a1440e714b7a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa0d31f61b8c3da61cf1cc9dee8cd2961"><td class="memItemLeft" align="right" valign="top"><a id="aa0d31f61b8c3da61cf1cc9dee8cd2961"></a>
QMainWindow *&#160;</td><td class="memItemRight" valign="bottom"><b>_teamTab</b></td></tr>
<tr class="separator:aa0d31f61b8c3da61cf1cc9dee8cd2961"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a10117d7c167c147d48f70a6296e6df1a"><td class="memItemLeft" align="right" valign="top"><a id="a10117d7c167c147d48f70a6296e6df1a"></a>
QWidget *&#160;</td><td class="memItemRight" valign="bottom"><b>_teamCenter</b></td></tr>
<tr class="separator:a10117d7c167c147d48f70a6296e6df1a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5183b60f5b4e05ac10b45600bf94f963"><td class="memItemLeft" align="right" valign="top"><a id="a5183b60f5b4e05ac10b45600bf94f963"></a>
QVBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><b>_teamLay</b></td></tr>
<tr class="separator:a5183b60f5b4e05ac10b45600bf94f963"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a20c12be6d8fa26f9c21d751278559586"><td class="memItemLeft" align="right" valign="top"><a id="a20c12be6d8fa26f9c21d751278559586"></a>
QToolBar *&#160;</td><td class="memItemRight" valign="bottom"><b>_teamToolBar</b></td></tr>
<tr class="separator:a20c12be6d8fa26f9c21d751278559586"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab0ecb072ce22a42948e056aaadccc722"><td class="memItemLeft" align="right" valign="top"><a id="ab0ecb072ce22a42948e056aaadccc722"></a>
QTableWidget *&#160;</td><td class="memItemRight" valign="bottom"><b>_teamTable</b></td></tr>
<tr class="separator:ab0ecb072ce22a42948e056aaadccc722"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7d55533f3737f2335ec9cf96e62b85ef"><td class="memItemLeft" align="right" valign="top"><a id="a7d55533f3737f2335ec9cf96e62b85ef"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>selectedMember</b></td></tr>
<tr class="separator:a7d55533f3737f2335ec9cf96e62b85ef"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aba41ddd6ba254cdbcb07792d04364e81"><td class="memItemLeft" align="right" valign="top"><a id="aba41ddd6ba254cdbcb07792d04364e81"></a>
std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><b>teamMembers</b></td></tr>
<tr class="separator:aba41ddd6ba254cdbcb07792d04364e81"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad3e946281a4e18941715c55cc6dedba2"><td class="memItemLeft" align="right" valign="top"><a id="ad3e946281a4e18941715c55cc6dedba2"></a>
std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><b>selectedTeamMembers</b></td></tr>
<tr class="separator:ad3e946281a4e18941715c55cc6dedba2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a85a36afcb6c98fc556bf080ba380a74f"><td class="memItemLeft" align="right" valign="top"><a id="a85a36afcb6c98fc556bf080ba380a74f"></a>
bool&#160;</td><td class="memItemRight" valign="bottom"><b>_autoChange</b></td></tr>
<tr class="separator:a85a36afcb6c98fc556bf080ba380a74f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4bcec25200d3263b59d9fbf442a7daf0"><td class="memItemLeft" align="right" valign="top"><a id="a4bcec25200d3263b59d9fbf442a7daf0"></a>
QWidget *&#160;</td><td class="memItemRight" valign="bottom"><b>_planningTab</b></td></tr>
<tr class="separator:a4bcec25200d3263b59d9fbf442a7daf0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8cf9dfaf8e8f44dd2da3c912ec42bc1c"><td class="memItemLeft" align="right" valign="top"><a id="a8cf9dfaf8e8f44dd2da3c912ec42bc1c"></a>
QVBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><b>_planningLay</b></td></tr>
<tr class="separator:a8cf9dfaf8e8f44dd2da3c912ec42bc1c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a96ecd85e9f5a24073a878db40d80dfe0"><td class="memItemLeft" align="right" valign="top"><a id="a96ecd85e9f5a24073a878db40d80dfe0"></a>
<a class="el" href="../../d3/dd6/a00624.php">Planning</a>&#160;</td><td class="memItemRight" valign="bottom"><b>_planning</b></td></tr>
<tr class="separator:a96ecd85e9f5a24073a878db40d80dfe0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae21b928d41978e70e14a530b40d4412b"><td class="memItemLeft" align="right" valign="top"><a id="ae21b928d41978e70e14a530b40d4412b"></a>
<a class="el" href="../../d6/d75/a00604.php">Api</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>_api</b></td></tr>
<tr class="separator:ae21b928d41978e70e14a530b40d4412b"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="friends"></a>
Friends</h2></td></tr>
<tr class="memitem:a17791c185ba058b9c17f7e4f070cb09b"><td class="memItemLeft" align="right" valign="top"><a id="a17791c185ba058b9c17f7e4f070cb09b"></a>
bool&#160;</td><td class="memItemRight" valign="bottom"><b>operator==</b> (const <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &amp;a, const int &amp;b)</td></tr>
<tr class="separator:a17791c185ba058b9c17f7e4f070cb09b"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>The main window of the software. </p>
</div><hr/>The documentation for this class was generated from the following file:<ul>
<li>MainWindow.h</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../db/db5/a00616.php">MainWindow</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
