<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: Planning.h File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:22:26 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d5/d16/a00029.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a>  </div>
  <div class="headertitle">
<div class="title">Planning.h File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;Widgets/Qt.hpp&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Planning.h:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/d79/a00030.png" border="0" usemap="#Planning_8h" alt=""/></div>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../df/d61/a00031.png" border="0" usemap="#Planning_8hdep" alt=""/></div>
<map name="Planning_8hdep" id="Planning_8hdep">
<area shape="rect" id="node2" href="../../dd/dad/a00005.php" title="Api.hpp" alt="" coords="101,80,168,107"/>
<area shape="rect" id="node3" href="../../d2/de7/a00014.php" title="includes.h" alt="" coords="94,155,175,181"/>
<area shape="rect" id="node4" href="../../dc/d87/a00032.php" title="RegisterWidget.h" alt="" coords="73,229,196,256"/>
<area shape="rect" id="node5" href="../../d7/d46/a00002.php" title="AddMemberModal.h" alt="" coords="5,304,144,331"/>
<area shape="rect" id="node8" href="../../d4/d8c/a00035.php" title="SigninWindow.h" alt="" coords="146,379,262,405"/>
<area shape="rect" id="node6" href="../../d4/d51/a00017.php" title="MainWindow.h" alt="" coords="14,379,122,405"/>
<area shape="rect" id="node7" href="../../d4/dee/a00008.php" title="ConnectWindow.h" alt="" coords="71,453,201,480"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d4d/a00620.php">Pause</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d3/dd6/a00624.php">Planning</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_ed26a3555d00e4455851f1edbe2abea5.php">UQAC</a></li><li class="navelem"><a class="el" href="../../dir_72411d72a30b0a1d05f4f299c6dfb7e5.php">Cours2019-2020</a></li><li class="navelem"><a class="el" href="../../dir_3980970c724e97a7cae3ad342bc5e88e.php">Cours</a></li><li class="navelem"><a class="el" href="../../dir_de660acd428597c95c4dbb5b7e7040d2.php">T1_Genie_logiciel</a></li><li class="navelem"><a class="el" href="../../dir_2ed2da8857c2ea9b402c35adb582720e.php">Projet</a></li><li class="navelem"><a class="el" href="../../dir_a775c7fce4d0a7a4e13e85e05d64f23a.php">project_GL_uqac_automne2019</a></li><li class="navelem"><a class="el" href="../../dir_11f7a8fe58957f41539c5c2e1ae91c25.php">inc</a></li><li class="navelem"><a class="el" href="../../d5/d16/a00029.php">Planning.h</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
