<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: Api Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:25:59 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d6/d75/a00604.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-slots">Public Slots</a> &#124;
<a href="#signals">Signals</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-methods">Protected Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#pri-methods">Private Member Functions</a> &#124;
<a href="#pri-attribs">Private Attributes</a> &#124;
<a href="../../d6/db2/a00601.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">Api Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A class to talk with the remote apis.  
 <a href="../../d6/d75/a00604.php#details">More...</a></p>

<p><code>#include &lt;Api.hpp&gt;</code></p>
<div class="dynheader">
Inheritance diagram for Api:</div>
<div class="dyncontent">
<div class="center"><img src="../../de/d94/a00603.png" border="0" usemap="#Api_inherit__map" alt="Inheritance graph"/></div>
</div>
<div class="dynheader">
Collaboration diagram for Api:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/d0a/a00602.png" border="0" usemap="#Api_coll__map" alt="Collaboration graph"/></div>
<map name="Api_coll__map" id="Api_coll__map">
<area shape="rect" id="node4" title="STL class. " alt="" coords="175,160,255,237"/>
<area shape="rect" id="node5" title="STL class. " alt="" coords="152,5,279,97"/>
<area shape="rect" id="node6" title="STL class. " alt="" coords="354,160,477,237"/>
</map>
</div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-slots"></a>
Public Slots</h2></td></tr>
<tr class="memitem:a8690ac3b4f5e72aad8142f7d2bfd2695"><td class="memItemLeft" align="right" valign="top"><a id="a8690ac3b4f5e72aad8142f7d2bfd2695"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>getAll</b> ()</td></tr>
<tr class="separator:a8690ac3b4f5e72aad8142f7d2bfd2695"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac2b5e102425358d7d2eebac89d65e30a"><td class="memItemLeft" align="right" valign="top"><a id="ac2b5e102425358d7d2eebac89d65e30a"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>auth_end</b> (QNetworkReply *reply)</td></tr>
<tr class="separator:ac2b5e102425358d7d2eebac89d65e30a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a39c0094cc013eef8d512915bb1be0f91"><td class="memItemLeft" align="right" valign="top"><a id="a39c0094cc013eef8d512915bb1be0f91"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>register_end</b> (QNetworkReply *reply)</td></tr>
<tr class="separator:a39c0094cc013eef8d512915bb1be0f91"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3a194c206cbed4dd649ca925f74187c2"><td class="memItemLeft" align="right" valign="top"><a id="a3a194c206cbed4dd649ca925f74187c2"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>save_end</b> (QNetworkReply *reply)</td></tr>
<tr class="separator:a3a194c206cbed4dd649ca925f74187c2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a090232a9cc268f4b61c5c91b6f1c4b40"><td class="memItemLeft" align="right" valign="top"><a id="a090232a9cc268f4b61c5c91b6f1c4b40"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>saveMembers_end</b> (QNetworkReply *reply)</td></tr>
<tr class="separator:a090232a9cc268f4b61c5c91b6f1c4b40"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a38ddf54ba912805d223e8967979777d7"><td class="memItemLeft" align="right" valign="top"><a id="a38ddf54ba912805d223e8967979777d7"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>getAll_end</b> (QNetworkReply *reply)</td></tr>
<tr class="separator:a38ddf54ba912805d223e8967979777d7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a547d36bee82f736d43649dfec011e3d4"><td class="memItemLeft" align="right" valign="top"><a id="a547d36bee82f736d43649dfec011e3d4"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>compute_end</b> (QNetworkReply *reply)</td></tr>
<tr class="separator:a547d36bee82f736d43649dfec011e3d4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af1cf07b8f53877d07d56a4b537ba752e"><td class="memItemLeft" align="right" valign="top"><a id="af1cf07b8f53877d07d56a4b537ba752e"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>register_user_end</b> (QNetworkReply *reply)</td></tr>
<tr class="separator:af1cf07b8f53877d07d56a4b537ba752e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a84afd510ae92a5ebbb49843a5f54675f"><td class="memItemLeft" align="right" valign="top"><a id="a84afd510ae92a5ebbb49843a5f54675f"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>register_team_end</b> (QNetworkReply *reply)</td></tr>
<tr class="separator:a84afd510ae92a5ebbb49843a5f54675f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a15d21dee37cd82a72645a40e26d50941"><td class="memItemLeft" align="right" valign="top"><a id="a15d21dee37cd82a72645a40e26d50941"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>register_teammember_end</b> (QNetworkReply *reply)</td></tr>
<tr class="separator:a15d21dee37cd82a72645a40e26d50941"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7b1f827ec6102deb0b38e2f28089e1c1"><td class="memItemLeft" align="right" valign="top"><a id="a7b1f827ec6102deb0b38e2f28089e1c1"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>signin_user_end</b> (QNetworkReply *reply)</td></tr>
<tr class="separator:a7b1f827ec6102deb0b38e2f28089e1c1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2919e9666178e7ab5d8ff7a9425d3079"><td class="memItemLeft" align="right" valign="top"><a id="a2919e9666178e7ab5d8ff7a9425d3079"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>signin_teammember_end</b> (QNetworkReply *reply)</td></tr>
<tr class="separator:a2919e9666178e7ab5d8ff7a9425d3079"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="signals"></a>
Signals</h2></td></tr>
<tr class="memitem:a9bc95b70776528d7672b1ba5dc449546"><td class="memItemLeft" align="right" valign="top"><a id="a9bc95b70776528d7672b1ba5dc449546"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>auth_ended</b> ()</td></tr>
<tr class="separator:a9bc95b70776528d7672b1ba5dc449546"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0498d5c3a110596ad05c46dce4677fc7"><td class="memItemLeft" align="right" valign="top"><a id="a0498d5c3a110596ad05c46dce4677fc7"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>auth_error</b> ()</td></tr>
<tr class="separator:a0498d5c3a110596ad05c46dce4677fc7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab5c7c1aaad0d03fadc18252e24301380"><td class="memItemLeft" align="right" valign="top"><a id="ab5c7c1aaad0d03fadc18252e24301380"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>signin_ended</b> ()</td></tr>
<tr class="separator:ab5c7c1aaad0d03fadc18252e24301380"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3d35018066513c86a6dd65db10f8e74f"><td class="memItemLeft" align="right" valign="top"><a id="a3d35018066513c86a6dd65db10f8e74f"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>signin_error</b> ()</td></tr>
<tr class="separator:a3d35018066513c86a6dd65db10f8e74f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab1510b8b5126665a7ee0af2cb32f418c"><td class="memItemLeft" align="right" valign="top"><a id="ab1510b8b5126665a7ee0af2cb32f418c"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>signin_ended</b> (const std::string &amp;id)</td></tr>
<tr class="separator:ab1510b8b5126665a7ee0af2cb32f418c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a375db9cdee6f799187b416295ef7bba4"><td class="memItemLeft" align="right" valign="top"><a id="a375db9cdee6f799187b416295ef7bba4"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>signin_error</b> (const std::string &amp;id)</td></tr>
<tr class="separator:a375db9cdee6f799187b416295ef7bba4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2c818677d55b216d97357347cb7f31e8"><td class="memItemLeft" align="right" valign="top"><a id="a2c818677d55b216d97357347cb7f31e8"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>save_ended</b> ()</td></tr>
<tr class="separator:a2c818677d55b216d97357347cb7f31e8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab555274c529f2d7c42eb772f10ddf026"><td class="memItemLeft" align="right" valign="top"><a id="ab555274c529f2d7c42eb772f10ddf026"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>save_error</b> ()</td></tr>
<tr class="separator:ab555274c529f2d7c42eb772f10ddf026"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acf220a4d7cff209cc4c30f4703f3c1b7"><td class="memItemLeft" align="right" valign="top"><a id="acf220a4d7cff209cc4c30f4703f3c1b7"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>saveMembers_ended</b> ()</td></tr>
<tr class="separator:acf220a4d7cff209cc4c30f4703f3c1b7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac7809d993ef34286970ee0edfed30fd9"><td class="memItemLeft" align="right" valign="top"><a id="ac7809d993ef34286970ee0edfed30fd9"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>saveMembers_error</b> ()</td></tr>
<tr class="separator:ac7809d993ef34286970ee0edfed30fd9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4f7e78eeea139c6ba315568231646bcb"><td class="memItemLeft" align="right" valign="top"><a id="a4f7e78eeea139c6ba315568231646bcb"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>getAll_ended</b> ()</td></tr>
<tr class="separator:a4f7e78eeea139c6ba315568231646bcb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7ec193ec81e5e20955eaa43f1751807b"><td class="memItemLeft" align="right" valign="top"><a id="a7ec193ec81e5e20955eaa43f1751807b"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>getAll_ended</b> (const <a class="el" href="../../d0/d8d/a00612.php">Globals</a> &amp;globals, const std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt; &amp;teamMembers, const <a class="el" href="../../d3/dd6/a00624.php">Planning</a> &amp;planning)</td></tr>
<tr class="separator:a7ec193ec81e5e20955eaa43f1751807b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa74c11986db59a2ac20b3cad3f16d1b8"><td class="memItemLeft" align="right" valign="top"><a id="aa74c11986db59a2ac20b3cad3f16d1b8"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>getAll_error</b> ()</td></tr>
<tr class="separator:aa74c11986db59a2ac20b3cad3f16d1b8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3a433ef809a5c9ac0d42732883aa4828"><td class="memItemLeft" align="right" valign="top"><a id="a3a433ef809a5c9ac0d42732883aa4828"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>compute_ended</b> ()</td></tr>
<tr class="separator:a3a433ef809a5c9ac0d42732883aa4828"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aca64a03f4af7f8a6ebfdb72b3e22c83a"><td class="memItemLeft" align="right" valign="top"><a id="aca64a03f4af7f8a6ebfdb72b3e22c83a"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>compute_error</b> ()</td></tr>
<tr class="separator:aca64a03f4af7f8a6ebfdb72b3e22c83a"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a84682b994ff76304c01175d83bb62544"><td class="memItemLeft" align="right" valign="top"><a id="a84682b994ff76304c01175d83bb62544"></a>
&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d75/a00604.php#a84682b994ff76304c01175d83bb62544">Api</a> ()</td></tr>
<tr class="memdesc:a84682b994ff76304c01175d83bb62544"><td class="mdescLeft">&#160;</td><td class="mdescRight">The constructor of the class. <br /></td></tr>
<tr class="separator:a84682b994ff76304c01175d83bb62544"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8362fa295c1927e08e4844542327665e"><td class="memItemLeft" align="right" valign="top"><a id="a8362fa295c1927e08e4844542327665e"></a>
bool&#160;</td><td class="memItemRight" valign="bottom"><b>isChef</b> () const</td></tr>
<tr class="separator:a8362fa295c1927e08e4844542327665e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af71f3cf41e5994081e09e2aed5aa9917"><td class="memItemLeft" align="right" valign="top"><a id="af71f3cf41e5994081e09e2aed5aa9917"></a>
bool&#160;</td><td class="memItemRight" valign="bottom"><b>connection</b> (const std::string &amp;host)</td></tr>
<tr class="separator:af71f3cf41e5994081e09e2aed5aa9917"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adf98fcf11929460567d25f3c3ca046c7"><td class="memItemLeft" align="right" valign="top"><a id="adf98fcf11929460567d25f3c3ca046c7"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>auth</b> (const std::string &amp;user, const std::string &amp;pass)</td></tr>
<tr class="separator:adf98fcf11929460567d25f3c3ca046c7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4f521a9df68fb7d6df5693d1587bcc39"><td class="memItemLeft" align="right" valign="top"><a id="a4f521a9df68fb7d6df5693d1587bcc39"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>signin</b> (const <a class="el" href="../../dc/d25/a00596.php">AuthUser</a> &amp;user, const <a class="el" href="../../d1/d8c/a00600.php">AuthMember</a> &amp;member, const std::string &amp;teamName)</td></tr>
<tr class="separator:a4f521a9df68fb7d6df5693d1587bcc39"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a04d38baff9d072002663de5c612901da"><td class="memItemLeft" align="right" valign="top"><a id="a04d38baff9d072002663de5c612901da"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>signin</b> (const <a class="el" href="../../dc/d25/a00596.php">AuthUser</a> &amp;user, const <a class="el" href="../../d1/d8c/a00600.php">AuthMember</a> &amp;member)</td></tr>
<tr class="separator:a04d38baff9d072002663de5c612901da"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1b4676d1a5dd5537f9e380e51b2c3f68"><td class="memItemLeft" align="right" valign="top"><a id="a1b4676d1a5dd5537f9e380e51b2c3f68"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>save</b> (const <a class="el" href="../../d0/d8d/a00612.php">Globals</a> &amp;team, const <a class="el" href="../../d3/dd6/a00624.php">Planning</a> &amp;planning)</td></tr>
<tr class="separator:a1b4676d1a5dd5537f9e380e51b2c3f68"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aac006983648944a4b88969ebe29e43c6"><td class="memItemLeft" align="right" valign="top"><a id="aac006983648944a4b88969ebe29e43c6"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>saveMembers</b> (const std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt; &amp;team)</td></tr>
<tr class="separator:aac006983648944a4b88969ebe29e43c6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae351826f48dff2c62da2d4c5d73c4e78"><td class="memItemLeft" align="right" valign="top"><a id="ae351826f48dff2c62da2d4c5d73c4e78"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>deleteMember</b> (const std::string &amp;id)</td></tr>
<tr class="separator:ae351826f48dff2c62da2d4c5d73c4e78"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3005eb166846be59810e7cd077bfb1fc"><td class="memItemLeft" align="right" valign="top"><a id="a3005eb166846be59810e7cd077bfb1fc"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>compute</b> ()</td></tr>
<tr class="separator:a3005eb166846be59810e7cd077bfb1fc"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-methods"></a>
Protected Member Functions</h2></td></tr>
<tr class="memitem:ab2adb83a606e8c98a088700933164a2e"><td class="memItemLeft" align="right" valign="top"><a id="ab2adb83a606e8c98a088700933164a2e"></a>
std::string&#160;</td><td class="memItemRight" valign="bottom"><b>base64_encode</b> (const std::string &amp;str)</td></tr>
<tr class="separator:ab2adb83a606e8c98a088700933164a2e"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr class="memitem:acd5e259f4c3271f090310b5bf4b67e83"><td class="memItemLeft" align="right" valign="top"><a id="acd5e259f4c3271f090310b5bf4b67e83"></a>
std::map&lt; std::string, QNetworkAccessManager * &gt;&#160;</td><td class="memItemRight" valign="bottom"><b>_managers</b></td></tr>
<tr class="separator:acd5e259f4c3271f090310b5bf4b67e83"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3363125cf76e33f196a9932c0920b2f8"><td class="memItemLeft" align="right" valign="top"><a id="a3363125cf76e33f196a9932c0920b2f8"></a>
std::map&lt; std::string, std::string &gt;&#160;</td><td class="memItemRight" valign="bottom"><b>_urls</b></td></tr>
<tr class="separator:a3363125cf76e33f196a9932c0920b2f8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac8a878964a51f589adad565861a407a6"><td class="memItemLeft" align="right" valign="top"><a id="ac8a878964a51f589adad565861a407a6"></a>
std::string&#160;</td><td class="memItemRight" valign="bottom"><b>_host</b></td></tr>
<tr class="separator:ac8a878964a51f589adad565861a407a6"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pri-methods"></a>
Private Member Functions</h2></td></tr>
<tr class="memitem:a21f29472018eaf971b1ade85a0640f04"><td class="memItemLeft" align="right" valign="top"><a id="a21f29472018eaf971b1ade85a0640f04"></a>
std::string&#160;</td><td class="memItemRight" valign="bottom"><b>createUrl</b> (const std::string &amp;str)</td></tr>
<tr class="separator:a21f29472018eaf971b1ade85a0640f04"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a38c087486e77ddfc2ecc44db9d8abd69"><td class="memItemLeft" align="right" valign="top"><a id="a38c087486e77ddfc2ecc44db9d8abd69"></a>
QJsonObject&#160;</td><td class="memItemRight" valign="bottom"><b>jsonParse</b> (const std::string &amp;str)</td></tr>
<tr class="separator:a38c087486e77ddfc2ecc44db9d8abd69"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2c868892dc8fb593680ac4f24e4f09ca"><td class="memItemLeft" align="right" valign="top"><a id="a2c868892dc8fb593680ac4f24e4f09ca"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>printJsonError</b> (const QJsonObject &amp;json)</td></tr>
<tr class="separator:a2c868892dc8fb593680ac4f24e4f09ca"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a08dc74bcba157287880937b233927ecd"><td class="memItemLeft" align="right" valign="top"><a id="a08dc74bcba157287880937b233927ecd"></a>
QNetworkRequest&#160;</td><td class="memItemRight" valign="bottom"><b>createRequest</b> (const std::string &amp;url, const std::string &amp;managerName)</td></tr>
<tr class="separator:a08dc74bcba157287880937b233927ecd"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pri-attribs"></a>
Private Attributes</h2></td></tr>
<tr class="memitem:afaff93ac57381c8bf3fe0cc7abdf6975"><td class="memItemLeft" align="right" valign="top"><a id="afaff93ac57381c8bf3fe0cc7abdf6975"></a>
std::string&#160;</td><td class="memItemRight" valign="bottom"><b>_token</b></td></tr>
<tr class="separator:afaff93ac57381c8bf3fe0cc7abdf6975"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a468f2ba533071f4a57e78292d93a3455"><td class="memItemLeft" align="right" valign="top"><a id="a468f2ba533071f4a57e78292d93a3455"></a>
std::string&#160;</td><td class="memItemRight" valign="bottom"><b>_userid</b></td></tr>
<tr class="separator:a468f2ba533071f4a57e78292d93a3455"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad60fcde009ca596d97ef28f3c0f3a9e5"><td class="memItemLeft" align="right" valign="top"><a id="ad60fcde009ca596d97ef28f3c0f3a9e5"></a>
std::string&#160;</td><td class="memItemRight" valign="bottom"><b>_username</b></td></tr>
<tr class="separator:ad60fcde009ca596d97ef28f3c0f3a9e5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a63e9bdd96e19b4a1fba5e890e83b8216"><td class="memItemLeft" align="right" valign="top"><a id="a63e9bdd96e19b4a1fba5e890e83b8216"></a>
std::string&#160;</td><td class="memItemRight" valign="bottom"><b>_teamid</b></td></tr>
<tr class="separator:a63e9bdd96e19b4a1fba5e890e83b8216"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a46880b407cd4d199d9fb1c0c42930a17"><td class="memItemLeft" align="right" valign="top"><a id="a46880b407cd4d199d9fb1c0c42930a17"></a>
std::string&#160;</td><td class="memItemRight" valign="bottom"><b>_teammemberid</b></td></tr>
<tr class="separator:a46880b407cd4d199d9fb1c0c42930a17"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a76fd16d79629f8ff9bb8d8a486f1999e"><td class="memItemLeft" align="right" valign="top"><a id="a76fd16d79629f8ff9bb8d8a486f1999e"></a>
bool&#160;</td><td class="memItemRight" valign="bottom"><b>_chef</b></td></tr>
<tr class="separator:a76fd16d79629f8ff9bb8d8a486f1999e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a92d67445cf32ab345045579e4d305e54"><td class="memItemLeft" align="right" valign="top"><a id="a92d67445cf32ab345045579e4d305e54"></a>
bool&#160;</td><td class="memItemRight" valign="bottom"><b>_firstGet</b></td></tr>
<tr class="separator:a92d67445cf32ab345045579e4d305e54"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>A class to talk with the remote apis. </p>
</div><hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../dd/dad/a00005.php">Api.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../d6/d75/a00604.php">Api</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
