<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: MainWindow_TabTeam.h File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:22:26 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d6/d5b/a00026.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#define-members">Macros</a> &#124;
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">MainWindow_TabTeam.h File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../dc/d3c/a00028.png" border="0" usemap="#MainWindow__TabTeam_8hdep" alt=""/></div>
<map name="MainWindow__TabTeam_8hdep" id="MainWindow__TabTeam_8hdep">
<area shape="rect" id="node2" href="../../d4/d51/a00017.php" title="MainWindow.h" alt="" coords="37,80,145,107"/>
<area shape="rect" id="node3" href="../../d4/dee/a00008.php" title="ConnectWindow.h" alt="" coords="26,155,155,181"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="define-members"></a>
Macros</h2></td></tr>
<tr class="memitem:a2ea5ef263e8c1c96f63160e7cf251001"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a2ea5ef263e8c1c96f63160e7cf251001">HEADER_MAINWINDOW_TAB_TEAM</a></td></tr>
<tr class="separator:a2ea5ef263e8c1c96f63160e7cf251001"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:ae7ab818b3cc381ecb85d1e615b666561"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#ae7ab818b3cc381ecb85d1e615b666561">addMember</a> ()</td></tr>
<tr class="separator:ae7ab818b3cc381ecb85d1e615b666561"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a30bf81ecee8d3a43204382ce427f7b1d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#a30bf81ecee8d3a43204382ce427f7b1d">editMember</a> (QTableWidgetItem *item)</td></tr>
<tr class="separator:a30bf81ecee8d3a43204382ce427f7b1d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad8398c3fc4be4b0bd7bb7de1b5174ef6"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#ad8398c3fc4be4b0bd7bb7de1b5174ef6">deleteMember</a> ()</td></tr>
<tr class="separator:ad8398c3fc4be4b0bd7bb7de1b5174ef6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7725f630f2d01e501e0553ecd11a5be7"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#a7725f630f2d01e501e0553ecd11a5be7">updateSelectedMember</a> (int row, int)</td></tr>
<tr class="separator:a7725f630f2d01e501e0553ecd11a5be7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa318206e92a79096efaae315fb728b4b"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#aa318206e92a79096efaae315fb728b4b">t_setAll</a> (const <a class="el" href="../../d0/d8d/a00612.php">Globals</a> &amp;gl, const std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt; &amp;tm, const <a class="el" href="../../d3/dd6/a00624.php">Planning</a> &amp;pl)</td></tr>
<tr class="separator:aa318206e92a79096efaae315fb728b4b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac5b023c32c199f25f4efe6d1ec8d6c93"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#ac5b023c32c199f25f4efe6d1ec8d6c93">initTeamTab</a> (QTabWidget *tabWidget)</td></tr>
<tr class="separator:ac5b023c32c199f25f4efe6d1ec8d6c93"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a82d394cad2d5a54add778eb9d7f8d993"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#a82d394cad2d5a54add778eb9d7f8d993">resetTeamTab</a> (QTabWidget *tabWidget)</td></tr>
<tr class="separator:a82d394cad2d5a54add778eb9d7f8d993"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aef22df25ffd032061e24d57db73f9b86"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#aef22df25ffd032061e24d57db73f9b86">deleteTeamTab</a> (QTabWidget *tabWidget)</td></tr>
<tr class="separator:aef22df25ffd032061e24d57db73f9b86"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9e59be7499f3ebb6b0688c2919fbb71b"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#a9e59be7499f3ebb6b0688c2919fbb71b">initTeamTable</a> ()</td></tr>
<tr class="separator:a9e59be7499f3ebb6b0688c2919fbb71b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9f9085c2a83d79b38915412dbda81aa5"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#a9f9085c2a83d79b38915412dbda81aa5">operator==</a> (const <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &amp;a, const int &amp;b)</td></tr>
<tr class="separator:a9f9085c2a83d79b38915412dbda81aa5"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:a256022a1b3a0c865c991fcdb4a5c975b"><td class="memItemLeft" align="right" valign="top">QMainWindow *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#a256022a1b3a0c865c991fcdb4a5c975b">_teamTab</a></td></tr>
<tr class="separator:a256022a1b3a0c865c991fcdb4a5c975b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae952d8ceff24bbf1b56ab06dbd79e73d"><td class="memItemLeft" align="right" valign="top">QWidget *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#ae952d8ceff24bbf1b56ab06dbd79e73d">_teamCenter</a></td></tr>
<tr class="separator:ae952d8ceff24bbf1b56ab06dbd79e73d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa721ed9fbe17ba6dcfa32317a11fad57"><td class="memItemLeft" align="right" valign="top">QVBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#aa721ed9fbe17ba6dcfa32317a11fad57">_teamLay</a></td></tr>
<tr class="separator:aa721ed9fbe17ba6dcfa32317a11fad57"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af8e7a4be0f732bc4c2f39d6460b33581"><td class="memItemLeft" align="right" valign="top">QToolBar *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#af8e7a4be0f732bc4c2f39d6460b33581">_teamToolBar</a></td></tr>
<tr class="separator:af8e7a4be0f732bc4c2f39d6460b33581"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad2142a6c84ab21662e671a5bc353d318"><td class="memItemLeft" align="right" valign="top">QTableWidget *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#ad2142a6c84ab21662e671a5bc353d318">_teamTable</a></td></tr>
<tr class="separator:ad2142a6c84ab21662e671a5bc353d318"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae2a23de97c9c87913b35d0a30501794b"><td class="memItemLeft" align="right" valign="top">int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#ae2a23de97c9c87913b35d0a30501794b">selectedMember</a></td></tr>
<tr class="separator:ae2a23de97c9c87913b35d0a30501794b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afeab32130bac1eae8af1358ea3b56e4a"><td class="memItemLeft" align="right" valign="top">std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#afeab32130bac1eae8af1358ea3b56e4a">teamMembers</a></td></tr>
<tr class="separator:afeab32130bac1eae8af1358ea3b56e4a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad0e998f81aaa3860a1eeb1853910bf8c"><td class="memItemLeft" align="right" valign="top">std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#ad0e998f81aaa3860a1eeb1853910bf8c">selectedTeamMembers</a></td></tr>
<tr class="separator:ad0e998f81aaa3860a1eeb1853910bf8c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae5f055afb0001ff1df4e16826739f01e"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d5b/a00026.php#ae5f055afb0001ff1df4e16826739f01e">_autoChange</a></td></tr>
<tr class="separator:ae5f055afb0001ff1df4e16826739f01e"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Macro Definition Documentation</h2>
<a id="a2ea5ef263e8c1c96f63160e7cf251001"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a2ea5ef263e8c1c96f63160e7cf251001">&#9670;&nbsp;</a></span>HEADER_MAINWINDOW_TAB_TEAM</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define HEADER_MAINWINDOW_TAB_TEAM</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Function Documentation</h2>
<a id="ae7ab818b3cc381ecb85d1e615b666561"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae7ab818b3cc381ecb85d1e615b666561">&#9670;&nbsp;</a></span>addMember()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void addMember </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="ad8398c3fc4be4b0bd7bb7de1b5174ef6"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ad8398c3fc4be4b0bd7bb7de1b5174ef6">&#9670;&nbsp;</a></span>deleteMember()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void deleteMember </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d6/d5b/a00026_ad8398c3fc4be4b0bd7bb7de1b5174ef6_icgraph.png" border="0" usemap="#d6/d5b/a00026_ad8398c3fc4be4b0bd7bb7de1b5174ef6_icgraph" alt=""/></div>
<map name="d6/d5b/a00026_ad8398c3fc4be4b0bd7bb7de1b5174ef6_icgraph" id="d6/d5b/a00026_ad8398c3fc4be4b0bd7bb7de1b5174ef6_icgraph">
<area shape="rect" id="node2" href="../../d6/d75/a00604.php#a8362fa295c1927e08e4844542327665e" title="Api::isChef" alt="" coords="157,5,244,32"/>
</map>
</div>

</div>
</div>
<a id="aef22df25ffd032061e24d57db73f9b86"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aef22df25ffd032061e24d57db73f9b86">&#9670;&nbsp;</a></span>deleteTeamTab()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void deleteTeamTab </td>
          <td>(</td>
          <td class="paramtype">QTabWidget *&#160;</td>
          <td class="paramname"><em>tabWidget</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a30bf81ecee8d3a43204382ce427f7b1d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a30bf81ecee8d3a43204382ce427f7b1d">&#9670;&nbsp;</a></span>editMember()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void editMember </td>
          <td>(</td>
          <td class="paramtype">QTableWidgetItem *&#160;</td>
          <td class="paramname"><em>item</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="ac5b023c32c199f25f4efe6d1ec8d6c93"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac5b023c32c199f25f4efe6d1ec8d6c93">&#9670;&nbsp;</a></span>initTeamTab()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void initTeamTab </td>
          <td>(</td>
          <td class="paramtype">QTabWidget *&#160;</td>
          <td class="paramname"><em>tabWidget</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a9e59be7499f3ebb6b0688c2919fbb71b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9e59be7499f3ebb6b0688c2919fbb71b">&#9670;&nbsp;</a></span>initTeamTable()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void initTeamTable </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a9f9085c2a83d79b38915412dbda81aa5"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9f9085c2a83d79b38915412dbda81aa5">&#9670;&nbsp;</a></span>operator==()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">friend bool operator== </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &amp;&#160;</td>
          <td class="paramname"><em>a</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const int &amp;&#160;</td>
          <td class="paramname"><em>b</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a82d394cad2d5a54add778eb9d7f8d993"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a82d394cad2d5a54add778eb9d7f8d993">&#9670;&nbsp;</a></span>resetTeamTab()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void resetTeamTab </td>
          <td>(</td>
          <td class="paramtype">QTabWidget *&#160;</td>
          <td class="paramname"><em>tabWidget</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="aa318206e92a79096efaae315fb728b4b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa318206e92a79096efaae315fb728b4b">&#9670;&nbsp;</a></span>t_setAll()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void t_setAll </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="../../d0/d8d/a00612.php">Globals</a> &amp;&#160;</td>
          <td class="paramname"><em>gl</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt; &amp;&#160;</td>
          <td class="paramname"><em>tm</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="../../d3/dd6/a00624.php">Planning</a> &amp;&#160;</td>
          <td class="paramname"><em>pl</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a7725f630f2d01e501e0553ecd11a5be7"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7725f630f2d01e501e0553ecd11a5be7">&#9670;&nbsp;</a></span>updateSelectedMember()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void updateSelectedMember </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>row</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname">&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a id="ae5f055afb0001ff1df4e16826739f01e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae5f055afb0001ff1df4e16826739f01e">&#9670;&nbsp;</a></span>_autoChange</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">bool _autoChange</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ae952d8ceff24bbf1b56ab06dbd79e73d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae952d8ceff24bbf1b56ab06dbd79e73d">&#9670;&nbsp;</a></span>_teamCenter</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QWidget* _teamCenter</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="aa721ed9fbe17ba6dcfa32317a11fad57"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa721ed9fbe17ba6dcfa32317a11fad57">&#9670;&nbsp;</a></span>_teamLay</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QVBoxLayout* _teamLay</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a256022a1b3a0c865c991fcdb4a5c975b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a256022a1b3a0c865c991fcdb4a5c975b">&#9670;&nbsp;</a></span>_teamTab</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QMainWindow* _teamTab</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ad2142a6c84ab21662e671a5bc353d318"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ad2142a6c84ab21662e671a5bc353d318">&#9670;&nbsp;</a></span>_teamTable</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QTableWidget* _teamTable</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="af8e7a4be0f732bc4c2f39d6460b33581"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af8e7a4be0f732bc4c2f39d6460b33581">&#9670;&nbsp;</a></span>_teamToolBar</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QToolBar* _teamToolBar</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ae2a23de97c9c87913b35d0a30501794b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae2a23de97c9c87913b35d0a30501794b">&#9670;&nbsp;</a></span>selectedMember</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">int selectedMember</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ad0e998f81aaa3860a1eeb1853910bf8c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ad0e998f81aaa3860a1eeb1853910bf8c">&#9670;&nbsp;</a></span>selectedTeamMembers</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::vector&lt;<a class="el" href="../../db/ddc/a00636.php">TeamMember</a>&gt; selectedTeamMembers</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="afeab32130bac1eae8af1358ea3b56e4a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#afeab32130bac1eae8af1358ea3b56e4a">&#9670;&nbsp;</a></span>teamMembers</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::vector&lt;<a class="el" href="../../db/ddc/a00636.php">TeamMember</a>&gt; teamMembers</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_ed26a3555d00e4455851f1edbe2abea5.php">UQAC</a></li><li class="navelem"><a class="el" href="../../dir_72411d72a30b0a1d05f4f299c6dfb7e5.php">Cours2019-2020</a></li><li class="navelem"><a class="el" href="../../dir_3980970c724e97a7cae3ad342bc5e88e.php">Cours</a></li><li class="navelem"><a class="el" href="../../dir_de660acd428597c95c4dbb5b7e7040d2.php">T1_Genie_logiciel</a></li><li class="navelem"><a class="el" href="../../dir_2ed2da8857c2ea9b402c35adb582720e.php">Projet</a></li><li class="navelem"><a class="el" href="../../dir_a775c7fce4d0a7a4e13e85e05d64f23a.php">project_GL_uqac_automne2019</a></li><li class="navelem"><a class="el" href="../../dir_11f7a8fe58957f41539c5c2e1ae91c25.php">inc</a></li><li class="navelem"><a class="el" href="../../d6/d5b/a00026.php">MainWindow_TabTeam.h</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
