<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: TeamMember Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:04:17 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d5/d39/a00676.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#friends">Friends</a> &#124;
<a href="../../d4/d4f/a00673.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">TeamMember Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p><code>#include &lt;TeamMember.h&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a07d4c8d564474101fd4a649ec79781bc"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#a07d4c8d564474101fd4a649ec79781bc">TeamMember</a> (const std::string &amp;id, double nbHours, QString firstName, QString lastName, const std::vector&lt; QString &gt; &amp;daysOff)</td></tr>
<tr class="separator:a07d4c8d564474101fd4a649ec79781bc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7fb6f36a42f3f021ee5142dcf8506dda"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#a7fb6f36a42f3f021ee5142dcf8506dda">~TeamMember</a> ()</td></tr>
<tr class="separator:a7fb6f36a42f3f021ee5142dcf8506dda"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa10064f3eb18d2d13d2525880fa18244"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#aa10064f3eb18d2d13d2525880fa18244">getId</a> () const</td></tr>
<tr class="separator:aa10064f3eb18d2d13d2525880fa18244"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a128f69981966608a96ad6922954e4484"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#a128f69981966608a96ad6922954e4484">getNbHours</a> () const</td></tr>
<tr class="separator:a128f69981966608a96ad6922954e4484"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac4d6bc292c6afb71eebd53f16a94ae08"><td class="memItemLeft" align="right" valign="top">QString&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#ac4d6bc292c6afb71eebd53f16a94ae08">getFirstName</a> () const</td></tr>
<tr class="separator:ac4d6bc292c6afb71eebd53f16a94ae08"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a24581b40203c002d2cc0b450ddb355f9"><td class="memItemLeft" align="right" valign="top">QString&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#a24581b40203c002d2cc0b450ddb355f9">getLastName</a> () const</td></tr>
<tr class="separator:a24581b40203c002d2cc0b450ddb355f9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a02c204e1e33c7bf33f6548a2dba11245"><td class="memItemLeft" align="right" valign="top">std::vector&lt; QString &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#a02c204e1e33c7bf33f6548a2dba11245">getDaysOff</a> () const</td></tr>
<tr class="separator:a02c204e1e33c7bf33f6548a2dba11245"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7769a0f39258773bb9b0b9348e8c1023"><td class="memItemLeft" align="right" valign="top">QString&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#a7769a0f39258773bb9b0b9348e8c1023">daysOffToQString</a> ()</td></tr>
<tr class="separator:a7769a0f39258773bb9b0b9348e8c1023"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a86c4cdab5733790753d3ef79d376a303"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#a86c4cdab5733790753d3ef79d376a303">setId</a> (const std::string &amp;id)</td></tr>
<tr class="separator:a86c4cdab5733790753d3ef79d376a303"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa97881e8e23273d5ebfad4e9c397d235"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#aa97881e8e23273d5ebfad4e9c397d235">setNbHours</a> (double nbHours)</td></tr>
<tr class="separator:aa97881e8e23273d5ebfad4e9c397d235"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9981b2e29ca20e9bdb823b8681df0e78"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#a9981b2e29ca20e9bdb823b8681df0e78">setFirstName</a> (QString firstName)</td></tr>
<tr class="separator:a9981b2e29ca20e9bdb823b8681df0e78"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a984fc107fe6518391b2d6a81204b3875"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#a984fc107fe6518391b2d6a81204b3875">setLastName</a> (QString lastName)</td></tr>
<tr class="separator:a984fc107fe6518391b2d6a81204b3875"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7cef76489e5bd0fef1930ab423f7e380"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#a7cef76489e5bd0fef1930ab423f7e380">setDaysOff</a> (std::vector&lt; QString &gt; &amp;daysOff)</td></tr>
<tr class="separator:a7cef76489e5bd0fef1930ab423f7e380"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4ba484e70a61bd21e947d473156b8b73"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#a4ba484e70a61bd21e947d473156b8b73">setDaysOffFromQString</a> (QString daysOff)</td></tr>
<tr class="separator:a4ba484e70a61bd21e947d473156b8b73"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="friends"></a>
Friends</h2></td></tr>
<tr class="memitem:a81cb266afc04760039c97fce7d0c3a6d"><td class="memItemLeft" align="right" valign="top">std::ostream &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#a81cb266afc04760039c97fce7d0c3a6d">operator&lt;&lt;</a> (std::ostream &amp;os, const <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &amp;tm)</td></tr>
<tr class="separator:a81cb266afc04760039c97fce7d0c3a6d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afb691011abf3878ec7dd37376242e28a"><td class="memItemLeft" align="right" valign="top">std::ifstream &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#afb691011abf3878ec7dd37376242e28a">operator&gt;&gt;</a> (std::ifstream &amp;is, <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &amp;tm)</td></tr>
<tr class="separator:afb691011abf3878ec7dd37376242e28a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a53ed47b4e7b64395257d398b35afbec9"><td class="memItemLeft" align="right" valign="top">std::ofstream &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d39/a00676.php#a53ed47b4e7b64395257d398b35afbec9">operator&lt;&lt;</a> (std::ofstream &amp;os, const <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &amp;tm)</td></tr>
<tr class="separator:a53ed47b4e7b64395257d398b35afbec9"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a07d4c8d564474101fd4a649ec79781bc"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a07d4c8d564474101fd4a649ec79781bc">&#9670;&nbsp;</a></span>TeamMember()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">TeamMember::TeamMember </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>id</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>nbHours</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">QString&#160;</td>
          <td class="paramname"><em>firstName</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">QString&#160;</td>
          <td class="paramname"><em>lastName</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::vector&lt; QString &gt; &amp;&#160;</td>
          <td class="paramname"><em>daysOff</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a7fb6f36a42f3f021ee5142dcf8506dda"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7fb6f36a42f3f021ee5142dcf8506dda">&#9670;&nbsp;</a></span>~TeamMember()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">TeamMember::~TeamMember </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="a7769a0f39258773bb9b0b9348e8c1023"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7769a0f39258773bb9b0b9348e8c1023">&#9670;&nbsp;</a></span>daysOffToQString()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">QString TeamMember::daysOffToQString </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a02c204e1e33c7bf33f6548a2dba11245"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a02c204e1e33c7bf33f6548a2dba11245">&#9670;&nbsp;</a></span>getDaysOff()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::vector&lt;QString&gt; TeamMember::getDaysOff </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/d39/a00676_a02c204e1e33c7bf33f6548a2dba11245_cgraph.png" border="0" usemap="#d5/d39/a00676_a02c204e1e33c7bf33f6548a2dba11245_cgraph" alt=""/></div>
<map name="d5/d39/a00676_a02c204e1e33c7bf33f6548a2dba11245_cgraph" id="d5/d39/a00676_a02c204e1e33c7bf33f6548a2dba11245_cgraph">
<area shape="rect" id="node2" href="../../d5/d39/a00676.php#a7769a0f39258773bb9b0b9348e8c1023" title="TeamMember::daysOffToQString" alt="" coords="231,5,445,32"/>
</map>
</div>

</div>
</div>
<a id="ac4d6bc292c6afb71eebd53f16a94ae08"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac4d6bc292c6afb71eebd53f16a94ae08">&#9670;&nbsp;</a></span>getFirstName()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QString TeamMember::getFirstName </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="aa10064f3eb18d2d13d2525880fa18244"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa10064f3eb18d2d13d2525880fa18244">&#9670;&nbsp;</a></span>getId()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::string TeamMember::getId </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a24581b40203c002d2cc0b450ddb355f9"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a24581b40203c002d2cc0b450ddb355f9">&#9670;&nbsp;</a></span>getLastName()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QString TeamMember::getLastName </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a128f69981966608a96ad6922954e4484"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a128f69981966608a96ad6922954e4484">&#9670;&nbsp;</a></span>getNbHours()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">double TeamMember::getNbHours </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a7cef76489e5bd0fef1930ab423f7e380"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7cef76489e5bd0fef1930ab423f7e380">&#9670;&nbsp;</a></span>setDaysOff()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void TeamMember::setDaysOff </td>
          <td>(</td>
          <td class="paramtype">std::vector&lt; QString &gt; &amp;&#160;</td>
          <td class="paramname"><em>daysOff</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/d39/a00676_a7cef76489e5bd0fef1930ab423f7e380_cgraph.png" border="0" usemap="#d5/d39/a00676_a7cef76489e5bd0fef1930ab423f7e380_cgraph" alt=""/></div>
<map name="d5/d39/a00676_a7cef76489e5bd0fef1930ab423f7e380_cgraph" id="d5/d39/a00676_a7cef76489e5bd0fef1930ab423f7e380_cgraph">
<area shape="rect" id="node2" href="../../d5/d39/a00676.php#a4ba484e70a61bd21e947d473156b8b73" title="TeamMember::setDaysOffFrom\lQString" alt="" coords="231,5,437,47"/>
</map>
</div>

</div>
</div>
<a id="a4ba484e70a61bd21e947d473156b8b73"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a4ba484e70a61bd21e947d473156b8b73">&#9670;&nbsp;</a></span>setDaysOffFromQString()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void TeamMember::setDaysOffFromQString </td>
          <td>(</td>
          <td class="paramtype">QString&#160;</td>
          <td class="paramname"><em>daysOff</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a9981b2e29ca20e9bdb823b8681df0e78"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9981b2e29ca20e9bdb823b8681df0e78">&#9670;&nbsp;</a></span>setFirstName()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void TeamMember::setFirstName </td>
          <td>(</td>
          <td class="paramtype">QString&#160;</td>
          <td class="paramname"><em>firstName</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a86c4cdab5733790753d3ef79d376a303"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a86c4cdab5733790753d3ef79d376a303">&#9670;&nbsp;</a></span>setId()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void TeamMember::setId </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a984fc107fe6518391b2d6a81204b3875"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a984fc107fe6518391b2d6a81204b3875">&#9670;&nbsp;</a></span>setLastName()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void TeamMember::setLastName </td>
          <td>(</td>
          <td class="paramtype">QString&#160;</td>
          <td class="paramname"><em>lastName</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="aa97881e8e23273d5ebfad4e9c397d235"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa97881e8e23273d5ebfad4e9c397d235">&#9670;&nbsp;</a></span>setNbHours()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void TeamMember::setNbHours </td>
          <td>(</td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>nbHours</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Friends And Related Function Documentation</h2>
<a id="a81cb266afc04760039c97fce7d0c3a6d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a81cb266afc04760039c97fce7d0c3a6d">&#9670;&nbsp;</a></span>operator<< <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::ostream&amp; operator&lt;&lt; </td>
          <td>(</td>
          <td class="paramtype">std::ostream &amp;&#160;</td>
          <td class="paramname"><em>os</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &amp;&#160;</td>
          <td class="paramname"><em>tm</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">friend</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a53ed47b4e7b64395257d398b35afbec9"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a53ed47b4e7b64395257d398b35afbec9">&#9670;&nbsp;</a></span>operator<< <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::ofstream&amp; operator&lt;&lt; </td>
          <td>(</td>
          <td class="paramtype">std::ofstream &amp;&#160;</td>
          <td class="paramname"><em>os</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &amp;&#160;</td>
          <td class="paramname"><em>tm</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">friend</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="afb691011abf3878ec7dd37376242e28a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#afb691011abf3878ec7dd37376242e28a">&#9670;&nbsp;</a></span>operator>></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::ifstream&amp; operator&gt;&gt; </td>
          <td>(</td>
          <td class="paramtype">std::ifstream &amp;&#160;</td>
          <td class="paramname"><em>is</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &amp;&#160;</td>
          <td class="paramname"><em>tm</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">friend</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d3/d8b/a00059.php">TeamMember.h</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
