<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: Member List</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:04:17 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('dc/d62/a00640.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Api Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="../../dc/d62/a00640.php">Api</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#ac8a878964a51f589adad565861a407a6">_host</a></td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#acd5e259f4c3271f090310b5bf4b67e83">_managers</a></td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a3363125cf76e33f196a9932c0920b2f8">_urls</a></td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a84682b994ff76304c01175d83bb62544">Api</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#adf98fcf11929460567d25f3c3ca046c7">auth</a>(const std::string &amp;user, const std::string &amp;pass)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#ac2b5e102425358d7d2eebac89d65e30a">auth_end</a>(QNetworkReply *reply)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a9bc95b70776528d7672b1ba5dc449546">auth_ended</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a0498d5c3a110596ad05c46dce4677fc7">auth_error</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#ab2adb83a606e8c98a088700933164a2e">base64_encode</a>(const std::string &amp;str)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a3005eb166846be59810e7cd077bfb1fc">compute</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a547d36bee82f736d43649dfec011e3d4">compute_end</a>(QNetworkReply *reply)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a3a433ef809a5c9ac0d42732883aa4828">compute_ended</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#aca64a03f4af7f8a6ebfdb72b3e22c83a">compute_error</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#af71f3cf41e5994081e09e2aed5aa9917">connection</a>(const std::string &amp;host)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#ae351826f48dff2c62da2d4c5d73c4e78">deleteMember</a>(const std::string &amp;id)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a8690ac3b4f5e72aad8142f7d2bfd2695">getAll</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a38ddf54ba912805d223e8967979777d7">getAll_end</a>(QNetworkReply *reply)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a4f7e78eeea139c6ba315568231646bcb">getAll_ended</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a7ec193ec81e5e20955eaa43f1751807b">getAll_ended</a>(const Globals &amp;globals, const std::vector&lt; TeamMember &gt; &amp;teamMembers, const Planning &amp;planning)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#aa74c11986db59a2ac20b3cad3f16d1b8">getAll_error</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a8362fa295c1927e08e4844542327665e">isChef</a>() const</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a39c0094cc013eef8d512915bb1be0f91">register_end</a>(QNetworkReply *reply)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a84afd510ae92a5ebbb49843a5f54675f">register_team_end</a>(QNetworkReply *reply)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a15d21dee37cd82a72645a40e26d50941">register_teammember_end</a>(QNetworkReply *reply)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#af1cf07b8f53877d07d56a4b537ba752e">register_user_end</a>(QNetworkReply *reply)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a1b4676d1a5dd5537f9e380e51b2c3f68">save</a>(const Globals &amp;team, const Planning &amp;planning)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a3a194c206cbed4dd649ca925f74187c2">save_end</a>(QNetworkReply *reply)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a2c818677d55b216d97357347cb7f31e8">save_ended</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#ab555274c529f2d7c42eb772f10ddf026">save_error</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#aac006983648944a4b88969ebe29e43c6">saveMembers</a>(const std::vector&lt; TeamMember &gt; &amp;team)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a090232a9cc268f4b61c5c91b6f1c4b40">saveMembers_end</a>(QNetworkReply *reply)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#acf220a4d7cff209cc4c30f4703f3c1b7">saveMembers_ended</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#ac7809d993ef34286970ee0edfed30fd9">saveMembers_error</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a4f521a9df68fb7d6df5693d1587bcc39">signin</a>(const AuthUser &amp;user, const AuthMember &amp;member, const std::string &amp;teamName)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a04d38baff9d072002663de5c612901da">signin</a>(const AuthUser &amp;user, const AuthMember &amp;member)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#ab5c7c1aaad0d03fadc18252e24301380">signin_ended</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#ab1510b8b5126665a7ee0af2cb32f418c">signin_ended</a>(const std::string &amp;id)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a3d35018066513c86a6dd65db10f8e74f">signin_error</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a375db9cdee6f799187b416295ef7bba4">signin_error</a>(const std::string &amp;id)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a2919e9666178e7ab5d8ff7a9425d3079">signin_teammember_end</a>(QNetworkReply *reply)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a7b1f827ec6102deb0b38e2f28089e1c1">signin_user_end</a>(QNetworkReply *reply)</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/d62/a00640.php#a3e0643b013bb9daab48b823673c308cc">~Api</a>()</td><td class="entry"><a class="el" href="../../dc/d62/a00640.php">Api</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
</table></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
