<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: RegisterWidget Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:04:17 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d0/d5c/a00668.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-slots">Public Slots</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-attribs">Public Attributes</a> &#124;
<a href="../../da/d46/a00665.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">RegisterWidget Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>The main window of the software.  
 <a href="../../d0/d5c/a00668.php#details">More...</a></p>

<p><code>#include &lt;RegisterWidget.h&gt;</code></p>
<div class="dynheader">
Inheritance diagram for RegisterWidget:</div>
<div class="dyncontent">
<div class="center"><img src="../../d2/d6e/a00667.png" border="0" usemap="#RegisterWidget_inherit__map" alt="Inheritance graph"/></div>
<map name="RegisterWidget_inherit__map" id="RegisterWidget_inherit__map">
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for RegisterWidget:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/d41/a00666.png" border="0" usemap="#RegisterWidget_coll__map" alt="Collaboration graph"/></div>
<map name="RegisterWidget_coll__map" id="RegisterWidget_coll__map">
<area shape="rect" id="node4" title="STL class. " alt="" coords="67,109,147,136"/>
<area shape="rect" id="node5" title="STL class. " alt="" coords="44,5,171,47"/>
<area shape="rect" id="node6" title="STL class. " alt="" coords="171,109,294,136"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-slots"></a>
Public Slots</h2></td></tr>
<tr class="memitem:adc0b4a0a0877a77fcf6e4b0f8292da6c"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d5c/a00668.php#adc0b4a0a0877a77fcf6e4b0f8292da6c">generalAllCheckstate</a> (int state)</td></tr>
<tr class="separator:adc0b4a0a0877a77fcf6e4b0f8292da6c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a7807ba4d5048e2b3134dda99cd4c19f3"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d5c/a00668.php#a7807ba4d5048e2b3134dda99cd4c19f3">RegisterWidget</a> (bool passless=false, QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:a7807ba4d5048e2b3134dda99cd4c19f3"><td class="mdescLeft">&#160;</td><td class="mdescRight">The constructor of the class.  <a href="#a7807ba4d5048e2b3134dda99cd4c19f3">More...</a><br /></td></tr>
<tr class="separator:a7807ba4d5048e2b3134dda99cd4c19f3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a855064ea03e9d6dd7c3ec7d2cde04a13"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d5c/a00668.php#a855064ea03e9d6dd7c3ec7d2cde04a13">~RegisterWidget</a> ()</td></tr>
<tr class="separator:a855064ea03e9d6dd7c3ec7d2cde04a13"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab995ac919d7fbca08fcbfbba4172e0e7"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d5c/a00668.php#ab995ac919d7fbca08fcbfbba4172e0e7">getDaysOff</a> () const</td></tr>
<tr class="separator:ab995ac919d7fbca08fcbfbba4172e0e7"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-attribs"></a>
Public Attributes</h2></td></tr>
<tr class="memitem:a74237be10533acff46f14589b3568ade"><td class="memItemLeft" align="right" valign="top">QLineEdit *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d5c/a00668.php#a74237be10533acff46f14589b3568ade">_username</a></td></tr>
<tr class="separator:a74237be10533acff46f14589b3568ade"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aff0471897ece6bb0c08ea2a4e5e035e6"><td class="memItemLeft" align="right" valign="top">QLineEdit *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d5c/a00668.php#aff0471897ece6bb0c08ea2a4e5e035e6">_password</a></td></tr>
<tr class="separator:aff0471897ece6bb0c08ea2a4e5e035e6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5c1cf1097d44adec4ab1edc689609e08"><td class="memItemLeft" align="right" valign="top">QLineEdit *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d5c/a00668.php#a5c1cf1097d44adec4ab1edc689609e08">_passwordConf</a></td></tr>
<tr class="separator:a5c1cf1097d44adec4ab1edc689609e08"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af743f98c0d1088e3955c11f7ecca8ad8"><td class="memItemLeft" align="right" valign="top">QCheckBox *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d5c/a00668.php#af743f98c0d1088e3955c11f7ecca8ad8">_checkAll</a></td></tr>
<tr class="separator:af743f98c0d1088e3955c11f7ecca8ad8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae3439ba0a314e23e82a9a136a4163f84"><td class="memItemLeft" align="right" valign="top">QLineEdit *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d5c/a00668.php#ae3439ba0a314e23e82a9a136a4163f84">_firstName</a></td></tr>
<tr class="separator:ae3439ba0a314e23e82a9a136a4163f84"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a42ef8b4599d867b0d7ad08c8362d696d"><td class="memItemLeft" align="right" valign="top">QLineEdit *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d5c/a00668.php#a42ef8b4599d867b0d7ad08c8362d696d">_lastName</a></td></tr>
<tr class="separator:a42ef8b4599d867b0d7ad08c8362d696d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abfaaa76d8f2a3eb77fbe47c88135031e"><td class="memItemLeft" align="right" valign="top">QDoubleSpinBox *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d5c/a00668.php#abfaaa76d8f2a3eb77fbe47c88135031e">_hoursPerWeek</a></td></tr>
<tr class="separator:abfaaa76d8f2a3eb77fbe47c88135031e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac586ce09560b4282faf3adbd26aeba3c"><td class="memItemLeft" align="right" valign="top">std::map&lt; std::string, QCheckBox * &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d5c/a00668.php#ac586ce09560b4282faf3adbd26aeba3c">_t_daysCheckboxes</a></td></tr>
<tr class="separator:ac586ce09560b4282faf3adbd26aeba3c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>The main window of the software. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a7807ba4d5048e2b3134dda99cd4c19f3"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7807ba4d5048e2b3134dda99cd4c19f3">&#9670;&nbsp;</a></span>RegisterWidget()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">RegisterWidget::RegisterWidget </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>passless</em> = <code>false</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>parent</em> = <code>nullptr</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>The constructor of the class. </p>

</div>
</div>
<a id="a855064ea03e9d6dd7c3ec7d2cde04a13"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a855064ea03e9d6dd7c3ec7d2cde04a13">&#9670;&nbsp;</a></span>~RegisterWidget()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual RegisterWidget::~RegisterWidget </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="adc0b4a0a0877a77fcf6e4b0f8292da6c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#adc0b4a0a0877a77fcf6e4b0f8292da6c">&#9670;&nbsp;</a></span>generalAllCheckstate</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void RegisterWidget::generalAllCheckstate </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>state</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ab995ac919d7fbca08fcbfbba4172e0e7"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab995ac919d7fbca08fcbfbba4172e0e7">&#9670;&nbsp;</a></span>getDaysOff()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string RegisterWidget::getDaysOff </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a id="af743f98c0d1088e3955c11f7ecca8ad8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af743f98c0d1088e3955c11f7ecca8ad8">&#9670;&nbsp;</a></span>_checkAll</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">QCheckBox* RegisterWidget::_checkAll</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="ae3439ba0a314e23e82a9a136a4163f84"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae3439ba0a314e23e82a9a136a4163f84">&#9670;&nbsp;</a></span>_firstName</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">QLineEdit* RegisterWidget::_firstName</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="abfaaa76d8f2a3eb77fbe47c88135031e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#abfaaa76d8f2a3eb77fbe47c88135031e">&#9670;&nbsp;</a></span>_hoursPerWeek</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">QDoubleSpinBox* RegisterWidget::_hoursPerWeek</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a42ef8b4599d867b0d7ad08c8362d696d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a42ef8b4599d867b0d7ad08c8362d696d">&#9670;&nbsp;</a></span>_lastName</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">QLineEdit* RegisterWidget::_lastName</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="aff0471897ece6bb0c08ea2a4e5e035e6"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aff0471897ece6bb0c08ea2a4e5e035e6">&#9670;&nbsp;</a></span>_password</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">QLineEdit* RegisterWidget::_password</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a5c1cf1097d44adec4ab1edc689609e08"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a5c1cf1097d44adec4ab1edc689609e08">&#9670;&nbsp;</a></span>_passwordConf</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">QLineEdit* RegisterWidget::_passwordConf</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="ac586ce09560b4282faf3adbd26aeba3c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac586ce09560b4282faf3adbd26aeba3c">&#9670;&nbsp;</a></span>_t_daysCheckboxes</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::map&lt;std::string, QCheckBox*&gt; RegisterWidget::_t_daysCheckboxes</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a74237be10533acff46f14589b3568ade"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a74237be10533acff46f14589b3568ade">&#9670;&nbsp;</a></span>_username</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">QLineEdit* RegisterWidget::_username</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../dc/dee/a00053.php">RegisterWidget.h</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../d0/d5c/a00668.php">RegisterWidget</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
