<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: TeamMember Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:25:59 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('db/ddc/a00636.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pri-attribs">Private Attributes</a> &#124;
<a href="#friends">Friends</a> &#124;
<a href="../../d9/d1d/a00633.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">TeamMember Class Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="dynheader">
Collaboration diagram for TeamMember:</div>
<div class="dyncontent">
<div class="center"><img src="../../d7/de4/a00634.png" border="0" usemap="#TeamMember_coll__map" alt="Collaboration graph"/></div>
<map name="TeamMember_coll__map" id="TeamMember_coll__map">
<area shape="rect" id="node3" title="STL class. " alt="" coords="21,153,137,230"/>
<area shape="rect" id="node5" title="STL class. " alt="" coords="184,300,264,377"/>
<area shape="rect" id="node6" title="STL class. " alt="" coords="161,145,287,237"/>
</map>
</div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a07d4c8d564474101fd4a649ec79781bc"><td class="memItemLeft" align="right" valign="top"><a id="a07d4c8d564474101fd4a649ec79781bc"></a>
&#160;</td><td class="memItemRight" valign="bottom"><b>TeamMember</b> (const std::string &amp;id, double nbHours, QString firstName, QString lastName, const std::vector&lt; QString &gt; &amp;daysOff)</td></tr>
<tr class="separator:a07d4c8d564474101fd4a649ec79781bc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa10064f3eb18d2d13d2525880fa18244"><td class="memItemLeft" align="right" valign="top"><a id="aa10064f3eb18d2d13d2525880fa18244"></a>
std::string&#160;</td><td class="memItemRight" valign="bottom"><b>getId</b> () const</td></tr>
<tr class="separator:aa10064f3eb18d2d13d2525880fa18244"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a128f69981966608a96ad6922954e4484"><td class="memItemLeft" align="right" valign="top"><a id="a128f69981966608a96ad6922954e4484"></a>
double&#160;</td><td class="memItemRight" valign="bottom"><b>getNbHours</b> () const</td></tr>
<tr class="separator:a128f69981966608a96ad6922954e4484"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac4d6bc292c6afb71eebd53f16a94ae08"><td class="memItemLeft" align="right" valign="top"><a id="ac4d6bc292c6afb71eebd53f16a94ae08"></a>
QString&#160;</td><td class="memItemRight" valign="bottom"><b>getFirstName</b> () const</td></tr>
<tr class="separator:ac4d6bc292c6afb71eebd53f16a94ae08"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a24581b40203c002d2cc0b450ddb355f9"><td class="memItemLeft" align="right" valign="top"><a id="a24581b40203c002d2cc0b450ddb355f9"></a>
QString&#160;</td><td class="memItemRight" valign="bottom"><b>getLastName</b> () const</td></tr>
<tr class="separator:a24581b40203c002d2cc0b450ddb355f9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a02c204e1e33c7bf33f6548a2dba11245"><td class="memItemLeft" align="right" valign="top"><a id="a02c204e1e33c7bf33f6548a2dba11245"></a>
std::vector&lt; QString &gt;&#160;</td><td class="memItemRight" valign="bottom"><b>getDaysOff</b> () const</td></tr>
<tr class="separator:a02c204e1e33c7bf33f6548a2dba11245"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7769a0f39258773bb9b0b9348e8c1023"><td class="memItemLeft" align="right" valign="top"><a id="a7769a0f39258773bb9b0b9348e8c1023"></a>
QString&#160;</td><td class="memItemRight" valign="bottom"><b>daysOffToQString</b> ()</td></tr>
<tr class="separator:a7769a0f39258773bb9b0b9348e8c1023"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a86c4cdab5733790753d3ef79d376a303"><td class="memItemLeft" align="right" valign="top"><a id="a86c4cdab5733790753d3ef79d376a303"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>setId</b> (const std::string &amp;id)</td></tr>
<tr class="separator:a86c4cdab5733790753d3ef79d376a303"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa97881e8e23273d5ebfad4e9c397d235"><td class="memItemLeft" align="right" valign="top"><a id="aa97881e8e23273d5ebfad4e9c397d235"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>setNbHours</b> (double nbHours)</td></tr>
<tr class="separator:aa97881e8e23273d5ebfad4e9c397d235"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9981b2e29ca20e9bdb823b8681df0e78"><td class="memItemLeft" align="right" valign="top"><a id="a9981b2e29ca20e9bdb823b8681df0e78"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>setFirstName</b> (QString firstName)</td></tr>
<tr class="separator:a9981b2e29ca20e9bdb823b8681df0e78"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a984fc107fe6518391b2d6a81204b3875"><td class="memItemLeft" align="right" valign="top"><a id="a984fc107fe6518391b2d6a81204b3875"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>setLastName</b> (QString lastName)</td></tr>
<tr class="separator:a984fc107fe6518391b2d6a81204b3875"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7cef76489e5bd0fef1930ab423f7e380"><td class="memItemLeft" align="right" valign="top"><a id="a7cef76489e5bd0fef1930ab423f7e380"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>setDaysOff</b> (std::vector&lt; QString &gt; &amp;daysOff)</td></tr>
<tr class="separator:a7cef76489e5bd0fef1930ab423f7e380"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4ba484e70a61bd21e947d473156b8b73"><td class="memItemLeft" align="right" valign="top"><a id="a4ba484e70a61bd21e947d473156b8b73"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>setDaysOffFromQString</b> (QString daysOff)</td></tr>
<tr class="separator:a4ba484e70a61bd21e947d473156b8b73"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pri-attribs"></a>
Private Attributes</h2></td></tr>
<tr class="memitem:a9ee0ee9816c842a4979692db4e7e4422"><td class="memItemLeft" align="right" valign="top"><a id="a9ee0ee9816c842a4979692db4e7e4422"></a>
std::string&#160;</td><td class="memItemRight" valign="bottom"><b>_id</b></td></tr>
<tr class="separator:a9ee0ee9816c842a4979692db4e7e4422"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aabad9f4729689ff0b9a3daf91bbc898a"><td class="memItemLeft" align="right" valign="top"><a id="aabad9f4729689ff0b9a3daf91bbc898a"></a>
double&#160;</td><td class="memItemRight" valign="bottom"><b>_nbHours</b></td></tr>
<tr class="separator:aabad9f4729689ff0b9a3daf91bbc898a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a428a8ed576625ee8c9da4a16985fab54"><td class="memItemLeft" align="right" valign="top"><a id="a428a8ed576625ee8c9da4a16985fab54"></a>
QString&#160;</td><td class="memItemRight" valign="bottom"><b>_firstName</b></td></tr>
<tr class="separator:a428a8ed576625ee8c9da4a16985fab54"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a06b44f3e3044c03f76ce8f7a7aa938e2"><td class="memItemLeft" align="right" valign="top"><a id="a06b44f3e3044c03f76ce8f7a7aa938e2"></a>
QString&#160;</td><td class="memItemRight" valign="bottom"><b>_lastName</b></td></tr>
<tr class="separator:a06b44f3e3044c03f76ce8f7a7aa938e2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaef7d63febe37ecec56fa06abad1a2c6"><td class="memItemLeft" align="right" valign="top"><a id="aaef7d63febe37ecec56fa06abad1a2c6"></a>
std::vector&lt; QString &gt;&#160;</td><td class="memItemRight" valign="bottom"><b>_daysOff</b></td></tr>
<tr class="separator:aaef7d63febe37ecec56fa06abad1a2c6"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="friends"></a>
Friends</h2></td></tr>
<tr class="memitem:a81cb266afc04760039c97fce7d0c3a6d"><td class="memItemLeft" align="right" valign="top"><a id="a81cb266afc04760039c97fce7d0c3a6d"></a>
std::ostream &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>operator&lt;&lt;</b> (std::ostream &amp;os, const <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &amp;tm)</td></tr>
<tr class="separator:a81cb266afc04760039c97fce7d0c3a6d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afb691011abf3878ec7dd37376242e28a"><td class="memItemLeft" align="right" valign="top"><a id="afb691011abf3878ec7dd37376242e28a"></a>
std::ifstream &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>operator&gt;&gt;</b> (std::ifstream &amp;is, <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &amp;tm)</td></tr>
<tr class="separator:afb691011abf3878ec7dd37376242e28a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a53ed47b4e7b64395257d398b35afbec9"><td class="memItemLeft" align="right" valign="top"><a id="a53ed47b4e7b64395257d398b35afbec9"></a>
std::ofstream &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>operator&lt;&lt;</b> (std::ofstream &amp;os, const <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &amp;tm)</td></tr>
<tr class="separator:a53ed47b4e7b64395257d398b35afbec9"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>TeamMember.h</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../db/ddc/a00636.php">TeamMember</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
