<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: Globals Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:04:17 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('df/d37/a00652.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-attribs">Public Attributes</a> &#124;
<a href="../../dd/d6b/a00649.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">Globals Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p><code>#include &lt;Globals.h&gt;</code></p>
<div class="dynheader">
Collaboration diagram for Globals:</div>
<div class="dyncontent">
<div class="center"><img src="../../da/d36/a00650.png" border="0" usemap="#Globals_coll__map" alt="Collaboration graph"/></div>
<map name="Globals_coll__map" id="Globals_coll__map">
<area shape="rect" id="node3" title="STL class. " alt="" coords="29,109,109,136"/>
<area shape="rect" id="node4" title="STL class. " alt="" coords="5,5,132,47"/>
<area shape="rect" id="node5" title="STL class. " alt="" coords="133,109,249,136"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a3b78cfdbe2809ad8b6b722969dda4425"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d37/a00652.php#a3b78cfdbe2809ad8b6b722969dda4425">Globals</a> ()</td></tr>
<tr class="separator:a3b78cfdbe2809ad8b6b722969dda4425"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acfea831928c2e3195d9c880955ff54d5"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d37/a00652.php#acfea831928c2e3195d9c880955ff54d5">Globals</a> (float start, float end, float hours, const std::vector&lt; std::string &gt; &amp;days)</td></tr>
<tr class="separator:acfea831928c2e3195d9c880955ff54d5"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-attribs"></a>
Public Attributes</h2></td></tr>
<tr class="memitem:a580b0c6e1a15d88437107964687f1e6d"><td class="memItemLeft" align="right" valign="top">float&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d37/a00652.php#a580b0c6e1a15d88437107964687f1e6d">startMin</a></td></tr>
<tr class="separator:a580b0c6e1a15d88437107964687f1e6d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9deb9168f76d51325db506b7f4c466e8"><td class="memItemLeft" align="right" valign="top">float&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d37/a00652.php#a9deb9168f76d51325db506b7f4c466e8">endMax</a></td></tr>
<tr class="separator:a9deb9168f76d51325db506b7f4c466e8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae151bc2f232e7996921d2885e37acbe0"><td class="memItemLeft" align="right" valign="top">float&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d37/a00652.php#ae151bc2f232e7996921d2885e37acbe0">nbHours</a></td></tr>
<tr class="separator:ae151bc2f232e7996921d2885e37acbe0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acb5d931277c8126668a043dfe4da4ce5"><td class="memItemLeft" align="right" valign="top">std::vector&lt; std::string &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d37/a00652.php#acb5d931277c8126668a043dfe4da4ce5">workedDays</a></td></tr>
<tr class="separator:acb5d931277c8126668a043dfe4da4ce5"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a3b78cfdbe2809ad8b6b722969dda4425"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3b78cfdbe2809ad8b6b722969dda4425">&#9670;&nbsp;</a></span>Globals() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">Globals::Globals </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="acfea831928c2e3195d9c880955ff54d5"></a>
<h2 class="memtitle"><span class="permalink"><a href="#acfea831928c2e3195d9c880955ff54d5">&#9670;&nbsp;</a></span>Globals() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">Globals::Globals </td>
          <td>(</td>
          <td class="paramtype">float&#160;</td>
          <td class="paramname"><em>start</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">float&#160;</td>
          <td class="paramname"><em>end</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">float&#160;</td>
          <td class="paramname"><em>hours</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::vector&lt; std::string &gt; &amp;&#160;</td>
          <td class="paramname"><em>days</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a id="a9deb9168f76d51325db506b7f4c466e8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9deb9168f76d51325db506b7f4c466e8">&#9670;&nbsp;</a></span>endMax</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">float Globals::endMax</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="ae151bc2f232e7996921d2885e37acbe0"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae151bc2f232e7996921d2885e37acbe0">&#9670;&nbsp;</a></span>nbHours</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">float Globals::nbHours</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a580b0c6e1a15d88437107964687f1e6d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a580b0c6e1a15d88437107964687f1e6d">&#9670;&nbsp;</a></span>startMin</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">float Globals::startMin</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="acb5d931277c8126668a043dfe4da4ce5"></a>
<h2 class="memtitle"><span class="permalink"><a href="#acb5d931277c8126668a043dfe4da4ce5">&#9670;&nbsp;</a></span>workedDays</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::vector&lt;std::string&gt; Globals::workedDays</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../dc/d87/a00032.php">Globals.h</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../df/d37/a00652.php">Globals</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
