<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: Qt.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:04:17 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('df/d03/a00062.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Qt.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../de/de1/a00065.php">QtDefines.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Qt.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d6f/a00063.png" border="0" usemap="#Qt_8hpp" alt=""/></div>
<map name="Qt_8hpp" id="Qt_8hpp">
<area shape="rect" id="node2" href="../../de/de1/a00065.php" title="QtDefines.hpp" alt="" coords="15,80,122,107"/>
<area shape="rect" id="node4" href="../../db/db6/a00074.php" title="Spacers.hpp" alt="" coords="21,155,116,181"/>
<area shape="rect" id="node5" href="../../d0/d89/a00071.php" title="QtFunctions.hpp" alt="" coords="140,155,258,181"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../df/d5f/a00064.png" border="0" usemap="#Qt_8hppdep" alt=""/></div>
<map name="Qt_8hppdep" id="Qt_8hppdep">
<area shape="rect" id="node2" href="../../d4/d8c/a00035.php" title="includes.h" alt="" coords="112,229,193,256"/>
<area shape="rect" id="node8" href="../../dc/d87/a00032.php" title="Globals.h" alt="" coords="21,80,98,107"/>
<area shape="rect" id="node10" href="../../d5/de0/a00050.php" title="Planning.h" alt="" coords="261,80,343,107"/>
<area shape="rect" id="node11" href="../../d3/d8b/a00059.php" title="TeamMember.h" alt="" coords="123,80,236,107"/>
<area shape="rect" id="node3" href="../../dc/dee/a00053.php" title="RegisterWidget.h" alt="" coords="83,304,206,331"/>
<area shape="rect" id="node5" href="../../d8/d41/a00038.php" title="MainWindow.h" alt="" coords="177,453,285,480"/>
<area shape="rect" id="node4" href="../../d7/d46/a00002.php" title="AddMemberModal.h" alt="" coords="75,379,214,405"/>
<area shape="rect" id="node7" href="../../d9/d2e/a00056.php" title="SigninWindow.h" alt="" coords="19,453,135,480"/>
<area shape="rect" id="node6" href="../../d5/d16/a00029.php" title="ConnectWindow.h" alt="" coords="80,528,209,555"/>
<area shape="rect" id="node9" href="../../dd/dad/a00005.php" title="Api.hpp" alt="" coords="137,155,203,181"/>
</map>
</div>
</div><a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>08 juin 2018 </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_ed26a3555d00e4455851f1edbe2abea5.php">UQAC</a></li><li class="navelem"><a class="el" href="../../dir_72411d72a30b0a1d05f4f299c6dfb7e5.php">Cours2019-2020</a></li><li class="navelem"><a class="el" href="../../dir_3980970c724e97a7cae3ad342bc5e88e.php">Cours</a></li><li class="navelem"><a class="el" href="../../dir_de660acd428597c95c4dbb5b7e7040d2.php">T1_Genie_logiciel</a></li><li class="navelem"><a class="el" href="../../dir_2ed2da8857c2ea9b402c35adb582720e.php">Projet</a></li><li class="navelem"><a class="el" href="../../dir_a775c7fce4d0a7a4e13e85e05d64f23a.php">project_GL_uqac_automne2019</a></li><li class="navelem"><a class="el" href="../../dir_11f7a8fe58957f41539c5c2e1ae91c25.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_78a63cdfa5ba1108a1c6943bc3305158.php">Widgets</a></li><li class="navelem"><a class="el" href="../../df/d03/a00062.php">Qt.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
