<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: SigninWindow Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:04:17 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d5/d40/a00672.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-slots">Public Slots</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-methods">Protected Member Functions</a> &#124;
<a href="../../d8/d7a/a00669.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">SigninWindow Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>The main window of the software.  
 <a href="../../d5/d40/a00672.php#details">More...</a></p>

<p><code>#include &lt;SigninWindow.h&gt;</code></p>
<div class="dynheader">
Inheritance diagram for SigninWindow:</div>
<div class="dyncontent">
<div class="center"><img src="../../d8/d13/a00671.png" border="0" usemap="#SigninWindow_inherit__map" alt="Inheritance graph"/></div>
<map name="SigninWindow_inherit__map" id="SigninWindow_inherit__map">
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for SigninWindow:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d97/a00670.png" border="0" usemap="#SigninWindow_coll__map" alt="Collaboration graph"/></div>
<map name="SigninWindow_coll__map" id="SigninWindow_coll__map">
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-slots"></a>
Public Slots</h2></td></tr>
<tr class="memitem:a8606463f143a72c48e91ea047a4c0e14"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d40/a00672.php#a8606463f143a72c48e91ea047a4c0e14">signingin</a> ()</td></tr>
<tr class="separator:a8606463f143a72c48e91ea047a4c0e14"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a93a18832275298b8825c76c165161363"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d40/a00672.php#a93a18832275298b8825c76c165161363">connection</a> ()</td></tr>
<tr class="separator:a93a18832275298b8825c76c165161363"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1b123d82f9403a25bf8742657ded6e0d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d40/a00672.php#a1b123d82f9403a25bf8742657ded6e0d">goThrough</a> ()</td></tr>
<tr class="separator:a1b123d82f9403a25bf8742657ded6e0d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a14a8720f2c2b8cae2c59dd901888535b"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d40/a00672.php#a14a8720f2c2b8cae2c59dd901888535b">reenableLinks</a> ()</td></tr>
<tr class="separator:a14a8720f2c2b8cae2c59dd901888535b"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a97ffb6811b80312f4e6b18ff52ae2a80"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d40/a00672.php#a97ffb6811b80312f4e6b18ff52ae2a80">SigninWindow</a> (QMainWindow *connectWindow, <a class="el" href="../../dc/d62/a00640.php">Api</a> &amp;api, QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:a97ffb6811b80312f4e6b18ff52ae2a80"><td class="mdescLeft">&#160;</td><td class="mdescRight">The constructor of the class.  <a href="#a97ffb6811b80312f4e6b18ff52ae2a80">More...</a><br /></td></tr>
<tr class="separator:a97ffb6811b80312f4e6b18ff52ae2a80"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2f4dfec2068ee16a88199cddde63713e"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d40/a00672.php#a2f4dfec2068ee16a88199cddde63713e">~SigninWindow</a> ()</td></tr>
<tr class="separator:a2f4dfec2068ee16a88199cddde63713e"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-methods"></a>
Protected Member Functions</h2></td></tr>
<tr class="memitem:abef53069c7523b41bde25b7061e50748"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d40/a00672.php#abef53069c7523b41bde25b7061e50748">showEvent</a> (QShowEvent *event)</td></tr>
<tr class="separator:abef53069c7523b41bde25b7061e50748"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>The main window of the software. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a97ffb6811b80312f4e6b18ff52ae2a80"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a97ffb6811b80312f4e6b18ff52ae2a80">&#9670;&nbsp;</a></span>SigninWindow()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">SigninWindow::SigninWindow </td>
          <td>(</td>
          <td class="paramtype">QMainWindow *&#160;</td>
          <td class="paramname"><em>connectWindow</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="../../dc/d62/a00640.php">Api</a> &amp;&#160;</td>
          <td class="paramname"><em>api</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>parent</em> = <code>nullptr</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>The constructor of the class. </p>

</div>
</div>
<a id="a2f4dfec2068ee16a88199cddde63713e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a2f4dfec2068ee16a88199cddde63713e">&#9670;&nbsp;</a></span>~SigninWindow()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual SigninWindow::~SigninWindow </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="a93a18832275298b8825c76c165161363"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a93a18832275298b8825c76c165161363">&#9670;&nbsp;</a></span>connection</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void SigninWindow::connection </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a1b123d82f9403a25bf8742657ded6e0d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a1b123d82f9403a25bf8742657ded6e0d">&#9670;&nbsp;</a></span>goThrough</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void SigninWindow::goThrough </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a14a8720f2c2b8cae2c59dd901888535b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a14a8720f2c2b8cae2c59dd901888535b">&#9670;&nbsp;</a></span>reenableLinks</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void SigninWindow::reenableLinks </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="abef53069c7523b41bde25b7061e50748"></a>
<h2 class="memtitle"><span class="permalink"><a href="#abef53069c7523b41bde25b7061e50748">&#9670;&nbsp;</a></span>showEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void SigninWindow::showEvent </td>
          <td>(</td>
          <td class="paramtype">QShowEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a8606463f143a72c48e91ea047a4c0e14"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a8606463f143a72c48e91ea047a4c0e14">&#9670;&nbsp;</a></span>signingin</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void SigninWindow::signingin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d9/d2e/a00056.php">SigninWindow.h</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../d5/d40/a00672.php">SigninWindow</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
