<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: ConnectWindow Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:04:17 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('dd/d1f/a00648.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-slots">Public Slots</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-methods">Protected Member Functions</a> &#124;
<a href="../../d6/dcf/a00645.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">ConnectWindow Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>The main window of the software.  
 <a href="../../dd/d1f/a00648.php#details">More...</a></p>

<p><code>#include &lt;ConnectWindow.h&gt;</code></p>
<div class="dynheader">
Inheritance diagram for ConnectWindow:</div>
<div class="dyncontent">
<div class="center"><img src="../../d3/d8e/a00647.png" border="0" usemap="#ConnectWindow_inherit__map" alt="Inheritance graph"/></div>
<map name="ConnectWindow_inherit__map" id="ConnectWindow_inherit__map">
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for ConnectWindow:</div>
<div class="dyncontent">
<div class="center"><img src="../../d6/d08/a00646.png" border="0" usemap="#ConnectWindow_coll__map" alt="Collaboration graph"/></div>
<map name="ConnectWindow_coll__map" id="ConnectWindow_coll__map">
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-slots"></a>
Public Slots</h2></td></tr>
<tr class="memitem:a97ae82d5a82f16be9ef49190831cd627"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1f/a00648.php#a97ae82d5a82f16be9ef49190831cd627">connection</a> ()</td></tr>
<tr class="separator:a97ae82d5a82f16be9ef49190831cd627"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a30f9e20da21170b6fb4483631b8c2004"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1f/a00648.php#a30f9e20da21170b6fb4483631b8c2004">signingin</a> ()</td></tr>
<tr class="separator:a30f9e20da21170b6fb4483631b8c2004"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa7a256669919cd96e7762c92152779d5"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1f/a00648.php#aa7a256669919cd96e7762c92152779d5">goThrough</a> ()</td></tr>
<tr class="separator:aa7a256669919cd96e7762c92152779d5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9dfb8513eee377da498948fd808b08bf"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1f/a00648.php#a9dfb8513eee377da498948fd808b08bf">reenableLinks</a> ()</td></tr>
<tr class="separator:a9dfb8513eee377da498948fd808b08bf"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a922461f8248d2f68f992f391559e944b"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1f/a00648.php#a922461f8248d2f68f992f391559e944b">ConnectWindow</a> (<a class="el" href="../../dc/df2/a00656.php">MainWindow</a> &amp;mainWind, <a class="el" href="../../dc/d62/a00640.php">Api</a> &amp;api, QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:a922461f8248d2f68f992f391559e944b"><td class="mdescLeft">&#160;</td><td class="mdescRight">The constructor of the class.  <a href="#a922461f8248d2f68f992f391559e944b">More...</a><br /></td></tr>
<tr class="separator:a922461f8248d2f68f992f391559e944b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a244b52b960e461d8c679b455a1c503c2"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1f/a00648.php#a244b52b960e461d8c679b455a1c503c2">~ConnectWindow</a> ()</td></tr>
<tr class="separator:a244b52b960e461d8c679b455a1c503c2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af84126e3453f6a29353686cdaf3c3d52"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1f/a00648.php#af84126e3453f6a29353686cdaf3c3d52">link</a> (<a class="el" href="../../d5/d40/a00672.php">SigninWindow</a> *wind)</td></tr>
<tr class="separator:af84126e3453f6a29353686cdaf3c3d52"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a628c37f83de053fb7d68ee55dfbe24ec"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1f/a00648.php#a628c37f83de053fb7d68ee55dfbe24ec">testConnect</a> (const std::string &amp;user, const std::string &amp;pass)</td></tr>
<tr class="separator:a628c37f83de053fb7d68ee55dfbe24ec"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4241ce4be37f44d35e624bef31446ec9"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1f/a00648.php#a4241ce4be37f44d35e624bef31446ec9">testRegister</a> ()</td></tr>
<tr class="separator:a4241ce4be37f44d35e624bef31446ec9"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-methods"></a>
Protected Member Functions</h2></td></tr>
<tr class="memitem:a0f5ef34d29f827d44330accba2e81e86"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1f/a00648.php#a0f5ef34d29f827d44330accba2e81e86">showEvent</a> (QShowEvent *event)</td></tr>
<tr class="separator:a0f5ef34d29f827d44330accba2e81e86"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>The main window of the software. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a922461f8248d2f68f992f391559e944b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a922461f8248d2f68f992f391559e944b">&#9670;&nbsp;</a></span>ConnectWindow()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">ConnectWindow::ConnectWindow </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a> &amp;&#160;</td>
          <td class="paramname"><em>mainWind</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="../../dc/d62/a00640.php">Api</a> &amp;&#160;</td>
          <td class="paramname"><em>api</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>parent</em> = <code>nullptr</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>The constructor of the class. </p>

</div>
</div>
<a id="a244b52b960e461d8c679b455a1c503c2"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a244b52b960e461d8c679b455a1c503c2">&#9670;&nbsp;</a></span>~ConnectWindow()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual ConnectWindow::~ConnectWindow </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="a97ae82d5a82f16be9ef49190831cd627"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a97ae82d5a82f16be9ef49190831cd627">&#9670;&nbsp;</a></span>connection</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void ConnectWindow::connection </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="aa7a256669919cd96e7762c92152779d5"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa7a256669919cd96e7762c92152779d5">&#9670;&nbsp;</a></span>goThrough</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void ConnectWindow::goThrough </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="af84126e3453f6a29353686cdaf3c3d52"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af84126e3453f6a29353686cdaf3c3d52">&#9670;&nbsp;</a></span>link()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void ConnectWindow::link </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../d5/d40/a00672.php">SigninWindow</a> *&#160;</td>
          <td class="paramname"><em>wind</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../dd/d1f/a00648_af84126e3453f6a29353686cdaf3c3d52_cgraph.png" border="0" usemap="#dd/d1f/a00648_af84126e3453f6a29353686cdaf3c3d52_cgraph" alt=""/></div>
<map name="dd/d1f/a00648_af84126e3453f6a29353686cdaf3c3d52_cgraph" id="dd/d1f/a00648_af84126e3453f6a29353686cdaf3c3d52_cgraph">
<area shape="rect" id="node2" href="../../dd/d1f/a00648.php#a628c37f83de053fb7d68ee55dfbe24ec" title="ConnectWindow::testConnect" alt="" coords="213,5,410,32"/>
<area shape="rect" id="node3" href="../../dd/d1f/a00648.php#a4241ce4be37f44d35e624bef31446ec9" title="ConnectWindow::testRegister" alt="" coords="213,56,410,83"/>
<area shape="rect" id="node4" href="../../dd/d1f/a00648.php#a97ae82d5a82f16be9ef49190831cd627" title="ConnectWindow::connection" alt="" coords="217,107,406,133"/>
<area shape="rect" id="node5" href="../../dd/d1f/a00648.php#a30f9e20da21170b6fb4483631b8c2004" title="ConnectWindow::signingin" alt="" coords="223,157,400,184"/>
<area shape="rect" id="node6" href="../../dd/d1f/a00648.php#aa7a256669919cd96e7762c92152779d5" title="ConnectWindow::goThrough" alt="" coords="218,208,405,235"/>
<area shape="rect" id="node7" href="../../dd/d1f/a00648.php#a9dfb8513eee377da498948fd808b08bf" title="ConnectWindow::reenableLinks" alt="" coords="208,259,415,285"/>
<area shape="rect" id="node8" href="../../dd/d1f/a00648.php#a0f5ef34d29f827d44330accba2e81e86" title="ConnectWindow::showEvent" alt="" coords="216,309,407,336"/>
<area shape="rect" id="node9" href="../../dd/d1f/a00648.php#a922461f8248d2f68f992f391559e944b" title="The constructor of the class. " alt="" coords="200,360,423,387"/>
</map>
</div>

</div>
</div>
<a id="a9dfb8513eee377da498948fd808b08bf"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9dfb8513eee377da498948fd808b08bf">&#9670;&nbsp;</a></span>reenableLinks</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void ConnectWindow::reenableLinks </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a0f5ef34d29f827d44330accba2e81e86"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0f5ef34d29f827d44330accba2e81e86">&#9670;&nbsp;</a></span>showEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void ConnectWindow::showEvent </td>
          <td>(</td>
          <td class="paramtype">QShowEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a30f9e20da21170b6fb4483631b8c2004"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a30f9e20da21170b6fb4483631b8c2004">&#9670;&nbsp;</a></span>signingin</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void ConnectWindow::signingin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a628c37f83de053fb7d68ee55dfbe24ec"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a628c37f83de053fb7d68ee55dfbe24ec">&#9670;&nbsp;</a></span>testConnect()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void ConnectWindow::testConnect </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>user</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>pass</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a4241ce4be37f44d35e624bef31446ec9"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a4241ce4be37f44d35e624bef31446ec9">&#9670;&nbsp;</a></span>testRegister()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void ConnectWindow::testRegister </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d5/d16/a00029.php">ConnectWindow.h</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dd/d1f/a00648.php">ConnectWindow</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
