<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: AddMemberModal Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:25:59 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d0/dec/a00592.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-slots">Public Slots</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pri-methods">Private Member Functions</a> &#124;
<a href="#pri-attribs">Private Attributes</a> &#124;
<a href="../../d6/da3/a00589.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">AddMemberModal Class Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="dynheader">
Inheritance diagram for AddMemberModal:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/dad/a00591.png" border="0" usemap="#AddMemberModal_inherit__map" alt="Inheritance graph"/></div>
</div>
<div class="dynheader">
Collaboration diagram for AddMemberModal:</div>
<div class="dyncontent">
<div class="center"><img src="../../d7/db1/a00590.png" border="0" usemap="#AddMemberModal_coll__map" alt="Collaboration graph"/></div>
<map name="AddMemberModal_coll__map" id="AddMemberModal_coll__map">
<area shape="rect" id="node3" href="../../d1/d51/a00628.php" title="The main window of the software. " alt="" coords="151,917,317,1200"/>
<area shape="rect" id="node6" title="STL class. " alt="" coords="659,300,739,377"/>
<area shape="rect" id="node11" href="../../d6/d75/a00604.php" title="A class to talk with the remote apis. " alt="" coords="481,815,677,1303"/>
<area shape="rect" id="node18" href="../../db/ddc/a00636.php" title="{TeamMember\n|&#45; _nbHours\l&#45; _firstName\l&#45; _lastName\l|+ TeamMember()\l+ ~TeamMember()\l+ getId()\l+ getNbHours()\l+ getFirstName()\l+ getLastName()\l+ getDaysOff()\l+ daysOffToQString()\l+ setId()\l+ setNbHours()\l+ setFirstName()\l+ setLastName()\l+ setDaysOff()\l+ setDaysOffFromQString()\l}" alt="" coords="957,455,1140,752"/>
<area shape="rect" id="node7" title="STL class. " alt="" coords="636,145,763,237"/>
<area shape="rect" id="node8" title="STL class. " alt="" coords="214,300,337,377"/>
<area shape="rect" id="node16" title="STL class. " alt="" coords="861,153,977,230"/>
</map>
</div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:a2be2c83a4066d0742719bdaa46a58893"><td class="memItemLeft" align="right" valign="top"><a id="a2be2c83a4066d0742719bdaa46a58893"></a>enum &#160;</td><td class="memItemRight" valign="bottom"><b>Columns</b> { <br />
&#160;&#160;<b>ID</b>, 
<b>FIRSTNAME</b>, 
<b>LASTNAME</b>, 
<b>NBHOURS</b>, 
<br />
&#160;&#160;<b>DAYSOFF</b>
<br />
 }</td></tr>
<tr class="separator:a2be2c83a4066d0742719bdaa46a58893"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-slots"></a>
Public Slots</h2></td></tr>
<tr class="memitem:aed08d238ec70f374ad1f86747b8f3255"><td class="memItemLeft" align="right" valign="top"><a id="aed08d238ec70f374ad1f86747b8f3255"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>addNewMember</b> ()</td></tr>
<tr class="separator:aed08d238ec70f374ad1f86747b8f3255"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af3d6bfdcc0c1a43aa464af0ac75a39ab"><td class="memItemLeft" align="right" valign="top"><a id="af3d6bfdcc0c1a43aa464af0ac75a39ab"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>addingNewMember</b> (const std::string &amp;id)</td></tr>
<tr class="separator:af3d6bfdcc0c1a43aa464af0ac75a39ab"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a16b21bcc0ca18fb06e94df990bcd71dd"><td class="memItemLeft" align="right" valign="top"><a id="a16b21bcc0ca18fb06e94df990bcd71dd"></a>
&#160;</td><td class="memItemRight" valign="bottom"><b>AddMemberModal</b> (QWidget *parent, std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt; &amp;teamMembers, QTableWidget &amp;teamTable, <a class="el" href="../../d6/d75/a00604.php">Api</a> &amp;api)</td></tr>
<tr class="separator:a16b21bcc0ca18fb06e94df990bcd71dd"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pri-methods"></a>
Private Member Functions</h2></td></tr>
<tr class="memitem:aaa7a8550cc0ce2763c3852cd5727c5a6"><td class="memItemLeft" align="right" valign="top"><a id="aaa7a8550cc0ce2763c3852cd5727c5a6"></a>
&#160;</td><td class="memItemRight" valign="bottom"><b>AddMemberModal</b> (const <a class="el" href="../../d0/dec/a00592.php">AddMemberModal</a> &amp;other)</td></tr>
<tr class="separator:aaa7a8550cc0ce2763c3852cd5727c5a6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6afe4437c496168602d67ce3b5be409d"><td class="memItemLeft" align="right" valign="top"><a id="a6afe4437c496168602d67ce3b5be409d"></a>
<a class="el" href="../../d0/dec/a00592.php">AddMemberModal</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>operator=</b> (const <a class="el" href="../../d0/dec/a00592.php">AddMemberModal</a> &amp;other)</td></tr>
<tr class="separator:a6afe4437c496168602d67ce3b5be409d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aed5503def033fcb8df83c15e454c4619"><td class="memItemLeft" align="right" valign="top"><a id="aed5503def033fcb8df83c15e454c4619"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>init</b> (const <a class="el" href="../../d0/dec/a00592.php">AddMemberModal</a> *other=nullptr)</td></tr>
<tr class="separator:aed5503def033fcb8df83c15e454c4619"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4eca2627779fbbc887842fd4d17d5d10"><td class="memItemLeft" align="right" valign="top"><a id="a4eca2627779fbbc887842fd4d17d5d10"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>initWindow</b> ()</td></tr>
<tr class="separator:a4eca2627779fbbc887842fd4d17d5d10"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pri-attribs"></a>
Private Attributes</h2></td></tr>
<tr class="memitem:aa818f39ab8ce3a90e7275c04265196cf"><td class="memItemLeft" align="right" valign="top"><a id="aa818f39ab8ce3a90e7275c04265196cf"></a>
<a class="el" href="../../d1/d51/a00628.php">RegisterWidget</a> *&#160;</td><td class="memItemRight" valign="bottom"><b>_register</b></td></tr>
<tr class="separator:aa818f39ab8ce3a90e7275c04265196cf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acf127048a8c1cf4e6ceb3b18ca3ada10"><td class="memItemLeft" align="right" valign="top"><a id="acf127048a8c1cf4e6ceb3b18ca3ada10"></a>
QPushButton *&#160;</td><td class="memItemRight" valign="bottom"><b>_confirmButton</b></td></tr>
<tr class="separator:acf127048a8c1cf4e6ceb3b18ca3ada10"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a21708e1de2d3b42402323f7b7170a91e"><td class="memItemLeft" align="right" valign="top"><a id="a21708e1de2d3b42402323f7b7170a91e"></a>
std::vector&lt; QString &gt;&#160;</td><td class="memItemRight" valign="bottom"><b>_daysOff</b></td></tr>
<tr class="separator:a21708e1de2d3b42402323f7b7170a91e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5761807b959efa8db63854af4434c900"><td class="memItemLeft" align="right" valign="top"><a id="a5761807b959efa8db63854af4434c900"></a>
std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt; &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>_teamMembers</b></td></tr>
<tr class="separator:a5761807b959efa8db63854af4434c900"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae8050e27d792a4d4043691a10a739392"><td class="memItemLeft" align="right" valign="top"><a id="ae8050e27d792a4d4043691a10a739392"></a>
QTableWidget &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>_teamTable</b></td></tr>
<tr class="separator:ae8050e27d792a4d4043691a10a739392"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acb002f8ff2cbcb542bbe6294dc0be8f3"><td class="memItemLeft" align="right" valign="top"><a id="acb002f8ff2cbcb542bbe6294dc0be8f3"></a>
<a class="el" href="../../d6/d75/a00604.php">Api</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>_api</b></td></tr>
<tr class="separator:acb002f8ff2cbcb542bbe6294dc0be8f3"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>AddMemberModal.h</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../d0/dec/a00592.php">AddMemberModal</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
