<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: SigninWindow Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:25:59 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d4/d2a/a00632.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-slots">Public Slots</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-methods">Protected Member Functions</a> &#124;
<a href="#pri-methods">Private Member Functions</a> &#124;
<a href="#pri-attribs">Private Attributes</a> &#124;
<a href="../../da/dd1/a00629.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">SigninWindow Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>The main window of the software.  
 <a href="../../d4/d2a/a00632.php#details">More...</a></p>

<p><code>#include &lt;SigninWindow.h&gt;</code></p>
<div class="dynheader">
Inheritance diagram for SigninWindow:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/de3/a00631.png" border="0" usemap="#SigninWindow_inherit__map" alt="Inheritance graph"/></div>
</div>
<div class="dynheader">
Collaboration diagram for SigninWindow:</div>
<div class="dyncontent">
<div class="center"><img src="../../dc/d66/a00630.png" border="0" usemap="#SigninWindow_coll__map" alt="Collaboration graph"/></div>
<map name="SigninWindow_coll__map" id="SigninWindow_coll__map">
<area shape="rect" id="node3" href="../../d1/d51/a00628.php" title="The main window of the software. " alt="" coords="147,572,314,855"/>
<area shape="rect" id="node6" title="STL class. " alt="" coords="640,160,720,237"/>
<area shape="rect" id="node11" href="../../d6/d75/a00604.php" title="A class to talk with the remote apis. " alt="" coords="386,469,582,957"/>
<area shape="rect" id="node7" title="STL class. " alt="" coords="617,5,743,97"/>
<area shape="rect" id="node8" title="STL class. " alt="" coords="163,160,285,237"/>
</map>
</div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-slots"></a>
Public Slots</h2></td></tr>
<tr class="memitem:a8606463f143a72c48e91ea047a4c0e14"><td class="memItemLeft" align="right" valign="top"><a id="a8606463f143a72c48e91ea047a4c0e14"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>signingin</b> ()</td></tr>
<tr class="separator:a8606463f143a72c48e91ea047a4c0e14"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a93a18832275298b8825c76c165161363"><td class="memItemLeft" align="right" valign="top"><a id="a93a18832275298b8825c76c165161363"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>connection</b> ()</td></tr>
<tr class="separator:a93a18832275298b8825c76c165161363"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1b123d82f9403a25bf8742657ded6e0d"><td class="memItemLeft" align="right" valign="top"><a id="a1b123d82f9403a25bf8742657ded6e0d"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>goThrough</b> ()</td></tr>
<tr class="separator:a1b123d82f9403a25bf8742657ded6e0d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a14a8720f2c2b8cae2c59dd901888535b"><td class="memItemLeft" align="right" valign="top"><a id="a14a8720f2c2b8cae2c59dd901888535b"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>reenableLinks</b> ()</td></tr>
<tr class="separator:a14a8720f2c2b8cae2c59dd901888535b"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a97ffb6811b80312f4e6b18ff52ae2a80"><td class="memItemLeft" align="right" valign="top"><a id="a97ffb6811b80312f4e6b18ff52ae2a80"></a>
&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d2a/a00632.php#a97ffb6811b80312f4e6b18ff52ae2a80">SigninWindow</a> (QMainWindow *connectWindow, <a class="el" href="../../d6/d75/a00604.php">Api</a> &amp;api, QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:a97ffb6811b80312f4e6b18ff52ae2a80"><td class="mdescLeft">&#160;</td><td class="mdescRight">The constructor of the class. <br /></td></tr>
<tr class="separator:a97ffb6811b80312f4e6b18ff52ae2a80"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-methods"></a>
Protected Member Functions</h2></td></tr>
<tr class="memitem:abef53069c7523b41bde25b7061e50748"><td class="memItemLeft" align="right" valign="top"><a id="abef53069c7523b41bde25b7061e50748"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>showEvent</b> (QShowEvent *event)</td></tr>
<tr class="separator:abef53069c7523b41bde25b7061e50748"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pri-methods"></a>
Private Member Functions</h2></td></tr>
<tr class="memitem:a48ac2eed1be670ce5b7ddbb482a6f607"><td class="memItemLeft" align="right" valign="top"><a id="a48ac2eed1be670ce5b7ddbb482a6f607"></a>
&#160;</td><td class="memItemRight" valign="bottom"><b>SigninWindow</b> (const <a class="el" href="../../d4/d2a/a00632.php">SigninWindow</a> &amp;other)</td></tr>
<tr class="separator:a48ac2eed1be670ce5b7ddbb482a6f607"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a29beb82ea61b267b93b03ca50f99f5b3"><td class="memItemLeft" align="right" valign="top"><a id="a29beb82ea61b267b93b03ca50f99f5b3"></a>
<a class="el" href="../../d4/d2a/a00632.php">SigninWindow</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>operator=</b> (const <a class="el" href="../../d4/d2a/a00632.php">SigninWindow</a> &amp;other)</td></tr>
<tr class="separator:a29beb82ea61b267b93b03ca50f99f5b3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0df1af0dfcb41a6756d8cf9d12173ded"><td class="memItemLeft" align="right" valign="top"><a id="a0df1af0dfcb41a6756d8cf9d12173ded"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>init</b> (const <a class="el" href="../../d4/d2a/a00632.php">SigninWindow</a> *other=nullptr)</td></tr>
<tr class="separator:a0df1af0dfcb41a6756d8cf9d12173ded"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aac1bf8e7bfc4aa841a96f6983eea7070"><td class="memItemLeft" align="right" valign="top"><a id="aac1bf8e7bfc4aa841a96f6983eea7070"></a>
void&#160;</td><td class="memItemRight" valign="bottom"><b>backConnect</b> ()</td></tr>
<tr class="separator:aac1bf8e7bfc4aa841a96f6983eea7070"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pri-attribs"></a>
Private Attributes</h2></td></tr>
<tr class="memitem:a689089bf317480fe8ce8af3e21b7c004"><td class="memItemLeft" align="right" valign="top"><a id="a689089bf317480fe8ce8af3e21b7c004"></a>
QVBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><b>centerLayout</b></td></tr>
<tr class="separator:a689089bf317480fe8ce8af3e21b7c004"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8b72787d80385c320dd6e37f6dcf9e85"><td class="memItemLeft" align="right" valign="top"><a id="a8b72787d80385c320dd6e37f6dcf9e85"></a>
QWidget *&#160;</td><td class="memItemRight" valign="bottom"><b>center</b></td></tr>
<tr class="separator:a8b72787d80385c320dd6e37f6dcf9e85"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a536b5395ef35314de14d0b2386fe1f03"><td class="memItemLeft" align="right" valign="top"><a id="a536b5395ef35314de14d0b2386fe1f03"></a>
<a class="el" href="../../d1/d51/a00628.php">RegisterWidget</a> *&#160;</td><td class="memItemRight" valign="bottom"><b>_registerer</b></td></tr>
<tr class="separator:a536b5395ef35314de14d0b2386fe1f03"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab150d06d57dd29470ec7c9ea4fe4cc4d"><td class="memItemLeft" align="right" valign="top"><a id="ab150d06d57dd29470ec7c9ea4fe4cc4d"></a>
QLineEdit *&#160;</td><td class="memItemRight" valign="bottom"><b>_teamName</b></td></tr>
<tr class="separator:ab150d06d57dd29470ec7c9ea4fe4cc4d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a582cfe0fed4f60a69009c9a41a48c8cd"><td class="memItemLeft" align="right" valign="top"><a id="a582cfe0fed4f60a69009c9a41a48c8cd"></a>
QPushButton *&#160;</td><td class="memItemRight" valign="bottom"><b>_signin</b></td></tr>
<tr class="separator:a582cfe0fed4f60a69009c9a41a48c8cd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac8eb6a3bab389e6f27456c80022ece8f"><td class="memItemLeft" align="right" valign="top"><a id="ac8eb6a3bab389e6f27456c80022ece8f"></a>
QCommandLinkButton *&#160;</td><td class="memItemRight" valign="bottom"><b>_connect</b></td></tr>
<tr class="separator:ac8eb6a3bab389e6f27456c80022ece8f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9724ebac9385920398eae9b12bf46344"><td class="memItemLeft" align="right" valign="top"><a id="a9724ebac9385920398eae9b12bf46344"></a>
QMainWindow *&#160;</td><td class="memItemRight" valign="bottom"><b>_connectWindow</b></td></tr>
<tr class="separator:a9724ebac9385920398eae9b12bf46344"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa66ebd3592a2778af120d8f6c9ef5394"><td class="memItemLeft" align="right" valign="top"><a id="aa66ebd3592a2778af120d8f6c9ef5394"></a>
<a class="el" href="../../d6/d75/a00604.php">Api</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>_api</b></td></tr>
<tr class="separator:aa66ebd3592a2778af120d8f6c9ef5394"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>The main window of the software. </p>
</div><hr/>The documentation for this class was generated from the following file:<ul>
<li>SigninWindow.h</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../d4/d2a/a00632.php">SigninWindow</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
