<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: Api Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:04:17 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('dc/d62/a00640.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-slots">Public Slots</a> &#124;
<a href="#signals">Signals</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-methods">Protected Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="../../de/dbb/a00637.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">Api Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A class to talk with the remote apis.  
 <a href="../../dc/d62/a00640.php#details">More...</a></p>

<p><code>#include &lt;Api.hpp&gt;</code></p>
<div class="dynheader">
Inheritance diagram for Api:</div>
<div class="dyncontent">
<div class="center"><img src="../../dd/db6/a00639.png" border="0" usemap="#Api_inherit__map" alt="Inheritance graph"/></div>
<map name="Api_inherit__map" id="Api_inherit__map">
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for Api:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/daa/a00638.png" border="0" usemap="#Api_coll__map" alt="Collaboration graph"/></div>
<map name="Api_coll__map" id="Api_coll__map">
<area shape="rect" id="node4" title="STL class. " alt="" coords="259,107,339,133"/>
<area shape="rect" id="node5" title="STL class. " alt="" coords="5,99,132,141"/>
<area shape="rect" id="node6" title="STL class. " alt="" coords="237,243,360,269"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-slots"></a>
Public Slots</h2></td></tr>
<tr class="memitem:a8690ac3b4f5e72aad8142f7d2bfd2695"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a8690ac3b4f5e72aad8142f7d2bfd2695">getAll</a> ()</td></tr>
<tr class="separator:a8690ac3b4f5e72aad8142f7d2bfd2695"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac2b5e102425358d7d2eebac89d65e30a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#ac2b5e102425358d7d2eebac89d65e30a">auth_end</a> (QNetworkReply *reply)</td></tr>
<tr class="separator:ac2b5e102425358d7d2eebac89d65e30a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a39c0094cc013eef8d512915bb1be0f91"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a39c0094cc013eef8d512915bb1be0f91">register_end</a> (QNetworkReply *reply)</td></tr>
<tr class="separator:a39c0094cc013eef8d512915bb1be0f91"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3a194c206cbed4dd649ca925f74187c2"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a3a194c206cbed4dd649ca925f74187c2">save_end</a> (QNetworkReply *reply)</td></tr>
<tr class="separator:a3a194c206cbed4dd649ca925f74187c2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a090232a9cc268f4b61c5c91b6f1c4b40"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a090232a9cc268f4b61c5c91b6f1c4b40">saveMembers_end</a> (QNetworkReply *reply)</td></tr>
<tr class="separator:a090232a9cc268f4b61c5c91b6f1c4b40"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a38ddf54ba912805d223e8967979777d7"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a38ddf54ba912805d223e8967979777d7">getAll_end</a> (QNetworkReply *reply)</td></tr>
<tr class="separator:a38ddf54ba912805d223e8967979777d7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a547d36bee82f736d43649dfec011e3d4"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a547d36bee82f736d43649dfec011e3d4">compute_end</a> (QNetworkReply *reply)</td></tr>
<tr class="separator:a547d36bee82f736d43649dfec011e3d4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af1cf07b8f53877d07d56a4b537ba752e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#af1cf07b8f53877d07d56a4b537ba752e">register_user_end</a> (QNetworkReply *reply)</td></tr>
<tr class="separator:af1cf07b8f53877d07d56a4b537ba752e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a84afd510ae92a5ebbb49843a5f54675f"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a84afd510ae92a5ebbb49843a5f54675f">register_team_end</a> (QNetworkReply *reply)</td></tr>
<tr class="separator:a84afd510ae92a5ebbb49843a5f54675f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a15d21dee37cd82a72645a40e26d50941"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a15d21dee37cd82a72645a40e26d50941">register_teammember_end</a> (QNetworkReply *reply)</td></tr>
<tr class="separator:a15d21dee37cd82a72645a40e26d50941"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7b1f827ec6102deb0b38e2f28089e1c1"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a7b1f827ec6102deb0b38e2f28089e1c1">signin_user_end</a> (QNetworkReply *reply)</td></tr>
<tr class="separator:a7b1f827ec6102deb0b38e2f28089e1c1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2919e9666178e7ab5d8ff7a9425d3079"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a2919e9666178e7ab5d8ff7a9425d3079">signin_teammember_end</a> (QNetworkReply *reply)</td></tr>
<tr class="separator:a2919e9666178e7ab5d8ff7a9425d3079"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="signals"></a>
Signals</h2></td></tr>
<tr class="memitem:a9bc95b70776528d7672b1ba5dc449546"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a9bc95b70776528d7672b1ba5dc449546">auth_ended</a> ()</td></tr>
<tr class="separator:a9bc95b70776528d7672b1ba5dc449546"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0498d5c3a110596ad05c46dce4677fc7"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a0498d5c3a110596ad05c46dce4677fc7">auth_error</a> ()</td></tr>
<tr class="separator:a0498d5c3a110596ad05c46dce4677fc7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab5c7c1aaad0d03fadc18252e24301380"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#ab5c7c1aaad0d03fadc18252e24301380">signin_ended</a> ()</td></tr>
<tr class="separator:ab5c7c1aaad0d03fadc18252e24301380"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3d35018066513c86a6dd65db10f8e74f"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a3d35018066513c86a6dd65db10f8e74f">signin_error</a> ()</td></tr>
<tr class="separator:a3d35018066513c86a6dd65db10f8e74f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab1510b8b5126665a7ee0af2cb32f418c"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#ab1510b8b5126665a7ee0af2cb32f418c">signin_ended</a> (const std::string &amp;id)</td></tr>
<tr class="separator:ab1510b8b5126665a7ee0af2cb32f418c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a375db9cdee6f799187b416295ef7bba4"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a375db9cdee6f799187b416295ef7bba4">signin_error</a> (const std::string &amp;id)</td></tr>
<tr class="separator:a375db9cdee6f799187b416295ef7bba4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2c818677d55b216d97357347cb7f31e8"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a2c818677d55b216d97357347cb7f31e8">save_ended</a> ()</td></tr>
<tr class="separator:a2c818677d55b216d97357347cb7f31e8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab555274c529f2d7c42eb772f10ddf026"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#ab555274c529f2d7c42eb772f10ddf026">save_error</a> ()</td></tr>
<tr class="separator:ab555274c529f2d7c42eb772f10ddf026"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acf220a4d7cff209cc4c30f4703f3c1b7"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#acf220a4d7cff209cc4c30f4703f3c1b7">saveMembers_ended</a> ()</td></tr>
<tr class="separator:acf220a4d7cff209cc4c30f4703f3c1b7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac7809d993ef34286970ee0edfed30fd9"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#ac7809d993ef34286970ee0edfed30fd9">saveMembers_error</a> ()</td></tr>
<tr class="separator:ac7809d993ef34286970ee0edfed30fd9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4f7e78eeea139c6ba315568231646bcb"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a4f7e78eeea139c6ba315568231646bcb">getAll_ended</a> ()</td></tr>
<tr class="separator:a4f7e78eeea139c6ba315568231646bcb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7ec193ec81e5e20955eaa43f1751807b"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a7ec193ec81e5e20955eaa43f1751807b">getAll_ended</a> (const <a class="el" href="../../df/d37/a00652.php">Globals</a> &amp;globals, const std::vector&lt; <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &gt; &amp;teamMembers, const <a class="el" href="../../df/d46/a00664.php">Planning</a> &amp;planning)</td></tr>
<tr class="separator:a7ec193ec81e5e20955eaa43f1751807b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa74c11986db59a2ac20b3cad3f16d1b8"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#aa74c11986db59a2ac20b3cad3f16d1b8">getAll_error</a> ()</td></tr>
<tr class="separator:aa74c11986db59a2ac20b3cad3f16d1b8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3a433ef809a5c9ac0d42732883aa4828"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a3a433ef809a5c9ac0d42732883aa4828">compute_ended</a> ()</td></tr>
<tr class="separator:a3a433ef809a5c9ac0d42732883aa4828"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aca64a03f4af7f8a6ebfdb72b3e22c83a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#aca64a03f4af7f8a6ebfdb72b3e22c83a">compute_error</a> ()</td></tr>
<tr class="separator:aca64a03f4af7f8a6ebfdb72b3e22c83a"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a84682b994ff76304c01175d83bb62544"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a84682b994ff76304c01175d83bb62544">Api</a> ()</td></tr>
<tr class="memdesc:a84682b994ff76304c01175d83bb62544"><td class="mdescLeft">&#160;</td><td class="mdescRight">The constructor of the class.  <a href="#a84682b994ff76304c01175d83bb62544">More...</a><br /></td></tr>
<tr class="separator:a84682b994ff76304c01175d83bb62544"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3e0643b013bb9daab48b823673c308cc"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a3e0643b013bb9daab48b823673c308cc">~Api</a> ()</td></tr>
<tr class="separator:a3e0643b013bb9daab48b823673c308cc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8362fa295c1927e08e4844542327665e"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a8362fa295c1927e08e4844542327665e">isChef</a> () const</td></tr>
<tr class="separator:a8362fa295c1927e08e4844542327665e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af71f3cf41e5994081e09e2aed5aa9917"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#af71f3cf41e5994081e09e2aed5aa9917">connection</a> (const std::string &amp;host)</td></tr>
<tr class="separator:af71f3cf41e5994081e09e2aed5aa9917"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adf98fcf11929460567d25f3c3ca046c7"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#adf98fcf11929460567d25f3c3ca046c7">auth</a> (const std::string &amp;user, const std::string &amp;pass)</td></tr>
<tr class="separator:adf98fcf11929460567d25f3c3ca046c7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4f521a9df68fb7d6df5693d1587bcc39"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a4f521a9df68fb7d6df5693d1587bcc39">signin</a> (const <a class="el" href="../../d4/d2a/a00632.php">AuthUser</a> &amp;user, const <a class="el" href="../../db/ddc/a00636.php">AuthMember</a> &amp;member, const std::string &amp;teamName)</td></tr>
<tr class="separator:a4f521a9df68fb7d6df5693d1587bcc39"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a04d38baff9d072002663de5c612901da"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a04d38baff9d072002663de5c612901da">signin</a> (const <a class="el" href="../../d4/d2a/a00632.php">AuthUser</a> &amp;user, const <a class="el" href="../../db/ddc/a00636.php">AuthMember</a> &amp;member)</td></tr>
<tr class="separator:a04d38baff9d072002663de5c612901da"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1b4676d1a5dd5537f9e380e51b2c3f68"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a1b4676d1a5dd5537f9e380e51b2c3f68">save</a> (const <a class="el" href="../../df/d37/a00652.php">Globals</a> &amp;team, const <a class="el" href="../../df/d46/a00664.php">Planning</a> &amp;planning)</td></tr>
<tr class="separator:a1b4676d1a5dd5537f9e380e51b2c3f68"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aac006983648944a4b88969ebe29e43c6"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#aac006983648944a4b88969ebe29e43c6">saveMembers</a> (const std::vector&lt; <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &gt; &amp;team)</td></tr>
<tr class="separator:aac006983648944a4b88969ebe29e43c6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae351826f48dff2c62da2d4c5d73c4e78"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#ae351826f48dff2c62da2d4c5d73c4e78">deleteMember</a> (const std::string &amp;id)</td></tr>
<tr class="separator:ae351826f48dff2c62da2d4c5d73c4e78"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3005eb166846be59810e7cd077bfb1fc"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a3005eb166846be59810e7cd077bfb1fc">compute</a> ()</td></tr>
<tr class="separator:a3005eb166846be59810e7cd077bfb1fc"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-methods"></a>
Protected Member Functions</h2></td></tr>
<tr class="memitem:ab2adb83a606e8c98a088700933164a2e"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#ab2adb83a606e8c98a088700933164a2e">base64_encode</a> (const std::string &amp;str)</td></tr>
<tr class="separator:ab2adb83a606e8c98a088700933164a2e"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr class="memitem:acd5e259f4c3271f090310b5bf4b67e83"><td class="memItemLeft" align="right" valign="top">std::map&lt; std::string, QNetworkAccessManager * &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#acd5e259f4c3271f090310b5bf4b67e83">_managers</a></td></tr>
<tr class="separator:acd5e259f4c3271f090310b5bf4b67e83"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3363125cf76e33f196a9932c0920b2f8"><td class="memItemLeft" align="right" valign="top">std::map&lt; std::string, std::string &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#a3363125cf76e33f196a9932c0920b2f8">_urls</a></td></tr>
<tr class="separator:a3363125cf76e33f196a9932c0920b2f8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac8a878964a51f589adad565861a407a6"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d62/a00640.php#ac8a878964a51f589adad565861a407a6">_host</a></td></tr>
<tr class="separator:ac8a878964a51f589adad565861a407a6"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>A class to talk with the remote apis. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a84682b994ff76304c01175d83bb62544"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a84682b994ff76304c01175d83bb62544">&#9670;&nbsp;</a></span>Api()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Api::Api </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>The constructor of the class. </p>

</div>
</div>
<a id="a3e0643b013bb9daab48b823673c308cc"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3e0643b013bb9daab48b823673c308cc">&#9670;&nbsp;</a></span>~Api()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual Api::~Api </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="adf98fcf11929460567d25f3c3ca046c7"></a>
<h2 class="memtitle"><span class="permalink"><a href="#adf98fcf11929460567d25f3c3ca046c7">&#9670;&nbsp;</a></span>auth()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Api::auth </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>user</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>pass</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="ac2b5e102425358d7d2eebac89d65e30a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac2b5e102425358d7d2eebac89d65e30a">&#9670;&nbsp;</a></span>auth_end</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::auth_end </td>
          <td>(</td>
          <td class="paramtype">QNetworkReply *&#160;</td>
          <td class="paramname"><em>reply</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a9bc95b70776528d7672b1ba5dc449546"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9bc95b70776528d7672b1ba5dc449546">&#9670;&nbsp;</a></span>auth_ended</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::auth_ended </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a0498d5c3a110596ad05c46dce4677fc7"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0498d5c3a110596ad05c46dce4677fc7">&#9670;&nbsp;</a></span>auth_error</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::auth_error </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ab2adb83a606e8c98a088700933164a2e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab2adb83a606e8c98a088700933164a2e">&#9670;&nbsp;</a></span>base64_encode()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::string Api::base64_encode </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>str</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a3005eb166846be59810e7cd077bfb1fc"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3005eb166846be59810e7cd077bfb1fc">&#9670;&nbsp;</a></span>compute()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Api::compute </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a547d36bee82f736d43649dfec011e3d4"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a547d36bee82f736d43649dfec011e3d4">&#9670;&nbsp;</a></span>compute_end</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::compute_end </td>
          <td>(</td>
          <td class="paramtype">QNetworkReply *&#160;</td>
          <td class="paramname"><em>reply</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a3a433ef809a5c9ac0d42732883aa4828"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3a433ef809a5c9ac0d42732883aa4828">&#9670;&nbsp;</a></span>compute_ended</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::compute_ended </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="aca64a03f4af7f8a6ebfdb72b3e22c83a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aca64a03f4af7f8a6ebfdb72b3e22c83a">&#9670;&nbsp;</a></span>compute_error</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::compute_error </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="af71f3cf41e5994081e09e2aed5aa9917"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af71f3cf41e5994081e09e2aed5aa9917">&#9670;&nbsp;</a></span>connection()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool Api::connection </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>host</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="ae351826f48dff2c62da2d4c5d73c4e78"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae351826f48dff2c62da2d4c5d73c4e78">&#9670;&nbsp;</a></span>deleteMember()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Api::deleteMember </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a8690ac3b4f5e72aad8142f7d2bfd2695"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a8690ac3b4f5e72aad8142f7d2bfd2695">&#9670;&nbsp;</a></span>getAll</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::getAll </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a38ddf54ba912805d223e8967979777d7"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a38ddf54ba912805d223e8967979777d7">&#9670;&nbsp;</a></span>getAll_end</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::getAll_end </td>
          <td>(</td>
          <td class="paramtype">QNetworkReply *&#160;</td>
          <td class="paramname"><em>reply</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a4f7e78eeea139c6ba315568231646bcb"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a4f7e78eeea139c6ba315568231646bcb">&#9670;&nbsp;</a></span>getAll_ended <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::getAll_ended </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a7ec193ec81e5e20955eaa43f1751807b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7ec193ec81e5e20955eaa43f1751807b">&#9670;&nbsp;</a></span>getAll_ended <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::getAll_ended </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="../../df/d37/a00652.php">Globals</a> &amp;&#160;</td>
          <td class="paramname"><em>globals</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::vector&lt; <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &gt; &amp;&#160;</td>
          <td class="paramname"><em>teamMembers</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="../../df/d46/a00664.php">Planning</a> &amp;&#160;</td>
          <td class="paramname"><em>planning</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="aa74c11986db59a2ac20b3cad3f16d1b8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa74c11986db59a2ac20b3cad3f16d1b8">&#9670;&nbsp;</a></span>getAll_error</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::getAll_error </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a8362fa295c1927e08e4844542327665e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a8362fa295c1927e08e4844542327665e">&#9670;&nbsp;</a></span>isChef()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">bool Api::isChef </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../dc/d62/a00640_a8362fa295c1927e08e4844542327665e_cgraph.png" border="0" usemap="#dc/d62/a00640_a8362fa295c1927e08e4844542327665e_cgraph" alt=""/></div>
<map name="dc/d62/a00640_a8362fa295c1927e08e4844542327665e_cgraph" id="dc/d62/a00640_a8362fa295c1927e08e4844542327665e_cgraph">
<area shape="rect" id="node2" href="../../d6/d2d/a00047.php#ad8398c3fc4be4b0bd7bb7de1b5174ef6" title="deleteMember" alt="" coords="140,5,244,32"/>
</map>
</div>

</div>
</div>
<a id="a39c0094cc013eef8d512915bb1be0f91"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a39c0094cc013eef8d512915bb1be0f91">&#9670;&nbsp;</a></span>register_end</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::register_end </td>
          <td>(</td>
          <td class="paramtype">QNetworkReply *&#160;</td>
          <td class="paramname"><em>reply</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a84afd510ae92a5ebbb49843a5f54675f"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a84afd510ae92a5ebbb49843a5f54675f">&#9670;&nbsp;</a></span>register_team_end</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::register_team_end </td>
          <td>(</td>
          <td class="paramtype">QNetworkReply *&#160;</td>
          <td class="paramname"><em>reply</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a15d21dee37cd82a72645a40e26d50941"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a15d21dee37cd82a72645a40e26d50941">&#9670;&nbsp;</a></span>register_teammember_end</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::register_teammember_end </td>
          <td>(</td>
          <td class="paramtype">QNetworkReply *&#160;</td>
          <td class="paramname"><em>reply</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="af1cf07b8f53877d07d56a4b537ba752e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af1cf07b8f53877d07d56a4b537ba752e">&#9670;&nbsp;</a></span>register_user_end</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::register_user_end </td>
          <td>(</td>
          <td class="paramtype">QNetworkReply *&#160;</td>
          <td class="paramname"><em>reply</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a1b4676d1a5dd5537f9e380e51b2c3f68"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a1b4676d1a5dd5537f9e380e51b2c3f68">&#9670;&nbsp;</a></span>save()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Api::save </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="../../df/d37/a00652.php">Globals</a> &amp;&#160;</td>
          <td class="paramname"><em>team</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="../../df/d46/a00664.php">Planning</a> &amp;&#160;</td>
          <td class="paramname"><em>planning</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a3a194c206cbed4dd649ca925f74187c2"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3a194c206cbed4dd649ca925f74187c2">&#9670;&nbsp;</a></span>save_end</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::save_end </td>
          <td>(</td>
          <td class="paramtype">QNetworkReply *&#160;</td>
          <td class="paramname"><em>reply</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a2c818677d55b216d97357347cb7f31e8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a2c818677d55b216d97357347cb7f31e8">&#9670;&nbsp;</a></span>save_ended</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::save_ended </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ab555274c529f2d7c42eb772f10ddf026"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab555274c529f2d7c42eb772f10ddf026">&#9670;&nbsp;</a></span>save_error</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::save_error </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="aac006983648944a4b88969ebe29e43c6"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aac006983648944a4b88969ebe29e43c6">&#9670;&nbsp;</a></span>saveMembers()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Api::saveMembers </td>
          <td>(</td>
          <td class="paramtype">const std::vector&lt; <a class="el" href="../../d5/d39/a00676.php">TeamMember</a> &gt; &amp;&#160;</td>
          <td class="paramname"><em>team</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a090232a9cc268f4b61c5c91b6f1c4b40"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a090232a9cc268f4b61c5c91b6f1c4b40">&#9670;&nbsp;</a></span>saveMembers_end</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::saveMembers_end </td>
          <td>(</td>
          <td class="paramtype">QNetworkReply *&#160;</td>
          <td class="paramname"><em>reply</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="acf220a4d7cff209cc4c30f4703f3c1b7"></a>
<h2 class="memtitle"><span class="permalink"><a href="#acf220a4d7cff209cc4c30f4703f3c1b7">&#9670;&nbsp;</a></span>saveMembers_ended</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::saveMembers_ended </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ac7809d993ef34286970ee0edfed30fd9"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac7809d993ef34286970ee0edfed30fd9">&#9670;&nbsp;</a></span>saveMembers_error</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::saveMembers_error </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a4f521a9df68fb7d6df5693d1587bcc39"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a4f521a9df68fb7d6df5693d1587bcc39">&#9670;&nbsp;</a></span>signin() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Api::signin </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="../../d4/d2a/a00632.php">AuthUser</a> &amp;&#160;</td>
          <td class="paramname"><em>user</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="../../db/ddc/a00636.php">AuthMember</a> &amp;&#160;</td>
          <td class="paramname"><em>member</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>teamName</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a04d38baff9d072002663de5c612901da"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a04d38baff9d072002663de5c612901da">&#9670;&nbsp;</a></span>signin() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Api::signin </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="../../d4/d2a/a00632.php">AuthUser</a> &amp;&#160;</td>
          <td class="paramname"><em>user</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="../../db/ddc/a00636.php">AuthMember</a> &amp;&#160;</td>
          <td class="paramname"><em>member</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="ab5c7c1aaad0d03fadc18252e24301380"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab5c7c1aaad0d03fadc18252e24301380">&#9670;&nbsp;</a></span>signin_ended <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::signin_ended </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ab1510b8b5126665a7ee0af2cb32f418c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab1510b8b5126665a7ee0af2cb32f418c">&#9670;&nbsp;</a></span>signin_ended <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::signin_ended </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a3d35018066513c86a6dd65db10f8e74f"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3d35018066513c86a6dd65db10f8e74f">&#9670;&nbsp;</a></span>signin_error <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::signin_error </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a375db9cdee6f799187b416295ef7bba4"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a375db9cdee6f799187b416295ef7bba4">&#9670;&nbsp;</a></span>signin_error <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::signin_error </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a2919e9666178e7ab5d8ff7a9425d3079"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a2919e9666178e7ab5d8ff7a9425d3079">&#9670;&nbsp;</a></span>signin_teammember_end</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::signin_teammember_end </td>
          <td>(</td>
          <td class="paramtype">QNetworkReply *&#160;</td>
          <td class="paramname"><em>reply</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a7b1f827ec6102deb0b38e2f28089e1c1"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7b1f827ec6102deb0b38e2f28089e1c1">&#9670;&nbsp;</a></span>signin_user_end</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Api::signin_user_end </td>
          <td>(</td>
          <td class="paramtype">QNetworkReply *&#160;</td>
          <td class="paramname"><em>reply</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a id="ac8a878964a51f589adad565861a407a6"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac8a878964a51f589adad565861a407a6">&#9670;&nbsp;</a></span>_host</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::string Api::_host</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="acd5e259f4c3271f090310b5bf4b67e83"></a>
<h2 class="memtitle"><span class="permalink"><a href="#acd5e259f4c3271f090310b5bf4b67e83">&#9670;&nbsp;</a></span>_managers</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::map&lt;std::string, QNetworkAccessManager*&gt; Api::_managers</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a3363125cf76e33f196a9932c0920b2f8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3363125cf76e33f196a9932c0920b2f8">&#9670;&nbsp;</a></span>_urls</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::map&lt;std::string, std::string&gt; Api::_urls</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../dd/dad/a00005.php">Api.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dc/d62/a00640.php">Api</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
