<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: Class Members - Variables</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:22:26 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('functions_vars.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a id="index__"></a>- _ -</h3><ul>
<li>_api
: <a class="el" href="d0/dec/a00592.php#acb002f8ff2cbcb542bbe6294dc0be8f3">AddMemberModal</a>
, <a class="el" href="d4/d14/a00608.php#ad68d5da50b971b1725cfa2f80b7cec9d">ConnectWindow</a>
, <a class="el" href="db/db5/a00616.php#ae21b928d41978e70e14a530b40d4412b">MainWindow</a>
, <a class="el" href="d4/d2a/a00632.php#aa66ebd3592a2778af120d8f6c9ef5394">SigninWindow</a>
</li>
<li>_autoChange
: <a class="el" href="db/db5/a00616.php#a85a36afcb6c98fc556bf080ba380a74f">MainWindow</a>
</li>
<li>_checkAll
: <a class="el" href="d1/d51/a00628.php#af743f98c0d1088e3955c11f7ecca8ad8">RegisterWidget</a>
</li>
<li>_chef
: <a class="el" href="d6/d75/a00604.php#a76fd16d79629f8ff9bb8d8a486f1999e">Api</a>
</li>
<li>_confirmButton
: <a class="el" href="d0/dec/a00592.php#acf127048a8c1cf4e6ceb3b18ca3ada10">AddMemberModal</a>
</li>
<li>_connect
: <a class="el" href="d4/d14/a00608.php#a2f6c8d9554853540e47c03df2b25a310">ConnectWindow</a>
, <a class="el" href="d4/d2a/a00632.php#ac8eb6a3bab389e6f27456c80022ece8f">SigninWindow</a>
</li>
<li>_connectWindow
: <a class="el" href="d4/d2a/a00632.php#a9724ebac9385920398eae9b12bf46344">SigninWindow</a>
</li>
<li>_daysOff
: <a class="el" href="d0/dec/a00592.php#a21708e1de2d3b42402323f7b7170a91e">AddMemberModal</a>
, <a class="el" href="db/ddc/a00636.php#aaef7d63febe37ecec56fa06abad1a2c6">TeamMember</a>
</li>
<li>_firstGet
: <a class="el" href="d6/d75/a00604.php#a92d67445cf32ab345045579e4d305e54">Api</a>
</li>
<li>_firstName
: <a class="el" href="d1/d51/a00628.php#ae3439ba0a314e23e82a9a136a4163f84">RegisterWidget</a>
, <a class="el" href="db/ddc/a00636.php#a428a8ed576625ee8c9da4a16985fab54">TeamMember</a>
</li>
<li>_g_allCheckbox
: <a class="el" href="db/db5/a00616.php#accb60d49f29adfa58fb1b8170c668533">MainWindow</a>
</li>
<li>_g_checkAllLay
: <a class="el" href="db/db5/a00616.php#aa9e71552e9a1773d1a1d67de3324bc7a">MainWindow</a>
</li>
<li>_g_checkDays
: <a class="el" href="db/db5/a00616.php#a4c9d0034794e82e7906e1ef189238ab6">MainWindow</a>
</li>
<li>_g_daysCheckboxes
: <a class="el" href="db/db5/a00616.php#aff1344a2e553d4228d5a04d84ec37207">MainWindow</a>
</li>
<li>_g_daysChoice
: <a class="el" href="db/db5/a00616.php#ae1107f643a19983423d9070001951382">MainWindow</a>
</li>
<li>_g_defaultHoursEdit
: <a class="el" href="db/db5/a00616.php#acc5975cbbe95f860f28807f04668c6b1">MainWindow</a>
</li>
<li>_g_defaultHoursLabel
: <a class="el" href="db/db5/a00616.php#a604496fd8b05a256fd42857f6e8582b9">MainWindow</a>
</li>
<li>_g_defaultHoursLay
: <a class="el" href="db/db5/a00616.php#affd29f71ee51875a0c5108d86c258016">MainWindow</a>
</li>
<li>_g_lay
: <a class="el" href="db/db5/a00616.php#aca0d693d253295a2a99e7cfcab0d2cf3">MainWindow</a>
</li>
<li>_g_maxTimeEdit
: <a class="el" href="db/db5/a00616.php#ae2178605ddcf6a8a228d467f8fe16f48">MainWindow</a>
</li>
<li>_g_maxTimeLabel
: <a class="el" href="db/db5/a00616.php#a07dba83a34b95c13c18216ad3306cc67">MainWindow</a>
</li>
<li>_g_maxTimeLay
: <a class="el" href="db/db5/a00616.php#ae9f579716520463962e97ceb7a4f10f1">MainWindow</a>
</li>
<li>_g_minTimeEdit
: <a class="el" href="db/db5/a00616.php#ad732e3faa84f5c5e062ef230504f7708">MainWindow</a>
</li>
<li>_g_minTimeLabel
: <a class="el" href="db/db5/a00616.php#a478381515eabf0a1cfff6c9e0dafcdb1">MainWindow</a>
</li>
<li>_g_minTimeLay
: <a class="el" href="db/db5/a00616.php#ab6e5fcaef945c922475f8247380eeec6">MainWindow</a>
</li>
<li>_g_tab
: <a class="el" href="db/db5/a00616.php#a579b74a045f9af9152407428ea23f1d1">MainWindow</a>
</li>
<li>_g_toolBar
: <a class="el" href="db/db5/a00616.php#a8bfe7f00b3c0ba50703baa32d06e82e6">MainWindow</a>
</li>
<li>_genAct
: <a class="el" href="db/db5/a00616.php#ad0d888116fe23b0d7a5c132234485146">MainWindow</a>
</li>
<li>_host
: <a class="el" href="d6/d75/a00604.php#ac8a878964a51f589adad565861a407a6">Api</a>
</li>
<li>_hoursPerWeek
: <a class="el" href="d1/d51/a00628.php#abfaaa76d8f2a3eb77fbe47c88135031e">RegisterWidget</a>
</li>
<li>_id
: <a class="el" href="db/ddc/a00636.php#a9ee0ee9816c842a4979692db4e7e4422">TeamMember</a>
</li>
<li>_lastName
: <a class="el" href="d1/d51/a00628.php#a42ef8b4599d867b0d7ad08c8362d696d">RegisterWidget</a>
, <a class="el" href="db/ddc/a00636.php#a06b44f3e3044c03f76ce8f7a7aa938e2">TeamMember</a>
</li>
<li>_mainWindow
: <a class="el" href="d4/d14/a00608.php#aac64b05e447e14b86981432b854635b8">ConnectWindow</a>
</li>
<li>_managers
: <a class="el" href="d6/d75/a00604.php#acd5e259f4c3271f090310b5bf4b67e83">Api</a>
</li>
<li>_nbHours
: <a class="el" href="db/ddc/a00636.php#aabad9f4729689ff0b9a3daf91bbc898a">TeamMember</a>
</li>
<li>_p_globals
: <a class="el" href="db/db5/a00616.php#afb4788b7a84063543823a0feb8d134b9">MainWindow</a>
</li>
<li>_p_teamMembers
: <a class="el" href="db/db5/a00616.php#a6b1643e8e22c9319b8930f8c1780560c">MainWindow</a>
</li>
<li>_passless
: <a class="el" href="d1/d51/a00628.php#ab5d6d76215556bcf8c6a4dc6f4c720e0">RegisterWidget</a>
</li>
<li>_password
: <a class="el" href="d4/d14/a00608.php#a2f14c7f204e2f5523fa4d3442abbda38">ConnectWindow</a>
, <a class="el" href="d1/d51/a00628.php#aff0471897ece6bb0c08ea2a4e5e035e6">RegisterWidget</a>
</li>
<li>_passwordConf
: <a class="el" href="d1/d51/a00628.php#a5c1cf1097d44adec4ab1edc689609e08">RegisterWidget</a>
</li>
<li>_planning
: <a class="el" href="db/db5/a00616.php#a96ecd85e9f5a24073a878db40d80dfe0">MainWindow</a>
</li>
<li>_planningLay
: <a class="el" href="db/db5/a00616.php#a8cf9dfaf8e8f44dd2da3c912ec42bc1c">MainWindow</a>
</li>
<li>_planningTab
: <a class="el" href="db/db5/a00616.php#a4bcec25200d3263b59d9fbf442a7daf0">MainWindow</a>
</li>
<li>_register
: <a class="el" href="d0/dec/a00592.php#aa818f39ab8ce3a90e7275c04265196cf">AddMemberModal</a>
</li>
<li>_registerer
: <a class="el" href="d4/d2a/a00632.php#a536b5395ef35314de14d0b2386fe1f03">SigninWindow</a>
</li>
<li>_saveAct
: <a class="el" href="db/db5/a00616.php#ac5a7f857261819efa73a7066aa5a7301">MainWindow</a>
</li>
<li>_signin
: <a class="el" href="d4/d14/a00608.php#a4f39a3777b052cd8d6c0782d78aca779">ConnectWindow</a>
, <a class="el" href="d4/d2a/a00632.php#a582cfe0fed4f60a69009c9a41a48c8cd">SigninWindow</a>
</li>
<li>_signinWindow
: <a class="el" href="d4/d14/a00608.php#abef9f6df480082080ac2369d45030d38">ConnectWindow</a>
</li>
<li>_syncAct
: <a class="el" href="db/db5/a00616.php#ac7e613964435c0784650a1440e714b7a">MainWindow</a>
</li>
<li>_t_daysCheckboxes
: <a class="el" href="d1/d51/a00628.php#ac586ce09560b4282faf3adbd26aeba3c">RegisterWidget</a>
</li>
<li>_tab
: <a class="el" href="db/db5/a00616.php#a2b7eef73dbbc7cece6889cef4092c925">MainWindow</a>
</li>
<li>_teamCenter
: <a class="el" href="db/db5/a00616.php#a10117d7c167c147d48f70a6296e6df1a">MainWindow</a>
</li>
<li>_teamid
: <a class="el" href="d6/d75/a00604.php#a63e9bdd96e19b4a1fba5e890e83b8216">Api</a>
</li>
<li>_teamLay
: <a class="el" href="db/db5/a00616.php#a5183b60f5b4e05ac10b45600bf94f963">MainWindow</a>
</li>
<li>_teammemberid
: <a class="el" href="d6/d75/a00604.php#a46880b407cd4d199d9fb1c0c42930a17">Api</a>
</li>
<li>_teamMembers
: <a class="el" href="d0/dec/a00592.php#a5761807b959efa8db63854af4434c900">AddMemberModal</a>
</li>
<li>_teamName
: <a class="el" href="d4/d2a/a00632.php#ab150d06d57dd29470ec7c9ea4fe4cc4d">SigninWindow</a>
</li>
<li>_teamTab
: <a class="el" href="db/db5/a00616.php#aa0d31f61b8c3da61cf1cc9dee8cd2961">MainWindow</a>
</li>
<li>_teamTable
: <a class="el" href="d0/dec/a00592.php#ae8050e27d792a4d4043691a10a739392">AddMemberModal</a>
, <a class="el" href="db/db5/a00616.php#ab0ecb072ce22a42948e056aaadccc722">MainWindow</a>
</li>
<li>_teamToolBar
: <a class="el" href="db/db5/a00616.php#a20c12be6d8fa26f9c21d751278559586">MainWindow</a>
</li>
<li>_token
: <a class="el" href="d6/d75/a00604.php#afaff93ac57381c8bf3fe0cc7abdf6975">Api</a>
</li>
<li>_urls
: <a class="el" href="d6/d75/a00604.php#a3363125cf76e33f196a9932c0920b2f8">Api</a>
</li>
<li>_userid
: <a class="el" href="d6/d75/a00604.php#a468f2ba533071f4a57e78292d93a3455">Api</a>
</li>
<li>_username
: <a class="el" href="d6/d75/a00604.php#ad60fcde009ca596d97ef28f3c0f3a9e5">Api</a>
, <a class="el" href="d4/d14/a00608.php#a9923b957870f20f0ffa9c0d7bd28efdd">ConnectWindow</a>
, <a class="el" href="d1/d51/a00628.php#a74237be10533acff46f14589b3568ade">RegisterWidget</a>
</li>
</ul>


<h3><a id="index_c"></a>- c -</h3><ul>
<li>center
: <a class="el" href="d4/d14/a00608.php#a7574b6845a9df5f9a6c3959b4c4476d0">ConnectWindow</a>
, <a class="el" href="db/db5/a00616.php#aebbf677c3c672b4627bde023aae8cc5d">MainWindow</a>
, <a class="el" href="d4/d2a/a00632.php#a8b72787d80385c320dd6e37f6dcf9e85">SigninWindow</a>
</li>
<li>centerLayout
: <a class="el" href="d4/d14/a00608.php#a4cf9a88b88bbd146fb3798631989598f">ConnectWindow</a>
, <a class="el" href="db/db5/a00616.php#aaafcdcfeded1bbf62f6b7bf05a70f819">MainWindow</a>
, <a class="el" href="d1/d51/a00628.php#ac718a184f68ddf595367b91f8ad8e9b5">RegisterWidget</a>
, <a class="el" href="d4/d2a/a00632.php#a689089bf317480fe8ce8af3e21b7c004">SigninWindow</a>
</li>
</ul>


<h3><a id="index_d"></a>- d -</h3><ul>
<li>daysOff
: <a class="el" href="d1/d8c/a00600.php#a265356c98cb163e153ffa6da7ed8e6b5">AuthMember</a>
</li>
</ul>


<h3><a id="index_e"></a>- e -</h3><ul>
<li>end
: <a class="el" href="dc/d4d/a00620.php#ae2ad20e05b76e216cc499b87f917b644">Pause</a>
</li>
<li>endMax
: <a class="el" href="d0/d8d/a00612.php#a9deb9168f76d51325db506b7f4c466e8">Globals</a>
</li>
</ul>


<h3><a id="index_f"></a>- f -</h3><ul>
<li>firstname
: <a class="el" href="d1/d8c/a00600.php#a6769e2f2585d53b8c7011ea26922f829">AuthMember</a>
</li>
</ul>


<h3><a id="index_l"></a>- l -</h3><ul>
<li>lastname
: <a class="el" href="d1/d8c/a00600.php#a032c4e580abcf8a67ce5730aa781ff2f">AuthMember</a>
</li>
</ul>


<h3><a id="index_n"></a>- n -</h3><ul>
<li>nbHours
: <a class="el" href="d1/d8c/a00600.php#a635e47ce910eac239665e3e213aaadf9">AuthMember</a>
, <a class="el" href="d0/d8d/a00612.php#ae151bc2f232e7996921d2885e37acbe0">Globals</a>
</li>
</ul>


<h3><a id="index_p"></a>- p -</h3><ul>
<li>password
: <a class="el" href="dc/d25/a00596.php#a44e66f4bd17013c7af6e7c3a29feb85c">AuthUser</a>
</li>
</ul>


<h3><a id="index_s"></a>- s -</h3><ul>
<li>selectedMember
: <a class="el" href="db/db5/a00616.php#a7d55533f3737f2335ec9cf96e62b85ef">MainWindow</a>
</li>
<li>selectedTeamMembers
: <a class="el" href="db/db5/a00616.php#ad3e946281a4e18941715c55cc6dedba2">MainWindow</a>
</li>
<li>start
: <a class="el" href="dc/d4d/a00620.php#a4a917f6132e2bd44453278c22478a8a0">Pause</a>
</li>
<li>startMin
: <a class="el" href="d0/d8d/a00612.php#a580b0c6e1a15d88437107964687f1e6d">Globals</a>
</li>
</ul>


<h3><a id="index_t"></a>- t -</h3><ul>
<li>teamMembers
: <a class="el" href="db/db5/a00616.php#aba41ddd6ba254cdbcb07792d04364e81">MainWindow</a>
</li>
</ul>


<h3><a id="index_u"></a>- u -</h3><ul>
<li>username
: <a class="el" href="dc/d25/a00596.php#a3be82ebf739591e1f06868a58d25a3cf">AuthUser</a>
</li>
</ul>


<h3><a id="index_w"></a>- w -</h3><ul>
<li>workedDays
: <a class="el" href="d0/d8d/a00612.php#acb5d931277c8126668a043dfe4da4ce5">Globals</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
