<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: Class Members</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:22:26 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('functions_c.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
<div class="textblock">Here is a list of all class members with links to the classes they belong to:</div>

<h3><a id="index_c"></a>- c -</h3><ul>
<li>center
: <a class="el" href="d4/d14/a00608.php#a7574b6845a9df5f9a6c3959b4c4476d0">ConnectWindow</a>
, <a class="el" href="db/db5/a00616.php#aebbf677c3c672b4627bde023aae8cc5d">MainWindow</a>
, <a class="el" href="d4/d2a/a00632.php#a8b72787d80385c320dd6e37f6dcf9e85">SigninWindow</a>
</li>
<li>centerLayout
: <a class="el" href="d4/d14/a00608.php#a4cf9a88b88bbd146fb3798631989598f">ConnectWindow</a>
, <a class="el" href="db/db5/a00616.php#aaafcdcfeded1bbf62f6b7bf05a70f819">MainWindow</a>
, <a class="el" href="d1/d51/a00628.php#ac718a184f68ddf595367b91f8ad8e9b5">RegisterWidget</a>
, <a class="el" href="d4/d2a/a00632.php#a689089bf317480fe8ce8af3e21b7c004">SigninWindow</a>
</li>
<li>closeEvent()
: <a class="el" href="db/db5/a00616.php#a4e20a4a065fbb0e4d3532a45a0a91425">MainWindow</a>
</li>
<li>Columns
: <a class="el" href="d0/dec/a00592.php#a2be2c83a4066d0742719bdaa46a58893">AddMemberModal</a>
</li>
<li>compute()
: <a class="el" href="d6/d75/a00604.php#a3005eb166846be59810e7cd077bfb1fc">Api</a>
</li>
<li>compute_end()
: <a class="el" href="d6/d75/a00604.php#a547d36bee82f736d43649dfec011e3d4">Api</a>
</li>
<li>compute_ended()
: <a class="el" href="d6/d75/a00604.php#a3a433ef809a5c9ac0d42732883aa4828">Api</a>
</li>
<li>compute_error()
: <a class="el" href="d6/d75/a00604.php#aca64a03f4af7f8a6ebfdb72b3e22c83a">Api</a>
</li>
<li>computeIfNeeded()
: <a class="el" href="db/db5/a00616.php#a18dc86b52aff39ce15c68150d6381e7f">MainWindow</a>
</li>
<li>connection()
: <a class="el" href="d6/d75/a00604.php#af71f3cf41e5994081e09e2aed5aa9917">Api</a>
, <a class="el" href="d4/d14/a00608.php#a97ae82d5a82f16be9ef49190831cd627">ConnectWindow</a>
, <a class="el" href="d4/d2a/a00632.php#a93a18832275298b8825c76c165161363">SigninWindow</a>
</li>
<li>ConnectWindow()
: <a class="el" href="d4/d14/a00608.php#a2a74d621a2fca59846652819a809ebfd">ConnectWindow</a>
</li>
<li>createRequest()
: <a class="el" href="d6/d75/a00604.php#a08dc74bcba157287880937b233927ecd">Api</a>
</li>
<li>createUrl()
: <a class="el" href="d6/d75/a00604.php#a21f29472018eaf971b1ade85a0640f04">Api</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
