<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: Class Members</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:22:26 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('functions_s.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
<div class="textblock">Here is a list of all class members with links to the classes they belong to:</div>

<h3><a id="index_s"></a>- s -</h3><ul>
<li>save()
: <a class="el" href="d6/d75/a00604.php#a1b4676d1a5dd5537f9e380e51b2c3f68">Api</a>
</li>
<li>save_end()
: <a class="el" href="d6/d75/a00604.php#a3a194c206cbed4dd649ca925f74187c2">Api</a>
</li>
<li>save_ended()
: <a class="el" href="d6/d75/a00604.php#a2c818677d55b216d97357347cb7f31e8">Api</a>
</li>
<li>save_error()
: <a class="el" href="d6/d75/a00604.php#ab555274c529f2d7c42eb772f10ddf026">Api</a>
</li>
<li>saveMembers()
: <a class="el" href="d6/d75/a00604.php#aac006983648944a4b88969ebe29e43c6">Api</a>
</li>
<li>saveMembers_end()
: <a class="el" href="d6/d75/a00604.php#a090232a9cc268f4b61c5c91b6f1c4b40">Api</a>
</li>
<li>saveMembers_ended()
: <a class="el" href="d6/d75/a00604.php#acf220a4d7cff209cc4c30f4703f3c1b7">Api</a>
</li>
<li>saveMembers_error()
: <a class="el" href="d6/d75/a00604.php#ac7809d993ef34286970ee0edfed30fd9">Api</a>
</li>
<li>selectedMember
: <a class="el" href="db/db5/a00616.php#a7d55533f3737f2335ec9cf96e62b85ef">MainWindow</a>
</li>
<li>selectedTeamMembers
: <a class="el" href="db/db5/a00616.php#ad3e946281a4e18941715c55cc6dedba2">MainWindow</a>
</li>
<li>setDaysOff()
: <a class="el" href="db/ddc/a00636.php#a7cef76489e5bd0fef1930ab423f7e380">TeamMember</a>
</li>
<li>setDaysOffFromQString()
: <a class="el" href="db/ddc/a00636.php#a4ba484e70a61bd21e947d473156b8b73">TeamMember</a>
</li>
<li>setFirstName()
: <a class="el" href="db/ddc/a00636.php#a9981b2e29ca20e9bdb823b8681df0e78">TeamMember</a>
</li>
<li>setId()
: <a class="el" href="db/ddc/a00636.php#a86c4cdab5733790753d3ef79d376a303">TeamMember</a>
</li>
<li>setLastName()
: <a class="el" href="db/ddc/a00636.php#a984fc107fe6518391b2d6a81204b3875">TeamMember</a>
</li>
<li>setNbHours()
: <a class="el" href="db/ddc/a00636.php#aa97881e8e23273d5ebfad4e9c397d235">TeamMember</a>
</li>
<li>setValues()
: <a class="el" href="db/db5/a00616.php#a8d91535d4d2e9f21e3433975f2652826">MainWindow</a>
</li>
<li>showEvent()
: <a class="el" href="d4/d14/a00608.php#a0f5ef34d29f827d44330accba2e81e86">ConnectWindow</a>
, <a class="el" href="d4/d2a/a00632.php#abef53069c7523b41bde25b7061e50748">SigninWindow</a>
</li>
<li>signin()
: <a class="el" href="d6/d75/a00604.php#a4f521a9df68fb7d6df5693d1587bcc39">Api</a>
</li>
<li>signin_ended()
: <a class="el" href="d6/d75/a00604.php#ab5c7c1aaad0d03fadc18252e24301380">Api</a>
</li>
<li>signin_error()
: <a class="el" href="d6/d75/a00604.php#a3d35018066513c86a6dd65db10f8e74f">Api</a>
</li>
<li>signin_teammember_end()
: <a class="el" href="d6/d75/a00604.php#a2919e9666178e7ab5d8ff7a9425d3079">Api</a>
</li>
<li>signin_user_end()
: <a class="el" href="d6/d75/a00604.php#a7b1f827ec6102deb0b38e2f28089e1c1">Api</a>
</li>
<li>signingin()
: <a class="el" href="d4/d14/a00608.php#a30f9e20da21170b6fb4483631b8c2004">ConnectWindow</a>
, <a class="el" href="d4/d2a/a00632.php#a8606463f143a72c48e91ea047a4c0e14">SigninWindow</a>
</li>
<li>SigninWindow()
: <a class="el" href="d4/d2a/a00632.php#a97ffb6811b80312f4e6b18ff52ae2a80">SigninWindow</a>
</li>
<li>start
: <a class="el" href="dc/d4d/a00620.php#a4a917f6132e2bd44453278c22478a8a0">Pause</a>
</li>
<li>startMin
: <a class="el" href="d0/d8d/a00612.php#a580b0c6e1a15d88437107964687f1e6d">Globals</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
