<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: Class Members</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:22:26 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('functions_g.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
<div class="textblock">Here is a list of all class members with links to the classes they belong to:</div>

<h3><a id="index_g"></a>- g -</h3><ul>
<li>g_setAll()
: <a class="el" href="db/db5/a00616.php#ad5798c89ebbf4b15a1d76866903418c9">MainWindow</a>
</li>
<li>generalAllCheckstate()
: <a class="el" href="db/db5/a00616.php#a0b85a19da77d0bed72a37d6be5844b59">MainWindow</a>
, <a class="el" href="d1/d51/a00628.php#adc0b4a0a0877a77fcf6e4b0f8292da6c">RegisterWidget</a>
</li>
<li>generalCalculate()
: <a class="el" href="db/db5/a00616.php#ad3e2369acb314fbfea8a793858298b34">MainWindow</a>
</li>
<li>generalSaveDatas()
: <a class="el" href="db/db5/a00616.php#ac519892d0faafbd26acd7a7992f9285c">MainWindow</a>
</li>
<li>get()
: <a class="el" href="d3/dd6/a00624.php#aa8db337577269c54181be39771dcb771">Planning</a>
</li>
<li>getAll()
: <a class="el" href="d6/d75/a00604.php#a8690ac3b4f5e72aad8142f7d2bfd2695">Api</a>
</li>
<li>getAll_end()
: <a class="el" href="d6/d75/a00604.php#a38ddf54ba912805d223e8967979777d7">Api</a>
</li>
<li>getAll_ended()
: <a class="el" href="d6/d75/a00604.php#a4f7e78eeea139c6ba315568231646bcb">Api</a>
</li>
<li>getAll_error()
: <a class="el" href="d6/d75/a00604.php#aa74c11986db59a2ac20b3cad3f16d1b8">Api</a>
</li>
<li>getDaysOff()
: <a class="el" href="d1/d51/a00628.php#ab995ac919d7fbca08fcbfbba4172e0e7">RegisterWidget</a>
, <a class="el" href="db/ddc/a00636.php#a02c204e1e33c7bf33f6548a2dba11245">TeamMember</a>
</li>
<li>getFirstName()
: <a class="el" href="db/ddc/a00636.php#ac4d6bc292c6afb71eebd53f16a94ae08">TeamMember</a>
</li>
<li>getId()
: <a class="el" href="db/ddc/a00636.php#aa10064f3eb18d2d13d2525880fa18244">TeamMember</a>
</li>
<li>getLastName()
: <a class="el" href="db/ddc/a00636.php#a24581b40203c002d2cc0b450ddb355f9">TeamMember</a>
</li>
<li>getNbHours()
: <a class="el" href="db/ddc/a00636.php#a128f69981966608a96ad6922954e4484">TeamMember</a>
</li>
<li>getQTimeFromFloat()
: <a class="el" href="db/db5/a00616.php#ab6d7cca983665e8bc18712242c681de6">MainWindow</a>
</li>
<li>Globals()
: <a class="el" href="d0/d8d/a00612.php#a3b78cfdbe2809ad8b6b722969dda4425">Globals</a>
</li>
<li>goThrough()
: <a class="el" href="d4/d14/a00608.php#aa7a256669919cd96e7762c92152779d5">ConnectWindow</a>
, <a class="el" href="d4/d2a/a00632.php#a1b123d82f9403a25bf8742657ded6e0d">SigninWindow</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
