<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: File Members</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:22:26 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('globals_vars.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a id="index__"></a>- _ -</h3><ul>
<li>_autoChange
: <a class="el" href="d6/d5b/a00026.php#ae5f055afb0001ff1df4e16826739f01e">MainWindow_TabTeam.h</a>
</li>
<li>_g_allCheckbox
: <a class="el" href="db/db2/a00020.php#a86198bdf625ba8437a3b246c276ea92f">MainWindow_TabGeneral.h</a>
</li>
<li>_g_checkAllLay
: <a class="el" href="db/db2/a00020.php#af601725005062451128a68bd8b4bef16">MainWindow_TabGeneral.h</a>
</li>
<li>_g_checkDays
: <a class="el" href="db/db2/a00020.php#a5a697a415a6bd3ea900df3263ec8fb50">MainWindow_TabGeneral.h</a>
</li>
<li>_g_daysCheckboxes
: <a class="el" href="db/db2/a00020.php#acd897c5500b14f05008a6fb6b5bd2549">MainWindow_TabGeneral.h</a>
</li>
<li>_g_daysChoice
: <a class="el" href="db/db2/a00020.php#aed54bb47157c4e9b390032cfaec968dd">MainWindow_TabGeneral.h</a>
</li>
<li>_g_defaultHoursEdit
: <a class="el" href="db/db2/a00020.php#af3a4edd4145770993fa6c1b59069201a">MainWindow_TabGeneral.h</a>
</li>
<li>_g_defaultHoursLabel
: <a class="el" href="db/db2/a00020.php#a761a843ae86f410cba86e8e35251f40b">MainWindow_TabGeneral.h</a>
</li>
<li>_g_defaultHoursLay
: <a class="el" href="db/db2/a00020.php#a6f657732ef53bd9e0d8ba964310a352f">MainWindow_TabGeneral.h</a>
</li>
<li>_g_lay
: <a class="el" href="db/db2/a00020.php#a14b83b207289735b23c18ff7b932e2e5">MainWindow_TabGeneral.h</a>
</li>
<li>_g_maxTimeEdit
: <a class="el" href="db/db2/a00020.php#af2749df4850f52b15aac96e6042bd2e9">MainWindow_TabGeneral.h</a>
</li>
<li>_g_maxTimeLabel
: <a class="el" href="db/db2/a00020.php#aa4266cbdb9da42c6e93af815cf0a478a">MainWindow_TabGeneral.h</a>
</li>
<li>_g_maxTimeLay
: <a class="el" href="db/db2/a00020.php#abdde26b9858213e7206bbd78527c5ac1">MainWindow_TabGeneral.h</a>
</li>
<li>_g_minTimeEdit
: <a class="el" href="db/db2/a00020.php#a4fcbf4e3416128e6fe3e337f5e9e051e">MainWindow_TabGeneral.h</a>
</li>
<li>_g_minTimeLabel
: <a class="el" href="db/db2/a00020.php#a08a7f850ad388b1fea6e9d0378a52e3f">MainWindow_TabGeneral.h</a>
</li>
<li>_g_minTimeLay
: <a class="el" href="db/db2/a00020.php#a37ba1ebbe8b699b47d448ad0cac63650">MainWindow_TabGeneral.h</a>
</li>
<li>_g_tab
: <a class="el" href="db/db2/a00020.php#a60c1f00762e4914ed696d120a8b5ead4">MainWindow_TabGeneral.h</a>
</li>
<li>_g_toolBar
: <a class="el" href="db/db2/a00020.php#aa33d76537e81dfb4da8ddf922d823994">MainWindow_TabGeneral.h</a>
</li>
<li>_genAct
: <a class="el" href="db/db2/a00020.php#add9422d207b993237b0ec5621f4fb183">MainWindow_TabGeneral.h</a>
</li>
<li>_p_globals
: <a class="el" href="d3/d52/a00023.php#a475e73047eb49e0a343b0ce698940ff6">MainWindow_TabPlanning.h</a>
</li>
<li>_p_teamMembers
: <a class="el" href="d3/d52/a00023.php#aae400d773085b3f43d74f1e2a7ca9ad4">MainWindow_TabPlanning.h</a>
</li>
<li>_planning
: <a class="el" href="d3/d52/a00023.php#a2f9640096754da371c94ea3bfa15612a">MainWindow_TabPlanning.h</a>
</li>
<li>_planningLay
: <a class="el" href="d3/d52/a00023.php#a32ce8d745a199d80acf30735d87182bc">MainWindow_TabPlanning.h</a>
</li>
<li>_planningTab
: <a class="el" href="d3/d52/a00023.php#a75562f150b0ccf10fc44b3e5c114b623">MainWindow_TabPlanning.h</a>
</li>
<li>_saveAct
: <a class="el" href="db/db2/a00020.php#a43ab2541a0a0746e0125480828496ed9">MainWindow_TabGeneral.h</a>
</li>
<li>_syncAct
: <a class="el" href="db/db2/a00020.php#a3f3bade98b835919c98d64716f13c957">MainWindow_TabGeneral.h</a>
</li>
<li>_teamCenter
: <a class="el" href="d6/d5b/a00026.php#ae952d8ceff24bbf1b56ab06dbd79e73d">MainWindow_TabTeam.h</a>
</li>
<li>_teamLay
: <a class="el" href="d6/d5b/a00026.php#aa721ed9fbe17ba6dcfa32317a11fad57">MainWindow_TabTeam.h</a>
</li>
<li>_teamTab
: <a class="el" href="d6/d5b/a00026.php#a256022a1b3a0c865c991fcdb4a5c975b">MainWindow_TabTeam.h</a>
</li>
<li>_teamTable
: <a class="el" href="d6/d5b/a00026.php#ad2142a6c84ab21662e671a5bc353d318">MainWindow_TabTeam.h</a>
</li>
<li>_teamToolBar
: <a class="el" href="d6/d5b/a00026.php#af8e7a4be0f732bc4c2f39d6460b33581">MainWindow_TabTeam.h</a>
</li>
</ul>


<h3><a id="index_s"></a>- s -</h3><ul>
<li>selectedMember
: <a class="el" href="d6/d5b/a00026.php#ae2a23de97c9c87913b35d0a30501794b">MainWindow_TabTeam.h</a>
</li>
<li>selectedTeamMembers
: <a class="el" href="d6/d5b/a00026.php#ad0e998f81aaa3860a1eeb1853910bf8c">MainWindow_TabTeam.h</a>
</li>
</ul>


<h3><a id="index_t"></a>- t -</h3><ul>
<li>teamMembers
: <a class="el" href="d6/d5b/a00026.php#afeab32130bac1eae8af1358ea3b56e4a">MainWindow_TabTeam.h</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
