<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: Class Hierarchy</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:25:59 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('hierarchy.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Class Hierarchy</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock">
<p><a href="hierarchy.php">Go to the textual class hierarchy</a></p>
</div><table border="0" cellspacing="10" cellpadding="0">
<tr><td><img src="inherit_graph_0.png" border="0" alt="" usemap="#AddMemberModal"/>
<map name="AddMemberModal" id="AddMemberModal">
<area shape="rect" id="node2" href="d0/dec/a00592.php" title="AddMemberModal" alt="" coords="123,5,249,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_1.png" border="0" alt="" usemap="#Api"/>
<map name="Api" id="Api">
<area shape="rect" id="node2" href="d6/d75/a00604.php" title="A class to talk with the remote apis. " alt="" coords="124,5,165,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_2.png" border="0" alt="" usemap="#AuthMember"/>
<map name="AuthMember" id="AuthMember">
<area shape="rect" id="node1" href="d1/d8c/a00600.php" title="AuthMember" alt="" coords="5,5,101,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_3.png" border="0" alt="" usemap="#AuthUser"/>
<map name="AuthUser" id="AuthUser">
<area shape="rect" id="node1" href="dc/d25/a00596.php" title="AuthUser" alt="" coords="5,5,83,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_4.png" border="0" alt="" usemap="#ConnectWindow"/>
<map name="ConnectWindow" id="ConnectWindow">
<area shape="rect" id="node2" href="d4/d14/a00608.php" title="The main window of the software. " alt="" coords="160,5,279,32"/>
<area shape="rect" id="node3" href="db/db5/a00616.php" title="The main window of the software. " alt="" coords="171,56,268,83"/>
<area shape="rect" id="node4" href="d4/d2a/a00632.php" title="The main window of the software. " alt="" coords="167,107,272,133"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_5.png" border="0" alt="" usemap="#Globals"/>
<map name="Globals" id="Globals">
<area shape="rect" id="node1" href="d0/d8d/a00612.php" title="Globals" alt="" coords="5,5,72,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_6.png" border="0" alt="" usemap="#Pause"/>
<map name="Pause" id="Pause">
<area shape="rect" id="node1" href="dc/d4d/a00620.php" title="Pause" alt="" coords="5,5,64,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_7.png" border="0" alt="" usemap="#Planning"/>
<map name="Planning" id="Planning">
<area shape="rect" id="node1" href="d3/dd6/a00624.php" title="Planning" alt="" coords="5,5,77,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_8.png" border="0" alt="" usemap="#RegisterWidget"/>
<map name="RegisterWidget" id="RegisterWidget">
<area shape="rect" id="node2" href="d1/d51/a00628.php" title="The main window of the software. " alt="" coords="127,5,239,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_9.png" border="0" alt="" usemap="#TeamMember"/>
<map name="TeamMember" id="TeamMember">
<area shape="rect" id="node1" href="db/ddc/a00636.php" title="TeamMember" alt="" coords="5,5,108,32"/>
</map>
</td></tr>
</table>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
