<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: Member List</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:04:17 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d5/d39/a00676.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">TeamMember Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="../../d5/d39/a00676.php">TeamMember</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="../../d5/d39/a00676.php#a7769a0f39258773bb9b0b9348e8c1023">daysOffToQString</a>()</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d5/d39/a00676.php#a02c204e1e33c7bf33f6548a2dba11245">getDaysOff</a>() const</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d5/d39/a00676.php#ac4d6bc292c6afb71eebd53f16a94ae08">getFirstName</a>() const</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d5/d39/a00676.php#aa10064f3eb18d2d13d2525880fa18244">getId</a>() const</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d5/d39/a00676.php#a24581b40203c002d2cc0b450ddb355f9">getLastName</a>() const</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d5/d39/a00676.php#a128f69981966608a96ad6922954e4484">getNbHours</a>() const</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d5/d39/a00676.php#a81cb266afc04760039c97fce7d0c3a6d">operator&lt;&lt;</a>(std::ostream &amp;os, const TeamMember &amp;tm)</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d5/d39/a00676.php#a53ed47b4e7b64395257d398b35afbec9">operator&lt;&lt;</a>(std::ofstream &amp;os, const TeamMember &amp;tm)</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d5/d39/a00676.php#afb691011abf3878ec7dd37376242e28a">operator&gt;&gt;</a>(std::ifstream &amp;is, TeamMember &amp;tm)</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d5/d39/a00676.php#a7cef76489e5bd0fef1930ab423f7e380">setDaysOff</a>(std::vector&lt; QString &gt; &amp;daysOff)</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d5/d39/a00676.php#a4ba484e70a61bd21e947d473156b8b73">setDaysOffFromQString</a>(QString daysOff)</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d5/d39/a00676.php#a9981b2e29ca20e9bdb823b8681df0e78">setFirstName</a>(QString firstName)</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d5/d39/a00676.php#a86c4cdab5733790753d3ef79d376a303">setId</a>(const std::string &amp;id)</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d5/d39/a00676.php#a984fc107fe6518391b2d6a81204b3875">setLastName</a>(QString lastName)</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d5/d39/a00676.php#aa97881e8e23273d5ebfad4e9c397d235">setNbHours</a>(double nbHours)</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d5/d39/a00676.php#a07d4c8d564474101fd4a649ec79781bc">TeamMember</a>(const std::string &amp;id, double nbHours, QString firstName, QString lastName, const std::vector&lt; QString &gt; &amp;daysOff)</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d5/d39/a00676.php#a7fb6f36a42f3f021ee5142dcf8506dda">~TeamMember</a>()</td><td class="entry"><a class="el" href="../../d5/d39/a00676.php">TeamMember</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
