<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: QtFunctions.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:04:17 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d0/d89/a00071.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#typedef-members">Typedefs</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">QtFunctions.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &lt;QtWidgets&gt;</code><br />
<code>#include &quot;C++/C++.hpp&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for QtFunctions.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d6/d2c/a00072.png" border="0" usemap="#QtFunctions_8hpp" alt=""/></div>
<map name="QtFunctions_8hpp" id="QtFunctions_8hpp">
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d6e/a00073.png" border="0" usemap="#QtFunctions_8hppdep" alt=""/></div>
<map name="QtFunctions_8hppdep" id="QtFunctions_8hppdep">
<area shape="rect" id="node2" href="../../de/de1/a00065.php" title="QtDefines.hpp" alt="" coords="66,80,173,107"/>
<area shape="rect" id="node14" href="../../da/d24/a00068.php" title="QtFunctions.cpp" alt="" coords="197,80,316,107"/>
<area shape="rect" id="node3" href="../../df/d03/a00062.php" title="Qt.hpp" alt="" coords="89,155,150,181"/>
<area shape="rect" id="node4" href="../../d4/d8c/a00035.php" title="includes.h" alt="" coords="112,379,193,405"/>
<area shape="rect" id="node10" href="../../dc/d87/a00032.php" title="Globals.h" alt="" coords="21,229,98,256"/>
<area shape="rect" id="node12" href="../../d5/de0/a00050.php" title="Planning.h" alt="" coords="261,229,343,256"/>
<area shape="rect" id="node13" href="../../d3/d8b/a00059.php" title="TeamMember.h" alt="" coords="123,229,236,256"/>
<area shape="rect" id="node5" href="../../dc/dee/a00053.php" title="RegisterWidget.h" alt="" coords="83,453,206,480"/>
<area shape="rect" id="node7" href="../../d8/d41/a00038.php" title="MainWindow.h" alt="" coords="177,603,285,629"/>
<area shape="rect" id="node6" href="../../d7/d46/a00002.php" title="AddMemberModal.h" alt="" coords="75,528,214,555"/>
<area shape="rect" id="node9" href="../../d9/d2e/a00056.php" title="SigninWindow.h" alt="" coords="19,603,135,629"/>
<area shape="rect" id="node8" href="../../d5/d16/a00029.php" title="ConnectWindow.h" alt="" coords="80,677,209,704"/>
<area shape="rect" id="node11" href="../../dd/dad/a00005.php" title="Api.hpp" alt="" coords="137,304,203,331"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="typedef-members"></a>
Typedefs</h2></td></tr>
<tr class="memitem:ae996d9afaef5cea512610eaca0b204e4"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d89/a00071.php#ae996d9afaef5cea512610eaca0b204e4">QtWindow</a> = mcd::ContraptionAttr</td></tr>
<tr class="memdesc:ae996d9afaef5cea512610eaca0b204e4"><td class="mdescLeft">&#160;</td><td class="mdescRight">An alias for Qt.  <a href="#ae996d9afaef5cea512610eaca0b204e4">More...</a><br /></td></tr>
<tr class="separator:ae996d9afaef5cea512610eaca0b204e4"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a0272cd6761e50151f46337d1d7f793f2"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../d0/d89/a00071.php#ae996d9afaef5cea512610eaca0b204e4">QtWindow</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d89/a00071.php#a0272cd6761e50151f46337d1d7f793f2">getDesktopSize</a> ()</td></tr>
<tr class="memdesc:a0272cd6761e50151f46337d1d7f793f2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the size of the desktop.  <a href="#a0272cd6761e50151f46337d1d7f793f2">More...</a><br /></td></tr>
<tr class="separator:a0272cd6761e50151f46337d1d7f793f2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7a5b8564155df959a2ed36b171090ec2"><td class="memItemLeft" align="right" valign="top">size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d89/a00071.php#a7a5b8564155df959a2ed36b171090ec2">getDesktopWidth</a> ()</td></tr>
<tr class="memdesc:a7a5b8564155df959a2ed36b171090ec2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the width of the desktop.  <a href="#a7a5b8564155df959a2ed36b171090ec2">More...</a><br /></td></tr>
<tr class="separator:a7a5b8564155df959a2ed36b171090ec2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4e89aa67e6219267f0f2965567c447a5"><td class="memItemLeft" align="right" valign="top">size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d89/a00071.php#a4e89aa67e6219267f0f2965567c447a5">getDesktopHeight</a> ()</td></tr>
<tr class="memdesc:a4e89aa67e6219267f0f2965567c447a5"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the height of the desktop.  <a href="#a4e89aa67e6219267f0f2965567c447a5">More...</a><br /></td></tr>
<tr class="separator:a4e89aa67e6219267f0f2965567c447a5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac35a8acbe17be1d705ecf8d940eacc95"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d89/a00071.php#ac35a8acbe17be1d705ecf8d940eacc95">cssReader</a> (std::string path)</td></tr>
<tr class="memdesc:ac35a8acbe17be1d705ecf8d940eacc95"><td class="mdescLeft">&#160;</td><td class="mdescRight">Read a Cascade Style Sheet and translate it for Qt.  <a href="#ac35a8acbe17be1d705ecf8d940eacc95">More...</a><br /></td></tr>
<tr class="separator:ac35a8acbe17be1d705ecf8d940eacc95"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2a4db6b65fb8985d7fe716ee01eccdcd"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d89/a00071.php#a2a4db6b65fb8985d7fe716ee01eccdcd">clearLayout</a> (QLayout *layout)</td></tr>
<tr class="separator:a2a4db6b65fb8985d7fe716ee01eccdcd"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>02 juin 2018 </dd></dl>
</div><h2 class="groupheader">Typedef Documentation</h2>
<a id="ae996d9afaef5cea512610eaca0b204e4"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae996d9afaef5cea512610eaca0b204e4">&#9670;&nbsp;</a></span>QtWindow</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="../../d0/d89/a00071.php#ae996d9afaef5cea512610eaca0b204e4">QtWindow</a> =  mcd::ContraptionAttr</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>An alias for Qt. </p>

</div>
</div>
<h2 class="groupheader">Function Documentation</h2>
<a id="a2a4db6b65fb8985d7fe716ee01eccdcd"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a2a4db6b65fb8985d7fe716ee01eccdcd">&#9670;&nbsp;</a></span>clearLayout()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void clearLayout </td>
          <td>(</td>
          <td class="paramtype">QLayout *&#160;</td>
          <td class="paramname"><em>layout</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="ac35a8acbe17be1d705ecf8d940eacc95"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac35a8acbe17be1d705ecf8d940eacc95">&#9670;&nbsp;</a></span>cssReader()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string cssReader </td>
          <td>(</td>
          <td class="paramtype">std::string&#160;</td>
          <td class="paramname"><em>path</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Read a Cascade Style Sheet and translate it for Qt. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">path</td><td>The path to the file </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the file contents as a string </dd></dl>

</div>
</div>
<a id="a4e89aa67e6219267f0f2965567c447a5"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a4e89aa67e6219267f0f2965567c447a5">&#9670;&nbsp;</a></span>getDesktopHeight()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">size_t getDesktopHeight </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Get the height of the desktop. </p>
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d0/d89/a00071_a4e89aa67e6219267f0f2965567c447a5_cgraph.png" border="0" usemap="#d0/d89/a00071_a4e89aa67e6219267f0f2965567c447a5_cgraph" alt=""/></div>
<map name="d0/d89/a00071_a4e89aa67e6219267f0f2965567c447a5_cgraph" id="d0/d89/a00071_a4e89aa67e6219267f0f2965567c447a5_cgraph">
<area shape="rect" id="node2" href="../../da/d24/a00068.php#a0272cd6761e50151f46337d1d7f793f2" title="Get the size of the desktop. " alt="" coords="180,5,295,32"/>
</map>
</div>

</div>
</div>
<a id="a0272cd6761e50151f46337d1d7f793f2"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0272cd6761e50151f46337d1d7f793f2">&#9670;&nbsp;</a></span>getDesktopSize()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../d0/d89/a00071.php#ae996d9afaef5cea512610eaca0b204e4">QtWindow</a> getDesktopSize </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Get the size of the desktop. </p>
<dl class="section return"><dt>Returns</dt><dd>Return a QtWindow struct </dd></dl>

</div>
</div>
<a id="a7a5b8564155df959a2ed36b171090ec2"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7a5b8564155df959a2ed36b171090ec2">&#9670;&nbsp;</a></span>getDesktopWidth()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">size_t getDesktopWidth </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Get the width of the desktop. </p>
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d0/d89/a00071_a7a5b8564155df959a2ed36b171090ec2_cgraph.png" border="0" usemap="#d0/d89/a00071_a7a5b8564155df959a2ed36b171090ec2_cgraph" alt=""/></div>
<map name="d0/d89/a00071_a7a5b8564155df959a2ed36b171090ec2_cgraph" id="d0/d89/a00071_a7a5b8564155df959a2ed36b171090ec2_cgraph">
<area shape="rect" id="node2" href="../../da/d24/a00068.php#a0272cd6761e50151f46337d1d7f793f2" title="Get the size of the desktop. " alt="" coords="176,5,291,32"/>
</map>
</div>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_ed26a3555d00e4455851f1edbe2abea5.php">UQAC</a></li><li class="navelem"><a class="el" href="../../dir_72411d72a30b0a1d05f4f299c6dfb7e5.php">Cours2019-2020</a></li><li class="navelem"><a class="el" href="../../dir_3980970c724e97a7cae3ad342bc5e88e.php">Cours</a></li><li class="navelem"><a class="el" href="../../dir_de660acd428597c95c4dbb5b7e7040d2.php">T1_Genie_logiciel</a></li><li class="navelem"><a class="el" href="../../dir_2ed2da8857c2ea9b402c35adb582720e.php">Projet</a></li><li class="navelem"><a class="el" href="../../dir_a775c7fce4d0a7a4e13e85e05d64f23a.php">project_GL_uqac_automne2019</a></li><li class="navelem"><a class="el" href="../../dir_11f7a8fe58957f41539c5c2e1ae91c25.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_78a63cdfa5ba1108a1c6943bc3305158.php">Widgets</a></li><li class="navelem"><a class="el" href="../../d0/d89/a00071.php">QtFunctions.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
