<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: MainWindow_TabGeneral.h File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:22:26 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('db/db2/a00020.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#define-members">Macros</a> &#124;
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">MainWindow_TabGeneral.h File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d7/de0/a00022.png" border="0" usemap="#MainWindow__TabGeneral_8hdep" alt=""/></div>
<map name="MainWindow__TabGeneral_8hdep" id="MainWindow__TabGeneral_8hdep">
<area shape="rect" id="node2" href="../../d4/d51/a00017.php" title="MainWindow.h" alt="" coords="43,80,151,107"/>
<area shape="rect" id="node3" href="../../d4/dee/a00008.php" title="ConnectWindow.h" alt="" coords="32,155,161,181"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="define-members"></a>
Macros</h2></td></tr>
<tr class="memitem:a3b482e7ec3298a5ebb6c0046a26cf975"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d51/a00017.php#a3b482e7ec3298a5ebb6c0046a26cf975">HEADER_MAINWINDOW_TAB_GENERAL</a></td></tr>
<tr class="separator:a3b482e7ec3298a5ebb6c0046a26cf975"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:ae2751f858e549c3116e32123642f0db0"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#ae2751f858e549c3116e32123642f0db0">generalAllCheckstate</a> (int state)</td></tr>
<tr class="separator:ae2751f858e549c3116e32123642f0db0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a22cb2e47048321ba89927c5373413b3a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a22cb2e47048321ba89927c5373413b3a">generalSaveDatas</a> ()</td></tr>
<tr class="separator:a22cb2e47048321ba89927c5373413b3a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a35c99caa0393c63ef04f7bfae0714fdc"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a35c99caa0393c63ef04f7bfae0714fdc">generalCalculate</a> ()</td></tr>
<tr class="separator:a35c99caa0393c63ef04f7bfae0714fdc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a712cf2f2a1f96c4d74738b9e13707268"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a712cf2f2a1f96c4d74738b9e13707268">reenableSave</a> ()</td></tr>
<tr class="separator:a712cf2f2a1f96c4d74738b9e13707268"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a31ab159a75215992c70ffcdc0332f132"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a31ab159a75215992c70ffcdc0332f132">reenableGen</a> ()</td></tr>
<tr class="separator:a31ab159a75215992c70ffcdc0332f132"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a816e0a647db399f4210f62ca0053898a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a816e0a647db399f4210f62ca0053898a">computeIfNeeded</a> ()</td></tr>
<tr class="separator:a816e0a647db399f4210f62ca0053898a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0721d2b5d66bc460030ffc967fdffa70"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a0721d2b5d66bc460030ffc967fdffa70">g_setAll</a> (const <a class="el" href="../../d0/d8d/a00612.php">Globals</a> &amp;gl, const std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt; &amp;tm, const <a class="el" href="../../d3/dd6/a00624.php">Planning</a> &amp;pl)</td></tr>
<tr class="separator:a0721d2b5d66bc460030ffc967fdffa70"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afe349ec72ae5743900042b8ce1672030"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#afe349ec72ae5743900042b8ce1672030">initGeneralTab</a> (QTabWidget *tabWidget)</td></tr>
<tr class="separator:afe349ec72ae5743900042b8ce1672030"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a56764a46776c3a3e04c3cc2f0be28838"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a56764a46776c3a3e04c3cc2f0be28838">initGeneralTab</a> (QTabWidget *tabWidget, <a class="el" href="../../d0/d8d/a00612.php">Globals</a> initGlob)</td></tr>
<tr class="separator:a56764a46776c3a3e04c3cc2f0be28838"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad6ac3589416cffbe1e02509ec04fa697"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#ad6ac3589416cffbe1e02509ec04fa697">resetGeneralTab</a> (QTabWidget *tabWidget)</td></tr>
<tr class="separator:ad6ac3589416cffbe1e02509ec04fa697"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8dea9ca339cd5e4a4cea6ca2ff684baf"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a8dea9ca339cd5e4a4cea6ca2ff684baf">deleteGeneralTab</a> (QTabWidget *tabWidget)</td></tr>
<tr class="separator:a8dea9ca339cd5e4a4cea6ca2ff684baf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac86fb2a6a9851dba2b051ee939f5d7a1"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#ac86fb2a6a9851dba2b051ee939f5d7a1">setValues</a> (<a class="el" href="../../d0/d8d/a00612.php">Globals</a> initGlob)</td></tr>
<tr class="separator:ac86fb2a6a9851dba2b051ee939f5d7a1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a38d744f59bb514c7fa1b6abe83744066"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../d0/d8d/a00612.php">Globals</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a38d744f59bb514c7fa1b6abe83744066">translate</a> ()</td></tr>
<tr class="separator:a38d744f59bb514c7fa1b6abe83744066"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adf6a730c652b6954833f36d01ff49e62"><td class="memItemLeft" align="right" valign="top">QTime&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#adf6a730c652b6954833f36d01ff49e62">getQTimeFromFloat</a> (float time)</td></tr>
<tr class="separator:adf6a730c652b6954833f36d01ff49e62"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:a60c1f00762e4914ed696d120a8b5ead4"><td class="memItemLeft" align="right" valign="top">QWidget *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a60c1f00762e4914ed696d120a8b5ead4">_g_tab</a></td></tr>
<tr class="separator:a60c1f00762e4914ed696d120a8b5ead4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a14b83b207289735b23c18ff7b932e2e5"><td class="memItemLeft" align="right" valign="top">QVBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a14b83b207289735b23c18ff7b932e2e5">_g_lay</a></td></tr>
<tr class="separator:a14b83b207289735b23c18ff7b932e2e5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aed54bb47157c4e9b390032cfaec968dd"><td class="memItemLeft" align="right" valign="top">QVBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#aed54bb47157c4e9b390032cfaec968dd">_g_daysChoice</a></td></tr>
<tr class="separator:aed54bb47157c4e9b390032cfaec968dd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af601725005062451128a68bd8b4bef16"><td class="memItemLeft" align="right" valign="top">QHBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#af601725005062451128a68bd8b4bef16">_g_checkAllLay</a></td></tr>
<tr class="separator:af601725005062451128a68bd8b4bef16"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a86198bdf625ba8437a3b246c276ea92f"><td class="memItemLeft" align="right" valign="top">QCheckBox *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a86198bdf625ba8437a3b246c276ea92f">_g_allCheckbox</a></td></tr>
<tr class="separator:a86198bdf625ba8437a3b246c276ea92f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5a697a415a6bd3ea900df3263ec8fb50"><td class="memItemLeft" align="right" valign="top">QHBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a5a697a415a6bd3ea900df3263ec8fb50">_g_checkDays</a></td></tr>
<tr class="separator:a5a697a415a6bd3ea900df3263ec8fb50"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acd897c5500b14f05008a6fb6b5bd2549"><td class="memItemLeft" align="right" valign="top">std::map&lt; std::string, QCheckBox * &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#acd897c5500b14f05008a6fb6b5bd2549">_g_daysCheckboxes</a></td></tr>
<tr class="separator:acd897c5500b14f05008a6fb6b5bd2549"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a37ba1ebbe8b699b47d448ad0cac63650"><td class="memItemLeft" align="right" valign="top">QHBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a37ba1ebbe8b699b47d448ad0cac63650">_g_minTimeLay</a></td></tr>
<tr class="separator:a37ba1ebbe8b699b47d448ad0cac63650"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4fcbf4e3416128e6fe3e337f5e9e051e"><td class="memItemLeft" align="right" valign="top">QTimeEdit *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a4fcbf4e3416128e6fe3e337f5e9e051e">_g_minTimeEdit</a></td></tr>
<tr class="separator:a4fcbf4e3416128e6fe3e337f5e9e051e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a08a7f850ad388b1fea6e9d0378a52e3f"><td class="memItemLeft" align="right" valign="top">QLabel *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a08a7f850ad388b1fea6e9d0378a52e3f">_g_minTimeLabel</a></td></tr>
<tr class="separator:a08a7f850ad388b1fea6e9d0378a52e3f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abdde26b9858213e7206bbd78527c5ac1"><td class="memItemLeft" align="right" valign="top">QHBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#abdde26b9858213e7206bbd78527c5ac1">_g_maxTimeLay</a></td></tr>
<tr class="separator:abdde26b9858213e7206bbd78527c5ac1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af2749df4850f52b15aac96e6042bd2e9"><td class="memItemLeft" align="right" valign="top">QTimeEdit *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#af2749df4850f52b15aac96e6042bd2e9">_g_maxTimeEdit</a></td></tr>
<tr class="separator:af2749df4850f52b15aac96e6042bd2e9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa4266cbdb9da42c6e93af815cf0a478a"><td class="memItemLeft" align="right" valign="top">QLabel *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#aa4266cbdb9da42c6e93af815cf0a478a">_g_maxTimeLabel</a></td></tr>
<tr class="separator:aa4266cbdb9da42c6e93af815cf0a478a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6f657732ef53bd9e0d8ba964310a352f"><td class="memItemLeft" align="right" valign="top">QHBoxLayout *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a6f657732ef53bd9e0d8ba964310a352f">_g_defaultHoursLay</a></td></tr>
<tr class="separator:a6f657732ef53bd9e0d8ba964310a352f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af3a4edd4145770993fa6c1b59069201a"><td class="memItemLeft" align="right" valign="top">QDoubleSpinBox *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#af3a4edd4145770993fa6c1b59069201a">_g_defaultHoursEdit</a></td></tr>
<tr class="separator:af3a4edd4145770993fa6c1b59069201a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a761a843ae86f410cba86e8e35251f40b"><td class="memItemLeft" align="right" valign="top">QLabel *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a761a843ae86f410cba86e8e35251f40b">_g_defaultHoursLabel</a></td></tr>
<tr class="separator:a761a843ae86f410cba86e8e35251f40b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa33d76537e81dfb4da8ddf922d823994"><td class="memItemLeft" align="right" valign="top">QToolBar *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#aa33d76537e81dfb4da8ddf922d823994">_g_toolBar</a></td></tr>
<tr class="separator:aa33d76537e81dfb4da8ddf922d823994"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a43ab2541a0a0746e0125480828496ed9"><td class="memItemLeft" align="right" valign="top">QAction *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a43ab2541a0a0746e0125480828496ed9">_saveAct</a></td></tr>
<tr class="separator:a43ab2541a0a0746e0125480828496ed9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:add9422d207b993237b0ec5621f4fb183"><td class="memItemLeft" align="right" valign="top">QAction *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#add9422d207b993237b0ec5621f4fb183">_genAct</a></td></tr>
<tr class="separator:add9422d207b993237b0ec5621f4fb183"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3f3bade98b835919c98d64716f13c957"><td class="memItemLeft" align="right" valign="top">QAction *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a3f3bade98b835919c98d64716f13c957">_syncAct</a></td></tr>
<tr class="separator:a3f3bade98b835919c98d64716f13c957"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Macro Definition Documentation</h2>
<a id="a3b482e7ec3298a5ebb6c0046a26cf975"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3b482e7ec3298a5ebb6c0046a26cf975">&#9670;&nbsp;</a></span>HEADER_MAINWINDOW_TAB_GENERAL</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define HEADER_MAINWINDOW_TAB_GENERAL</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Function Documentation</h2>
<a id="a816e0a647db399f4210f62ca0053898a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a816e0a647db399f4210f62ca0053898a">&#9670;&nbsp;</a></span>computeIfNeeded()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void computeIfNeeded </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a8dea9ca339cd5e4a4cea6ca2ff684baf"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a8dea9ca339cd5e4a4cea6ca2ff684baf">&#9670;&nbsp;</a></span>deleteGeneralTab()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void deleteGeneralTab </td>
          <td>(</td>
          <td class="paramtype">QTabWidget *&#160;</td>
          <td class="paramname"><em>tabWidget</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a0721d2b5d66bc460030ffc967fdffa70"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0721d2b5d66bc460030ffc967fdffa70">&#9670;&nbsp;</a></span>g_setAll()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void g_setAll </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="../../d0/d8d/a00612.php">Globals</a> &amp;&#160;</td>
          <td class="paramname"><em>gl</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::vector&lt; <a class="el" href="../../db/ddc/a00636.php">TeamMember</a> &gt; &amp;&#160;</td>
          <td class="paramname"><em>tm</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="../../d3/dd6/a00624.php">Planning</a> &amp;&#160;</td>
          <td class="paramname"><em>pl</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="ae2751f858e549c3116e32123642f0db0"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae2751f858e549c3116e32123642f0db0">&#9670;&nbsp;</a></span>generalAllCheckstate()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void generalAllCheckstate </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>state</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a35c99caa0393c63ef04f7bfae0714fdc"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a35c99caa0393c63ef04f7bfae0714fdc">&#9670;&nbsp;</a></span>generalCalculate()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void generalCalculate </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a22cb2e47048321ba89927c5373413b3a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a22cb2e47048321ba89927c5373413b3a">&#9670;&nbsp;</a></span>generalSaveDatas()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void generalSaveDatas </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="adf6a730c652b6954833f36d01ff49e62"></a>
<h2 class="memtitle"><span class="permalink"><a href="#adf6a730c652b6954833f36d01ff49e62">&#9670;&nbsp;</a></span>getQTimeFromFloat()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QTime getQTimeFromFloat </td>
          <td>(</td>
          <td class="paramtype">float&#160;</td>
          <td class="paramname"><em>time</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="afe349ec72ae5743900042b8ce1672030"></a>
<h2 class="memtitle"><span class="permalink"><a href="#afe349ec72ae5743900042b8ce1672030">&#9670;&nbsp;</a></span>initGeneralTab() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void initGeneralTab </td>
          <td>(</td>
          <td class="paramtype">QTabWidget *&#160;</td>
          <td class="paramname"><em>tabWidget</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a56764a46776c3a3e04c3cc2f0be28838"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a56764a46776c3a3e04c3cc2f0be28838">&#9670;&nbsp;</a></span>initGeneralTab() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void initGeneralTab </td>
          <td>(</td>
          <td class="paramtype">QTabWidget *&#160;</td>
          <td class="paramname"><em>tabWidget</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="../../d0/d8d/a00612.php">Globals</a>&#160;</td>
          <td class="paramname"><em>initGlob</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a31ab159a75215992c70ffcdc0332f132"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a31ab159a75215992c70ffcdc0332f132">&#9670;&nbsp;</a></span>reenableGen()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void reenableGen </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a712cf2f2a1f96c4d74738b9e13707268"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a712cf2f2a1f96c4d74738b9e13707268">&#9670;&nbsp;</a></span>reenableSave()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void reenableSave </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="ad6ac3589416cffbe1e02509ec04fa697"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ad6ac3589416cffbe1e02509ec04fa697">&#9670;&nbsp;</a></span>resetGeneralTab()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void resetGeneralTab </td>
          <td>(</td>
          <td class="paramtype">QTabWidget *&#160;</td>
          <td class="paramname"><em>tabWidget</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ac86fb2a6a9851dba2b051ee939f5d7a1"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac86fb2a6a9851dba2b051ee939f5d7a1">&#9670;&nbsp;</a></span>setValues()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void setValues </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../d0/d8d/a00612.php">Globals</a>&#160;</td>
          <td class="paramname"><em>initGlob</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a38d744f59bb514c7fa1b6abe83744066"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a38d744f59bb514c7fa1b6abe83744066">&#9670;&nbsp;</a></span>translate()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../d0/d8d/a00612.php">Globals</a> translate </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a id="a86198bdf625ba8437a3b246c276ea92f"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a86198bdf625ba8437a3b246c276ea92f">&#9670;&nbsp;</a></span>_g_allCheckbox</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QCheckBox* _g_allCheckbox</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="af601725005062451128a68bd8b4bef16"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af601725005062451128a68bd8b4bef16">&#9670;&nbsp;</a></span>_g_checkAllLay</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QHBoxLayout* _g_checkAllLay</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a5a697a415a6bd3ea900df3263ec8fb50"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a5a697a415a6bd3ea900df3263ec8fb50">&#9670;&nbsp;</a></span>_g_checkDays</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QHBoxLayout* _g_checkDays</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="acd897c5500b14f05008a6fb6b5bd2549"></a>
<h2 class="memtitle"><span class="permalink"><a href="#acd897c5500b14f05008a6fb6b5bd2549">&#9670;&nbsp;</a></span>_g_daysCheckboxes</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::map&lt;std::string, QCheckBox*&gt; _g_daysCheckboxes</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="aed54bb47157c4e9b390032cfaec968dd"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aed54bb47157c4e9b390032cfaec968dd">&#9670;&nbsp;</a></span>_g_daysChoice</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QVBoxLayout* _g_daysChoice</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="af3a4edd4145770993fa6c1b59069201a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af3a4edd4145770993fa6c1b59069201a">&#9670;&nbsp;</a></span>_g_defaultHoursEdit</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QDoubleSpinBox* _g_defaultHoursEdit</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a761a843ae86f410cba86e8e35251f40b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a761a843ae86f410cba86e8e35251f40b">&#9670;&nbsp;</a></span>_g_defaultHoursLabel</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QLabel* _g_defaultHoursLabel</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a6f657732ef53bd9e0d8ba964310a352f"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a6f657732ef53bd9e0d8ba964310a352f">&#9670;&nbsp;</a></span>_g_defaultHoursLay</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QHBoxLayout* _g_defaultHoursLay</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a14b83b207289735b23c18ff7b932e2e5"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a14b83b207289735b23c18ff7b932e2e5">&#9670;&nbsp;</a></span>_g_lay</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QVBoxLayout* _g_lay</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="af2749df4850f52b15aac96e6042bd2e9"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af2749df4850f52b15aac96e6042bd2e9">&#9670;&nbsp;</a></span>_g_maxTimeEdit</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QTimeEdit* _g_maxTimeEdit</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="aa4266cbdb9da42c6e93af815cf0a478a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa4266cbdb9da42c6e93af815cf0a478a">&#9670;&nbsp;</a></span>_g_maxTimeLabel</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QLabel* _g_maxTimeLabel</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="abdde26b9858213e7206bbd78527c5ac1"></a>
<h2 class="memtitle"><span class="permalink"><a href="#abdde26b9858213e7206bbd78527c5ac1">&#9670;&nbsp;</a></span>_g_maxTimeLay</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QHBoxLayout* _g_maxTimeLay</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a4fcbf4e3416128e6fe3e337f5e9e051e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a4fcbf4e3416128e6fe3e337f5e9e051e">&#9670;&nbsp;</a></span>_g_minTimeEdit</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QTimeEdit* _g_minTimeEdit</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a08a7f850ad388b1fea6e9d0378a52e3f"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a08a7f850ad388b1fea6e9d0378a52e3f">&#9670;&nbsp;</a></span>_g_minTimeLabel</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QLabel* _g_minTimeLabel</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a37ba1ebbe8b699b47d448ad0cac63650"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a37ba1ebbe8b699b47d448ad0cac63650">&#9670;&nbsp;</a></span>_g_minTimeLay</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QHBoxLayout* _g_minTimeLay</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a60c1f00762e4914ed696d120a8b5ead4"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a60c1f00762e4914ed696d120a8b5ead4">&#9670;&nbsp;</a></span>_g_tab</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QWidget* _g_tab</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="aa33d76537e81dfb4da8ddf922d823994"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa33d76537e81dfb4da8ddf922d823994">&#9670;&nbsp;</a></span>_g_toolBar</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QToolBar* _g_toolBar</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="add9422d207b993237b0ec5621f4fb183"></a>
<h2 class="memtitle"><span class="permalink"><a href="#add9422d207b993237b0ec5621f4fb183">&#9670;&nbsp;</a></span>_genAct</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QAction* _genAct</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a43ab2541a0a0746e0125480828496ed9"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a43ab2541a0a0746e0125480828496ed9">&#9670;&nbsp;</a></span>_saveAct</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QAction* _saveAct</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a3f3bade98b835919c98d64716f13c957"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3f3bade98b835919c98d64716f13c957">&#9670;&nbsp;</a></span>_syncAct</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QAction* _syncAct</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_ed26a3555d00e4455851f1edbe2abea5.php">UQAC</a></li><li class="navelem"><a class="el" href="../../dir_72411d72a30b0a1d05f4f299c6dfb7e5.php">Cours2019-2020</a></li><li class="navelem"><a class="el" href="../../dir_3980970c724e97a7cae3ad342bc5e88e.php">Cours</a></li><li class="navelem"><a class="el" href="../../dir_de660acd428597c95c4dbb5b7e7040d2.php">T1_Genie_logiciel</a></li><li class="navelem"><a class="el" href="../../dir_2ed2da8857c2ea9b402c35adb582720e.php">Projet</a></li><li class="navelem"><a class="el" href="../../dir_a775c7fce4d0a7a4e13e85e05d64f23a.php">project_GL_uqac_automne2019</a></li><li class="navelem"><a class="el" href="../../dir_11f7a8fe58957f41539c5c2e1ae91c25.php">inc</a></li><li class="navelem"><a class="el" href="../../db/db2/a00020.php">MainWindow_TabGeneral.h</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
