<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: Member List</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:04:17 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('dc/df2/a00656.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">MainWindow Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="../../dc/df2/a00656.php">MainWindow</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="../../dc/df2/a00656.php#afb4788b7a84063543823a0feb8d134b9">_p_globals</a></td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/df2/a00656.php#a6b1643e8e22c9319b8930f8c1780560c">_p_teamMembers</a></td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/df2/a00656.php#afbf23089969aeac3ae5ae2dc194460ef">addMember</a>()</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/df2/a00656.php#a18dc86b52aff39ce15c68150d6381e7f">computeIfNeeded</a>()</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/df2/a00656.php#a152f25e38ce6c4087fc2bfebd67ba2b7">deleteMember</a>()</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/df2/a00656.php#a4635fbbd25941294d7ddd280489092a8">editMember</a>(QTableWidgetItem *item)</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/df2/a00656.php#ad5798c89ebbf4b15a1d76866903418c9">g_setAll</a>(const Globals &amp;gl, const std::vector&lt; TeamMember &gt; &amp;tm, const Planning &amp;pl)</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/df2/a00656.php#a0b85a19da77d0bed72a37d6be5844b59">generalAllCheckstate</a>(int state)</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/df2/a00656.php#ad3e2369acb314fbfea8a793858298b34">generalCalculate</a>()</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/df2/a00656.php#ac519892d0faafbd26acd7a7992f9285c">generalSaveDatas</a>()</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/df2/a00656.php#ae21b4ca2c156eb550dcfec3df44cc71a">initWindow</a>()</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/df2/a00656.php#a221eba81c17c821ef10640da071f8ea9">MainWindow</a>(Api &amp;api, QWidget *parent=nullptr)</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/df2/a00656.php#a17791c185ba058b9c17f7e4f070cb09b">operator==</a>(const TeamMember &amp;a, const int &amp;b)</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/df2/a00656.php#a16ccde3508f4c90dde1b350fec24e48c">p_setAll</a>(const Globals &amp;gl, const std::vector&lt; TeamMember &gt; &amp;tm, const Planning &amp;pl)</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/df2/a00656.php#a7ec5a016e64ca83adf9bdf30513b190c">reenableGen</a>()</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/df2/a00656.php#a505c75251a666a8da570e569e864e346">reenableSave</a>()</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/df2/a00656.php#a173388227e3b48ce310ff34be1f3535e">t_setAll</a>(const Globals &amp;gl, const std::vector&lt; TeamMember &gt; &amp;tm, const Planning &amp;pl)</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dc/df2/a00656.php#ae7370d2140bb3823dfd8cc85ef4e6161">updateSelectedMember</a>(int row, int)</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dc/df2/a00656.php#a9a780b70b080b3e745298191099bba4d">~MainWindow</a>()</td><td class="entry"><a class="el" href="../../dc/df2/a00656.php">MainWindow</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
</table></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
