<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>Planning Generator: Member List</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">Planning Generator
									&#160;<span id="projectnumber">1.0</span>
								</div>
								<div id="projectbrief">A software to generate some plannings according to specifications.</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 27 2019 12:25:59 for Planning Generator by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d6/d75/a00604.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Api Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="../../d6/d75/a00604.php">Api</a>, including all inherited members.</p>
<table class="directory">
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>_chef</b> (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">private</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>_firstGet</b> (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">private</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>_host</b> (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>_managers</b> (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>_teamid</b> (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">private</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>_teammemberid</b> (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">private</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>_token</b> (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">private</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>_urls</b> (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>_userid</b> (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">private</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>_username</b> (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">private</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d6/d75/a00604.php#a84682b994ff76304c01175d83bb62544">Api</a>()</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>auth</b>(const std::string &amp;user, const std::string &amp;pass) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>auth_end</b>(QNetworkReply *reply) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>auth_ended</b>() (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>auth_error</b>() (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>base64_encode</b>(const std::string &amp;str) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>compute</b>() (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>compute_end</b>(QNetworkReply *reply) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>compute_ended</b>() (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>compute_error</b>() (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>connection</b>(const std::string &amp;host) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>createRequest</b>(const std::string &amp;url, const std::string &amp;managerName) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">private</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>createUrl</b>(const std::string &amp;str) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">private</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>deleteMember</b>(const std::string &amp;id) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>getAll</b>() (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>getAll_end</b>(QNetworkReply *reply) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>getAll_ended</b>() (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>getAll_ended</b>(const Globals &amp;globals, const std::vector&lt; TeamMember &gt; &amp;teamMembers, const Planning &amp;planning) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>getAll_error</b>() (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>isChef</b>() const (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>jsonParse</b>(const std::string &amp;str) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">private</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>printJsonError</b>(const QJsonObject &amp;json) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">private</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>register_end</b>(QNetworkReply *reply) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>register_team_end</b>(QNetworkReply *reply) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>register_teammember_end</b>(QNetworkReply *reply) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>register_user_end</b>(QNetworkReply *reply) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>save</b>(const Globals &amp;team, const Planning &amp;planning) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>save_end</b>(QNetworkReply *reply) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>save_ended</b>() (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>save_error</b>() (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>saveMembers</b>(const std::vector&lt; TeamMember &gt; &amp;team) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>saveMembers_end</b>(QNetworkReply *reply) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>saveMembers_ended</b>() (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>saveMembers_error</b>() (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>signin</b>(const AuthUser &amp;user, const AuthMember &amp;member, const std::string &amp;teamName) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>signin</b>(const AuthUser &amp;user, const AuthMember &amp;member) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>signin_ended</b>() (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>signin_ended</b>(const std::string &amp;id) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>signin_error</b>() (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>signin_error</b>(const std::string &amp;id) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">signal</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>signin_teammember_end</b>(QNetworkReply *reply) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>signin_user_end</b>(QNetworkReply *reply) (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>~Api</b>() (defined in <a class="el" href="../../d6/d75/a00604.php">Api</a>)</td><td class="entry"><a class="el" href="../../d6/d75/a00604.php">Api</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
</table></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
